### ISSUE TITLE
Connection dropped after 20-40 min of inactivity

### ISSUE THREAD

**Issue by sagor999** [projectcalico/cni-plugin#1006]
We having an issue with connections being dropped after 20-40 min of inactivity.
It affects two of our services right now, (one is mysql, another one is custom application), but both exhibit same behavior.
We have recently moved those services to a new cluster, that uses calico in eBPF mode (with kube-proxy disabled). 
Previous cluster was using calico in non ebpf mode, with kube-proxy in iptables mode and was not exhibiting this behavior.

Are there any configuration settings in ebpf that might affect this behavior?

Cluster is running on bare-metal. 

Running this on the node that has affected pod running:
`tc -s qdisc show dev enp216s0d1`
I get following:
```
qdisc clsact ffff: parent ffff:fff1 
 Sent 3551593575246 bytes 972860182 pkt (dropped 1571, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
```
Which shows some packets are being dropped. But I cannot quite correlate this number increasing with the actual dropped connection in mysql or another service. 

Felix config:
```
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: FelixConfiguration
  metadata:
    creationTimestamp: "2020-11-13T20:00:16Z"
    name: default
    resourceVersion: "1673955"
    uid: 548c407d-d383-4bea-9a4f-0f1e9c7f6b72
  spec:
    bpfEnabled: true
    bpfLogLevel: ""
    ipipEnabled: true
    logSeverityScreen: Info
    prometheusMetricsEnabled: true
    reportingInterval: 0s
kind: FelixConfigurationList
metadata:
  resourceVersion: "28356149"
```

There are no errors reported in calico pods.

This is an example of an error that is reported by mysql:
```
2021-01-04T19:32:30.207840Z 56153 [Note] Aborted connection 56153 to db: 'x' user: 'webapp' host: '100.64.114.45' (Got timeout reading communication packets) 
```
This is internal cluster traffic.
Meaning communication is between pods within the cluster.

I am wondering if there is any settings in calico that might be potentially affecting this behavior? 

## Expected Behavior
Connections that have long periods of inactivity shouldn't be dropped.

## Current Behavior
Connections with long period of inactivity seem to be getting dropped.

## Steps to Reproduce (for bugs)
Create an application that has very long times of network inactivity. (30min+).
Observe that when attempting to communicate after long time of inactivity, connection is severed.

## Context
Affects various deployments in our cluster.

## Your Environment
Calico: 3.17.1
K8s: 1.18.13
OS: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-53-generic x86_64)

**Comment by caseydavenport** [comment]
@fasaxc @tomastigera since it sounds like this might be an eBPF data plane issue

**Comment by fasaxc** [comment]
I believe the timeout is an hour right now; you might want to turn on TCP keepalives to make sure you don't have sockets with no packets for that long.

**Comment by sagor999** [comment]
Good to know about 1 hour timeout. 
We have made a workaround on our end and I believe everything is working fine now. 
I will close this issue now. 
Thank you!

**Comment by fasaxc** [comment]
Thanks for the feedback that this is an issue.  Over time I'm sure we'll improve/add configuration for these timeouts.
