### ISSUE TITLE
one of calico-node always restart 

### ISSUE THREAD

**Issue by ShawnBian** [projectcalico/cni-plugin#1060]
## Expected Behavior
the calico-node pods should not restart frequently

## Current Behavior
one of calico-node always restart ,the rest of calico-node pods is woking normally 
## Your Environment
K8S version: 1.19.5
[root@master1 ~]# kubectl get pods -n kube-system -o wide
NAME                                       READY   STATUS             RESTARTS   AGE     IP             NODE      NOMINATED NODE   READINESS GATES
calico-kube-controllers-744cfdf676-vccbf   1/1     Running            13         7d21h   10.244.2.55    node2     <none>           <none>
calico-node-44snf                          1/1     Running            16         37d     192.168.1.8    node3     <none>           <none>
calico-node-8p8t7                          1/1     Running            14         37d     192.168.1.7    node2     <none>           <none>
calico-node-b6vq7                          1/1     Running            15         37d     192.168.1.4    master1   <none>           <none>
calico-node-c78tx                          1/1     Running            4          37d     192.168.1.84   node5     <none>           <none>
calico-node-kxr4w                          0/1     CrashLoopBackOff   34         107m    192.168.1.6    node1     <none>           <none>
calico-node-qxp4w                          1/1     Running            13         37d     192.168.1.11   node4     <none>           <none>
calico-node-x66zq                          1/1     Running            18         37d     192.168.1.5    master2   <none>           <none>
coredns-569c5fb746-vkjlr                   1/1     Running            0          51m     10.244.4.43    node4     <none>           <none>

[root@master1 ~]# kubectl describe pods -n kube-system calico-node-kxr4w
Name:                 calico-node-kxr4w
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 node1/192.168.1.6
Start Time:           Sun, 11 Apr 2021 12:51:46 +0800
Labels:               controller-revision-hash=5fdfc55756
                      k8s-app=calico-node
                      pod-template-generation=2
Annotations:          kubectl.kubernetes.io/restartedAt: 2021-03-04T17:39:22+08:00
Status:               Running
IP:                   192.168.1.6
IPs:
  IP:           192.168.1.6
Controlled By:  DaemonSet/calico-node
Init Containers:
  upgrade-ipam:
    Container ID:  docker://9833bceeddf1bb043081e9077a7823eb6699ae5f775d034b81cd930f33415634
    Image:         docker.io/calico/cni:v3.17.1
    Image ID:      docker-pullable://calico/cni@sha256:3dc2506632843491864ce73a6e73d5bba7d0dc25ec0df00c1baa91d17549b068
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/calico-ipam
      -upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 11 Apr 2021 13:47:57 +0800
      Finished:     Sun, 11 Apr 2021 13:47:59 +0800
    Ready:          True
    Restart Count:  2
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      KUBERNETES_NODE_NAME:        (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:  <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/lib/cni/networks from host-local-net-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-wm8g8 (ro)
  install-cni:
    Container ID:  docker://709b9dd0105698b0610da0a8b716ff16cd63c4e5e1aeb10187cf5021748357eb
    Image:         docker.io/calico/cni:v3.17.1
    Image ID:      docker-pullable://calico/cni@sha256:3dc2506632843491864ce73a6e73d5bba7d0dc25ec0df00c1baa91d17549b068
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/install
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 11 Apr 2021 13:48:27 +0800
      Finished:     Sun, 11 Apr 2021 13:48:40 +0800
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      SLEEP:                 false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-wm8g8 (ro)
  flexvol-driver:
    Container ID:   docker://866c369d3a10f8c011df7dab58e24977d94004755e076a368eee9060ffc5419a
    Image:          docker.io/calico/pod2daemon-flexvol:v3.17.1
    Image ID:       docker-pullable://calico/pod2daemon-flexvol@sha256:48f277d41c35dae051d7dd6f0ec8f64ac7ee6650e27102a41b0203a0c2ce6c6b
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 11 Apr 2021 13:48:42 +0800
      Finished:     Sun, 11 Apr 2021 13:48:42 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host/driver from flexvol-driver-host (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-wm8g8 (ro)
Containers:
  calico-node:
    Container ID:   docker://88cef037e98199a9578579007ded37f0ebd929b71a3abe123872b5bf9e333e0c
    Image:          docker.io/calico/node:v3.17.1
    Image ID:       docker-pullable://calico/node@sha256:25e0b0495c0df3a7a06b6f9e92203c53e5b56c143ac1c885885ee84bf86285ff
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Sun, 11 Apr 2021 14:40:03 +0800
      Finished:     Sun, 11 Apr 2021 14:41:13 +0800
    Ready:          False
    Restart Count:  36
    Requests:
      cpu:      250m
    Liveness:   exec [/bin/calico-node -felix-live -bird-live] delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -felix-ready -bird-ready] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      DATASTORE_TYPE:                     kubernetes
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP_AUTODETECTION_METHOD:            interface=eth0
      IP:                                 autodetect
      CALICO_IPV4POOL_IPIP:               Always
      CALICO_IPV4POOL_VXLAN:              Never
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_VXLANMTU:                     <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_WIREGUARDMTU:                 <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_IPV4POOL_CIDR:               10.244.0.0/16
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_LOGSEVERITYSCREEN:            info
      FELIX_HEALTHENABLED:                true
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /sys/fs/ from sysfs (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/log/calico/cni from cni-log-dir (ro)
      /var/run/calico from var-run-calico (rw)
      /var/run/nodeagent from policysync (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-wm8g8 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:  
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:  
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  sysfs:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/
    HostPathType:  DirectoryOrCreate
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  cni-log-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/calico/cni
    HostPathType:  
  host-local-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/cni/networks
    HostPathType:  
  policysync:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/nodeagent
    HostPathType:  DirectoryOrCreate
  flexvol-driver-host:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    HostPathType:  DirectoryOrCreate
  calico-node-token-wm8g8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-wm8g8
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     :NoScheduleop=Exists
                 :NoExecuteop=Exists
                 CriticalAddonsOnly op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason          Age                   From     Message
  ----     ------          ----                  ----     -------
  Warning  BackOff         67m (x131 over 105m)  kubelet  Back-off restarting failed container
  Warning  Unhealthy       62m (x46 over 112m)   kubelet  Liveness probe failed: calico/node is not ready: Felix is not live: Get "http://localhost:9099/liveness": dial tcp [::1]:9099: connect: connection refused
  Normal   SandboxChanged  58m                   kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          58m                   kubelet  Container image "docker.io/calico/cni:v3.17.1" already present on machine
  Normal   Created         58m                   kubelet  Created container upgrade-ipam
  Normal   Started         58m                   kubelet  Started container upgrade-ipam
  Normal   Pulled          58m                   kubelet  Container image "docker.io/calico/cni:v3.17.1" already present on machine
  Normal   Created         58m                   kubelet  Created container install-cni
  Normal   Started         57m                   kubelet  Started container install-cni
  Normal   Pulled          57m                   kubelet  Container image "docker.io/calico/pod2daemon-flexvol:v3.17.1" already present on machine
  Normal   Created         57m                   kubelet  Created container flexvol-driver
  Normal   Started         57m                   kubelet  Started container flexvol-driver
  Normal   Pulled          57m                   kubelet  Container image "docker.io/calico/node:v3.17.1" already present on machine
  Normal   Created         57m                   kubelet  Created container calico-node
  Normal   Started         57m                   kubelet  Started container calico-node
  Normal   SandboxChanged  56m                   kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Created         56m                   kubelet  Created container upgrade-ipam
  Normal   Pulled          56m                   kubelet  Container image "docker.io/calico/cni:v3.17.1" already present on machine
  Normal   Started         56m                   kubelet  Started container upgrade-ipam
  Normal   Pulled          55m                   kubelet  Container image "docker.io/calico/cni:v3.17.1" already present on machine
  Normal   Created         55m                   kubelet  Created container install-cni
  Normal   Started         55m                   kubelet  Started container install-cni
  Normal   Pulled          55m                   kubelet  Container image "docker.io/calico/pod2daemon-flexvol:v3.17.1" already present on machine
  Normal   Created         55m                   kubelet  Created container flexvol-driver
  Normal   Started         55m                   kubelet  Started container flexvol-driver
  Normal   Pulled          55m                   kubelet  Container image "docker.io/calico/node:v3.17.1" already present on machine
  Normal   Created         55m                   kubelet  Created container calico-node
  Normal   Started         55m                   kubelet  Started container calico-node
  Warning  Unhealthy       54m                   kubelet  Liveness probe failed: calico/node is not ready: bird/confd is not live: exit status 1
  Warning  Unhealthy       54m (x4 over 55m)     kubelet  Liveness probe failed: calico/node is not ready: Felix is not live: Get "http://localhost:9099/liveness": dial tcp [::1]:9099: connect: connection refused
  Warning  Unhealthy       11m (x104 over 55m)   kubelet  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
  Warning  BackOff         69s (x166 over 50m)   kubelet  Back-off restarting failed container
[root@master1 ~]#

**Comment by ShawnBian** [comment]
I have been stuck in this issue for days ,is there anyone who know the reason ? thanks

**Comment by mgleung** [comment]
Hi @ShawnBian , unfortunately this issue could be caused a number of things so I don't have an easy answer based on what I can tell from the logs you've posted. The problem does seem to be just a connectivity issue on a single node though which I think we can verify.

What does your cluster look like? What's the OS/version of your nodes? I have seen issues like this where our autodetection logic ends up finding the wrong network interface on a node to use. Can you verify that your IP address of the failing node matches the main network interface on your node? If it does not, you can change which interface is picked up by setting `IP_AUTODETECTION_METHOD` (https://docs.projectcalico.org/archive/v3.18/reference/node/configuration#configuring-bgp-networking). This could also be caused by a firewall or something else preventing communication to the node in your cluster. Do you have anything like that in your cluster?
