### ISSUE TITLE
Support empty CNI_IFNAME when/if it gets added to the CNI spec

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#107]
This will be merged to upstream CNI soon: https://github.com/containernetworking/cni/pull/145

**Comment by dcbw** [comment]
After #145 gets merged we'd need to relax pkg/skel's CNI_IFNAME check and add some testcases.  I think that's it...

**Comment by caseydavenport** [comment]
@dcbw yep, when we switch this to Go this issue might just fall out, not sure.  Unfortunately at the moment this plugin is written in python and doesn't use pkg/skel so from the looks of it we'd need add support for empty CNI_IFNAME, a conflicting CNI_IFNAME, passing back interface information to the runtime, etc.

**Comment by caseydavenport** [comment]
Plugin is now written in Go, so we shouldn't have any work to do on this end.
