### ISSUE TITLE
Unable to PING external service with 192.168.X.X IP from pod running on calico CNI

### ISSUE THREAD

**Issue by chandrakanthkannam** [projectcalico/cni-plugin#1081]
Unable to PING external service with 192.168.X.X IP from pod running on calico CNI

## Expected Behavior
Ping should work, host which runs the pod can ping the external services

## Current Behavior
Pod unable to ping external services with 192.168.X.X IPs

pod response:
```
/ # hostname -i
10.0.116.193 <--pod IP-->

/ # ping 192.168.134.203
PING 192.168.134.203 (192.168.134.203): 56 data bytes
^C
--- 192.168.134.203 ping statistics ---
9 packets transmitted, 0 packets received, 100% packet loss
/ # 
```
## Context
I have a k8s service with type ExternalName which resolves to 192.168.X.X, and pod can not connect to it, I have tried ping from the node which pod is running from and node can ping it

## Your Environment
* CNI plugin version: docker.io/calico/node:**v3.19.0**
* Orchestrator version: AWS **EKS** v1.19.6

**Comment by chandrakanthkannam** [comment]
Hi @lwr20, i have a different CIDR within the cluster, if you see the pod IP its: `10.0.116.193`

**Comment by lwr20** [comment]
Nice.  What are your service-cidr and host-cidrs?

**Comment by chandrakanthkannam** [comment]
@lwr20 service-cidr : 172.20.0.0/16 and host-cidr: 10.223.140.0/22

**Comment by chandrakanthkannam** [comment]
any update?, If we change the ippool after cni is installed, do we need to restart any pods? like calico-node or anything. Does the change in ippool change iptables on the worker node too?

**Comment by lwr20** [comment]
> If we change the ippool after cni is installed, do we need to restart any pods? 
You'll need to restart any pods in that pool.  

> like calico-node or anything
No - just changing the ippool using `calicoctl` should be enough.  Note that updating ippools really has to be done with calicoctl and not kubectl.

> Does the change in ippool change iptables on the worker node too?
Sort of.  iptables rules are added to a node when there is a pod on that node that uses the rule.  i.e. Calico doesn't program rules onto nodes that aren't needed.

**Comment by lwr20** [comment]
You say that pods cannot talk to things outside the cluster.  After you've restarted pods, can we do a little characterisation please?  Can you do the following and report back please:
- pod to pod on the same node works
- pod to pod on different nodes works 
- pod to service works (using service IP and DNS name separately)
- pod to IP outside the cluster works
- pod to DNS name outside the cluster works

**Comment by chandrakanthkannam** [comment]
@lwr20  I was able to contact the external service with 192.168.X.X IP, after re-deploying from scratch with a different CIDR as the default IP-pool
