### ISSUE TITLE
Windows Quickstart installation does not create nodename file -- cni-plugin errors under Windows 2019 Container Server

### ISSUE THREAD

**Issue by turtledust** [projectcalico/cni-plugin#1149]
Hi, 

I have installed Calico for Windows on an AWS EC2 instance as per the Quick-Start guide

https://docs.projectcalico.org/getting-started/windows-calico/quickstart

which connects to a kubernetes master that uses version 1.20.1 and runs on ubuntu [ami-042e8287309f5df03 -- ami-042e8287309f5df03]

The windows server is based on ami-02cc00a60f7d8adb7 -- Windows_Server-2019-English-Full-ContainersLatest-2021.08.11

I have used the following command to deploy a container to the server:

	kubectl run wincnt5 --image=mcr.microsoft.com/windows/nanoserver:1809

However the status from the container does not progress from ContainerCreating.

Using the following command an error is shown:

	kubectl describe pod wincnt5

-----------------------------------------------------------------------------
	Failed to create pod sandbox: rpc error: code = Unknown desc = 
	[failed to set up sandbox container "6eeaa21bb59eda1efa38f6b580f7acb9f3669fb9cfc7ebfa8fac52d98587acf1" network for pod "wincnt5": 
	networkPlugin cni failed to set up pod "wincnt5_default" network: 
	CreateFile C:\CalicoWindows\libs\calico\..\..\nodename: 
	The system cannot find the file specified.: 
	check that the calico/node container is running and has mounted /var/lib/calico/, failed to clean up sandbox container "6eeaa21bb59eda1efa38f6b580f7acb9f3669fb9cfc7ebfa8fac52d98587acf1" network for pod "wincnt5": networkPlugin cni failed to teardown pod "wincnt5_default" network: CreateFile C:\CalicoWindows\libs\calico\..\..\nodename: The system cannot find the file specified.: 
	check that the calico/node container is running and has mounted /var/lib/calico/]	
-----------------------------------------------------------------------------	
	
It seems that the nodename file is missing: 

    C:\CalicoWindows\libs\calico\..\..\nodename

I have called the installation script using the following parameters
	
     .\install-calico-windows.ps1 -KubeVersion 1.20.1 `
                                  -Datastore etcdv3 `
                                  -EtcdEndpoints https://10.10.1.5:2379 `
                                  -EtcdKey c:\k\apiserver-etcd-client.key `
                                  -EtcdCert c:\k\apiserver-etcd-client.crt `
                                  -EtcdCaCert c:\k\ca.crt
	
This completes without any issue but does not create the nodename file.

I have also manually stepped through the script in debug mode using Powershell ISE and cannot see any code for creating the file.

The cni configuration file that is generated using the installation script is below:

It has a key called nodename_file that is set to C:\\CalicoWindows\\libs\\calico\\..\\..\\nodename

If I manually create the file and set its contents to the dns address of the windows server 

"ip-10-1-4-60.ec2.internal"

the cni-plugin error disappears

--------------------------------------------------
File: c:\k\cni\config\10-calico.conf
--------------------------------------------------
      "type": "calico",
      "mode": "",
    
      "vxlan_mac_prefix":  "0E-2A",
      "vxlan_vni": 4096,
    
      "policy": {
        "type": "k8s"
      },
    
      "log_level": "info",
    
      "capabilities": {"dns": true},
    
      "DNS":  {
        "Nameservers":  ["10.96.0.10"],
        "Search":  [
          "svc.cluster.local"
        ]
      },
    
      "nodename_file": "C:\\CalicoWindows\\libs\\calico\\..\\..\\nodename",
    
      "datastore_type": "etcdv3",
    
      "etcd_endpoints": "https://10.10.1.5:2379",
      "etcd_key_file": "c:\\k\\apiserver-etcd-client.key",
      "etcd_cert_file": "c:\\k\\apiserver-etcd-client.crt",
      "etcd_ca_cert_file": "c:\\k\\ca.crt",
    
      "kubernetes": {
        "kubeconfig": "C:\\CalicoWindows\\calico-kube-config"
      },
    
      "ipam": {
        "type": "calico-ipam",
        "subnet": "usePodCidr"
      },
    
      "policies":  [
        {
          "Name":  "EndpointPolicy",
          "Value":  {
            "Type":  "OutBoundNAT",
            "ExceptionList":  [
              "10.96.0.0/12"
            ]
          }
        },
        {
          "Name":  "EndpointPolicy",
          "Value":  {
            "Type":  "ROUTE",
            "DestinationPrefix":  "10.96.0.0/12",
            "NeedEncap":  true
          }
        }
      ]
    }
-----------------------------------------------------------
	
We have about 100 customers and are looking to move the software they use over to Kubernetes and the Calico plugin.
Some of our customers use windows, so looking into using windows containers for them.

**Comment by lmm** [comment]
Hi @turtledust, can you try:

```
kubectl run wincnt5 --image=mcr.microsoft.com/windows/nanoserver:1809 --overrides='{"spec": {"nodeSelector": {"kubernetes.io/os": "windows"}}}'
```

The pod is probably being scheduled into a Linux node. For Windows pods you will need to use a nodeSelector (or equivalent) to ensure the pod is always scheduled onto Windows nodes.

**Comment by lmm** [comment]
@turtledust I'm closing this issue for now, please reopen or send a message in Slack if this didn't resolve things for you.
