### ISSUE TITLE
CNI Plugin Error on Windows Server Container 2019 - File /var/lib/calico/mtu does not exist

### ISSUE THREAD

**Issue by turtledust** [projectcalico/cni-plugin#1150]
Hi,

I have installed Calico for Windows on an AWS EC2 instance as per the Quick-Start guide

https://docs.projectcalico.org/getting-started/windows-calico/quickstart

which connects to a kubernetes master that uses version 1.20.1 and runs on ubuntu [ami-042e8287309f5df03 -- ami-042e8287309f5df03]

The windows server is based on ami-02cc00a60f7d8adb7 -- Windows_Server-2019-English-Full-ContainersLatest-2021.08.11

I have created the nodename file that was missing after installation as detailed in https://github.com/projectcalico/cni-plugin/issues/1149

I have used the following command to deploy a container to the server:

	kubectl run wincnt6 --image=mcr.microsoft.com/windows/nanoserver:1809

However the status from the container does not progress from ContainerCreating.

Using the following command an error is shown:

	kubectl describe pod wincnt6
	
------------------------------------------------------------------------------------------------------
	
	Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded

------------------------------------------------------------------------------------------------------

When I search through the C:\k\kubelet.err.log I find the following error:

------------------------------------------------------------------------------------------------------
E0827 13:26:42.760103    1632 cni.go:366] Error adding default_wincnt6/291a214951d2e9712e27da37c0a7bc8e475300195437c1365aafdc62b6c9e55b to network calico/Calico: 
netplugin failed: 
"2021-08-27 13:23:02.810 [INFO][5848] utils.go 108: 
File /var/lib/calico/mtu does not exist\n"
------------------------------------------------------------------------------------------------------

Bit puzzled as to why its trying to access a linux path /var/lib/calico/mtu on a windows server?

Any help would be appreciated.

--------------------------------------------------
File: c:\k\cni\config\10-calico.conf
--------------------------------------------------
  "type": "calico",
  "mode": "",

  "vxlan_mac_prefix":  "0E-2A",
  "vxlan_vni": 4096,

  "policy": {
    "type": "k8s"
  },

  "log_level": "info",

  "capabilities": {"dns": true},

  "DNS":  {
    "Nameservers":  ["10.96.0.10"],
    "Search":  [
      "svc.cluster.local"
    ]
  },

  "nodename_file": "C:\\CalicoWindows\\libs\\calico\\..\\..\\nodename",

  "datastore_type": "etcdv3",

  "etcd_endpoints": "https://10.10.1.5:2379",
  "etcd_key_file": "c:\\k\\apiserver-etcd-client.key",
  "etcd_cert_file": "c:\\k\\apiserver-etcd-client.crt",
  "etcd_ca_cert_file": "c:\\k\\ca.crt",

  "kubernetes": {
    "kubeconfig": "C:\\CalicoWindows\\calico-kube-config"
  },

  "ipam": {
    "type": "calico-ipam",
    "subnet": "usePodCidr"
  },

  "policies":  [
    {
      "Name":  "EndpointPolicy",
      "Value":  {
        "Type":  "OutBoundNAT",
        "ExceptionList":  [
          "10.96.0.0/12"
        ]
      }
    },
    {
      "Name":  "EndpointPolicy",
      "Value":  {
        "Type":  "ROUTE",
        "DestinationPrefix":  "10.96.0.0/12",
        "NeedEncap":  true
      }
    }
  ]
}
-----------------------------------------------------------

**Comment by lmm** [comment]
@turtledust I just replied in your other issue: https://github.com/projectcalico/cni-plugin/issues/1149#issuecomment-910535196 :)

By the way, have you joined the Calico Users slack channel? It's a good place to discuss Calico issues and get help: https://slack.projectcalico.org/

**Comment by lmm** [comment]
@turtledust please reopen or send a message in Slack if this didn't resolve things for you.
