### ISSUE TITLE
Wrong source IP address during PODs communication

### ISSUE THREAD

**Issue by networkingana** [projectcalico/cni-plugin#1208]
I'm trying to run Kafka on Kubernetes using Strimzi. I am stuck with the creation of the Zookeepers cluster. They cannot communicate with each other properly. 

I tried to use calico both with direct and ipip mode, but the result was the same. I already reported this issue on the strimzi project, but I concluded that this is a network issue. I did network traces and the result was the following.

When using IPIP mode: I can see that two zookeepers did have communication in one way, and the other didn't have. In the network trace, I saw that the TCP SYN packets were coming with the source IP address of the tunnel interface of the source node1 and not the pod IP address, which was the case when the communication was successful.

I am not sure if I have the wrong configuration, or there is some bug I hit.

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v3.20.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.22.3
* CNI config: [calico.txt](https://github.com/projectcalico/cni-plugin/files/7470439/calico.txt)
* Operating System and version: CentOS 7

Please let me know if you need more information

Thank you.

**Comment by caseydavenport** [comment]
>  In the network trace, I saw that the TCP SYN packets were coming with the source IP address of the tunnel interface of the source node1 and not the pod IP address,

Which interface were you capturing the trace on? The address of the IPIP packet itself should have the source address of the node on the outer packet, however the inner packet should be the pod IP.
