### ISSUE TITLE
The Calico node has multiple IP addresses in the same network segment, causing the Calico network connection failure.

### ISSUE THREAD

**Issue by gongxiao2** [projectcalico/cni-plugin#1209]
k8s version:
v1.20.6
K8S nodes os:
centos 7.8
keepalived version:
1.3.5-19

k8s cluster has five nodes(3 master and 2 worker),  expose a VIP(32-bit mask) through keepalived.
five node has same manager network ip(24-bit mask), VIP is in manager network cidr.
set calico network autodetection method in every node:
```
kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=cidr="xx.xx.xx.0/24"
```
The VIP is sometimes used as a Calico BGP ip, once the VIP is migrated, the Calico network is disconnected.

**Comment by caseydavenport** [comment]
Sounds like you might need to use a different IP_AUTODETECTION_METHOD to make sure the VIP isn't chosen. 

This sounds a lot like https://github.com/projectcalico/calico/issues/4870
