### ISSUE TITLE
Support logging to file

### ISSUE THREAD

**Issue by tomdee** [projectcalico/cni-plugin#126]
IMHO it should be disabled by default (it's not much use when running in a `rkt fly` based hyperkube for example).

The default level (when enabled) should be simply to provide an audit trail. There should also be a debug level (which will be slower etc...) but can be turned on to track down problems. 

The file location should be configurable but should have a sensible default.

The log file should _probably_ be rotated and only a limited number kept - this should probably be configurable too.

**Comment by caseydavenport** [comment]
Agreed that it should be disabled by default, and that the default level when enabled should be minimal.

Beyond that I think we need configurable levels of logging. Don't care so much what the levels are, but it should be easy to look at a log file and see what the CNI plugin did, and then easy to up the verbosity until you can see a _really detailed_ view of what the plugin did.

**Comment by tomdee** [comment]
See #70

**Comment by ozdanborne** [comment]
Closing as wontfix, as there doesn't seem to be a need for this.
