### ISSUE TITLE
Calico IPAM should support specifying a pool

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#152]
Calico pools aren't much use if users can't pick which one they want a container to belong to.

We've heard a number of use-cases from people who want to be able to specify these - the main one being assigning from a public pool / private pool.

Not clear yet how best to expose this - either as a per-container argument, per-CNI-network argument, or maybe both?

**Comment by tomdee** [comment]
...or as a kubernetes label?

**Comment by caseydavenport** [comment]
@tomdee Perhaps it could be exposed as a k8s pod annotation (labels aren't right for this) in the Kubernetes case.

**Comment by djosborne** [comment]
We definitely want something like this for Mesos as well.

Mesos itself doesn't support it, but it could be user input in the labels that get injected into the args section  of the cni conf.

**Comment by gunjan5** [comment]
Related (kinda) PR https://github.com/projectcalico/libcalico-go/pull/245
(for issue [#244](https://github.com/projectcalico/libcalico-go/issues/244) )

**Comment by caseydavenport** [comment]
I think first step for this could be to support the following CNI config:

```
{
  type: calico
  ipam: {
    type: calico-ipam,
    ipv4_pool: <ip-pool-here>,
    ipv6_pool: <ip6-pool-here>,
  }
}
```

Any containers assigned IPs from this CNI network would get IP addresses from the specified ip pool.  If no pools were specified, then we'd follow the current behavior of using all pools.  If the specified pool doesn't exist, then return an error.

We can then decide down the road if we want to allow for per-container overrides to this (e.g through an annotation).

@tomdee @lxpollitt WDYT?

CC @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
I suppose that for generality's sake, it should be a set of pools rather than a single pool.  In my case I will be getting IP blocks from a cloud provider and getting, e.g., 2 blocks of size N from them is easier than getting one block of size 2N.

**Comment by tomdee** [comment]
General approach and using a list sounds fine to me.

**Comment by fasaxc** [comment]
Just to make sure we tie down the spec; I think if there are no IPs left in the pool, it should error.  Only mentioning it because the IPAM code currently uses affinity as a preference not a hard requirement (it'll fall back to allocating from a non-ideal block if the desired block is full).

**Comment by djosborne** [comment]
Since most orchestrators pass the IPAM section of the config on file directly to the CNI plugin without modification, doesn't that make those pool settings per-network settings?

**Comment by caseydavenport** [comment]
> I think if there are no IPs left in the pool, it should error. Only mentioning it because the IPAM code currently uses affinity as a preference not a hard requirement 

Agreed.  IPAM uses affinity as a preference, but if you specify a pool then that is considered a hard requirement, so this behavior _should_ be the way it works today.

**Comment by caseydavenport** [comment]
@djosborne yep.  These would essentially be "I want this CNI network to assign addresses from one of these pools"

**Comment by djosborne** [comment]
I think a lot of (mesos) users want to have the ability to pick pools on a per-app basis. If, for example, the ToR Calico is peered with is broadcasting one calico pool to its nexthop (public), but not another pool (private), app deployers want to be able to pick which pool their application is launched in. 

Sure, load balancers are one way around this problem, but I don't know that it should be the only way.

**Comment by caseydavenport** [comment]
@djosborne If we added support to the "args" section, who would populate that?  It would essentially be a per CNI network option until some orchestrator supported populating that field for us.

Agreed that per-container settings are useful.  For kubernetes I think we'd do an annotation on the Pod.

e.g `projectcalico.org/ipPools: [..., ...]`

Is there a similar concept in Mesos?

**Comment by djosborne** [comment]
Mesos allows application deployers to populate the args section with arbitrary metadata. Right now, we process everything there as endpoint labels in our data model.

Mesos does support the equivalent of Pod Annotations via App Labels which can be queried in the Mesos API (something we don't support yet, but could). I suppose it might make more sense to implement per-app pool selection there instead of going down the path of introducing special pool labels in `args` that are preprocessed before the remaining general endpoint labels located there.

**Comment by lxpollitt** [comment]
The Calico CNI plugin already has different code paths for getting per workload metadata from Mesos vs from Kubernetes.  Once the metadata is obtained then the rest of the pool processing logic would be common across both all orchestrators. 

I propose we separate this into a number of issues:
1) Support for the CNI config snippet as proposed by @caseydavenport.  If the ippools config snippet is omitted then behavior defaults to what it is today.  This feature would be common to all orchestrators that use CNI.
2) Support for Kubernetes pod annotation that specifies a list of pools.  If specified this overrides any CNI pool config delivered by feature (1).  This is Kubernetes specific, and a relatively small delta to (1).
3) Support for Mesos args labels to achieve the same as (2) for Mesos.

**Comment by caseydavenport** [comment]
Closing in favor of https://github.com/projectcalico/cni-plugin/issues/212
