### ISSUE TITLE
Support specifying ipPools as k8s annotation

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/cni-plugin#213]
As per the discussion in #152 , second step to accomplish what's listed there is to support ipPools specified as k8s pod annotation, for example: 
```yaml
spec:
  template:
    metadata:
       annotations:
            cni.calico/ipv4pools: [<ip-pool-1>, <ip-pool-2>]
            cni.calico/ipv6pools: [<ip-pool-1>, <ip-pool-2>]
```

To accomplish that, we'd have to make changes in the [CNI](https://github.com/projectcalico/calico-cni) repo:
- Make a helper func similsr to this one that gets k8s labels: https://github.com/projectcalico/calico-cni/blob/master/k8s/k8s.go#L235
- Have to modify where the args get populated https://github.com/projectcalico/calico-cni/blob/master/k8s/k8s.go#L43
- Make sure to pass the ipPools to when CmdAdd is called.
- Might need to do manual testing since adding tests for this would take time.

**Comment by lxpollitt** [comment]
cc @caseydavenport @MikeSpreitzer

**Comment by duglin** [comment]
See: https://github.com/projectcalico/calico-cni/issues/212 for related PRs.
This issue is next...

**Comment by duglin** [comment]
@lxpollitt thanks for all of the great pointers you gave me for the PRs related to this.

On this one I want to make sure I have the flow correct.  Am I correct that the call to `ipam.ExecAdd` at https://github.com/projectcalico/calico-cni/blob/master/k8s/k8s.go#L108 , as of now, will have the `NetConf` struct in the `args.StdinData` parameter w/o the new pools stuff ?
If so, where did that data come from?  From the name I suspect its coming from K8s calling the CNI plugin and its being flowed over stdin, but what in K8s knew about `NetConf` as that seems very Calico specific?  Or is NetConf a superset of the CNI config data and its just the CNI data as known to K8s and I just need to populate it the new IPAM.*pools fields in there from the K8s pod annotations?

**Comment by caseydavenport** [comment]
> as of now, will have the NetConf struct in the args.StdinData parameter w/o the new pools stuff

Yep, that's the json serialized version of the NetConf struct.

> From the name I suspect its coming from K8s calling the CNI plugin and its being flowed over stdin, but what in K8s knew about NetConf as that seems very Calico specific?

Yes, this is coming from the kubelet, but it's read from a file provided by the operator of the cluster so they have control over what that looks like.  It should have the new pools arguments included (but it won't have knowledge of the annotations).

> Or is NetConf a superset of the CNI config data and its just the CNI data as known to K8s and I just need to populate it the new IPAM.*pools fields in there from the K8s pod annotati

It's an interesting question.  There are at least a few ways this could pan out:
- The CNI plugin could detect the annotations (it already does) and populate the NetConf struct then Marshal it to json and pass to the IPAM plugin.  It would need to do this _only_ when using calico-ipam though.
- The IPAM plugin could become k8s aware (it isn't really today) and query the annotations itself.

I don't really like the second option since it adds another API lookup to CNI execution, so we probably need to go with the first (or something else)

**Comment by lxpollitt** [comment]
I think we should consider tweaking this PR a little to allow users to pass in either a /32 or a list of CIDRs.  Probably means renaming `ipv4pools` to something more generic like `ipv4constraints` (and ditto the ipv6 ones).

- If a /32 is passed in then that's the specific IP address to use.  If the IP address is within a Calico ipPool then Calico attempts to assign it from its IPAM data model to avoid IPAM clashes, and fails if the IP address is already assigned to another endpoint.  If the IP address is not within a Calico ipPool then it is the responsibility of the user to ensure no IPAM clashes.
- If CIDR(s) are passed in then they need to correspond to a Calico ipPool.

What do people think?

**Comment by MikeSpreitzer** [comment]
@lxpollitt: that sounds good to me.

**Comment by caseydavenport** [comment]
@lxpollitt I'm not sure I understand the desire to squeeze both of those into a single annotation.  Might be better to have a separate `calico.ipam.ipv4addr` annotation which can be specified?

> If the IP address is not within a Calico ipPool then it is the responsibility of the user to ensure no IPAM clashes

If using Calico IPAM, this will fail anyway - we assert that it's within a configured ip pool.  If not using Calico IPAM, then I'm not sure we can guarantee that this argument will be honored?   On that note, we may want to tweak the annotation to be `cni.ipam.calico/ipv4pools:` or similar.

Anyway, I'm also happy to switch to constraints and keep it as one annotation if we think that's best.  Just chucking around thoughts.

**Comment by lxpollitt** [comment]
I think a single constraints annotation is more future proof.  Right now I'm suggesting two types of constraints we will support, but there may be other CIDR based constraints that make sense in the future.

For the /32 addresses I am proposing that if the address is outside of a Calico range then we do not call Calico (or other CNI) IPAM.  The caller is responsible for IPAM in that case.  I've recently spoken to a large user who has this requirement.

We could potentially simplify for now and say if specifying a /32 then is MUST not be within a Calico IPAM pool.  That simplifies IPAM interactions and eliminates potential differences in behavior depending on strict affinity settings for example, or cyclic pod scheduling attempts that repeatedly fail if Calico thinks the IP address is already in use.

**Comment by caseydavenport** [comment]
> I think a single constraints annotation is more future proof. 

I think my main concern is that by inferring the behavior based on what sort of stuff we're putting in that list makes for a complicated interface for users _especially_ if we start adding more types of constraints to it.

I think if we take that approach I'd prefer a more expressive annotation than just a list.

e.g something like this (give or take) would be future proof and be clear to the user what the behavior is / easier to document:

```
cni.ipam.projectcalico.org/ipv4constraints: |
  {
    ipPools: [ . . .],
    explicitAddrs: [. . .],
    ...
  }
```

> For the /32 addresses I am proposing that if the address is outside of a Calico range then we do not call Calico (or other CNI) IPAM

This could be triggered by the presence of `explicitAddrs` - if this is given then it means some other party is doing IPAM and the CNI plugin in turn should not be.

**Comment by lxpollitt** [comment]
I think the downsides of a more expressive annotation is that you have to mess around with encoding it into a single field, right?  And I don't see a huge benefit in this kind of nesting.  If we really think that we need two separate fields then let's just have two separate fields.  (I personally don't think we need separate fields, but that's less of a big deal I think)

**Comment by valentin2105** [comment]
It would be awesome to can specify a /32 at pod creation to assign a /32 IP (Public for example) to the pod from Calico's IPPool.

**Comment by caseydavenport** [comment]
After chatting with @gunjan5 + @lxpollitt, I'd like to propose the following:

For #223, a pair of json encoded annotations (v4, v6) to specify a list of pools from which to assign an IP address:

```yaml
annotations:
  cni.projectcalico.org/ipv4pools: "['10.0.0.0/24', '172.18.1.0/24']"
```

In a follow on PR, a pair of json encoded annotations to specify a list of exact IP addresses to assign:

```yaml
annotations:
  cni.projectcalico.org/ipv4addrs: "['10.0.0.1']"
```

If the `cni.projectcalico.org/ipvXaddrs` annotation is specified then those addresses are assigned to the pod no matter what pool config may have been provided in the ipvXpools annotations or CNI config, and no matter what IP pools are actually configured in Calico.

**Comment by lxpollitt** [comment]
We should clarify the interaction between Calico IPAM and the ipvXaddrs if the address passed in on the annotation falls within a Calico pool.  Does it try to mark that address as assigned to the host in the Calico IPAM data model?  Or does it do nothing with Calico IPAM (therefore likely resulting in clashes at some point in the future - perhaps deliberately if someone is trying to do some sort of unusual ECMP thing, but perhaps just accidentally)?  Or should we reject it?

**Comment by tomdee** [comment]
@caseydavenport the general shape of the proposal sounds good to me.

I think @lxpollitt 's questions need to be answered too though. In libnetwork, the model we've followed is that the IP _must_ fall with a Calico IPPool and the address get's assigned in our IPAM. I think that should be supported here too. It feels a bit "flexible" to also allow IPs from outside a Calico IPPool, but if we have a concrete requirement for it then the code is straightforward, but maybe it should be a different annotation. It's a pretty different thing to an IP from within a Calico IPPool.

**Comment by lxpollitt** [comment]
I'm not sure which is best.  I can see arguments in both directions.  e.g. People who want to use this (or a very similar) feature to assign ECMP style service VIPs to pods.  If we mandate it has to be in a Calico pool then that stops people from doing that.  Maybe there are cases where Calico is not responsible for the IPAM at all given that this is k8s/CNI.

**Comment by tomdee** [comment]
It's also worth noting that the CNI plugin already presents a way for users to choose an IP address. 
http://docs.projectcalico.org/v2.0/reference/cni-plugin/configuration
> IPAM
> A specific IP address can be chosen by using CNI_ARGS and setting IP to the desired value.

**Comment by caseydavenport** [comment]
I am also torn between the two options.

My original thought was that we should bypass Calico's IPPool / assignment code altogether and just treat the annotation as the source of truth for IPAM.

Note that IPs which don't fall within Calico IP Pools will not have outgoing NAT applied to them, and routes won't get distributed by BIRD due to filtering, so in many cases users will still want to ensure that an IP Pool exists for the IPs they're assigning.  They can disable IPAM on that IP Pool so that addresses won't be automatically assigned to other Pods.

**Comment by gunjan5** [comment]
I think it could be an issue if NAT doesn't get applied automatically when an IP is assigned to a pod. 
I'm kind of leaning more towards consulting with Calico IPAM first to make sure the IP is available (from an ipPool), and then assign it. 

WDPT? @caseydavenport @lxpollitt @tomdee 
It would be nice to finalize what approach we want so we can get this in v2.1 hopefully.

**Comment by caseydavenport** [comment]
After discussing with @tomdee, we're thinking about two annotations now to represent the two different use cases above.

```
cni.projectcalico.org/ipAddrs: "['10.0.0.1']"
```

This annotation will be passed to the configured IPAM plugin using the `IP=...` environment variable as described in the CNI conventions.  The CNI plugin will be expected to assign the provided address or return an error.

```
cni.projectcalico.org/ipamOverrides: "['10.0.0.1']"
```

If specified, this annotation ignores all other IPAM settings and will be stored in the Calico WorkloadEndpoint without calling any IPAM plugin.

For now these annotations will only support a single IP in each list, but will be formatted as lists for future-proofing since we know that CNI will support multiple IP addresses in the future.  When the time comes then multiple IPs will be supported.

**Comment by gunjan5** [comment]
I've created a new issue to track this since it's separate from the original issue on this page. 
https://github.com/projectcalico/cni-plugin/issues/258

**Comment by gunjan5** [comment]
x-posting: Tested 5 different scenarios with the code in #260 with an actual k8s deployment and it seems to work. Details below:
--------------
1. Pods with annotation for the same ipPool as the default ipPool:
```yaml
 annotations:
        "cni.projectcalico.org/ipv4pools": "[\"192.168.0.0/16\"]"
```
```
default       my-nginx-1912065077-kct9v                   1/1       Running             0          24m       192.168.190.2   node-01
default       my-nginx-1912065077-zsqk9                   1/1       Running             0          24m       192.168.190.3   node-01
```

2. Pods with annotation for an ipPool that doesn't exist:
```yaml
annotations:
        "cni.projectcalico.org/ipv4pools": "[\"20.0.0.0/24\"]"
```
```
Error syncing pod, skipping: failed to "SetupNetwork" for "lalala-nginx-2470432397-7h05h_default" with SetupNetworkError: "Failed to setup network for pod \"lalala-nginx-2470432397-7h05h_default(fd4d2c4f-ea61-11e6-a871-080027ee3298)\" using network plugins \"cni\": The given pool (20.0.0.0/24) does not exist; Skipping pod"
```

3.  Pods with annotation for a non-default ipPool:
```yaml
ETCD_ENDPOINTS=http://10.96.232.136:6666 cat << EOF | calicoctl create -f -
apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 10.0.0.0/24
EOF
```
```yaml
annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.0.0.0/24\"]"
```
```
default       meep-nginx-60935436-d157z                   1/1       Running             0          11m       10.0.0.0        node-01
default       meep-nginx-60935436-wjdfz                   1/1       Running             0          11m       10.0.0.1        node-01
```

4. Pods with annotation for an existing **IPv6** ipPool:
```yaml
cat << EOF | calicoctl create -f -
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 2001:db8::1/120
EOF
```
```yaml
annotations:
    "cni.projectcalico.org/ipv6pools": "[\"2001:db8::1/120\"]"
```
Update calico CNI config to set `assign_ipv6` to `true`:
```json
 "assign_ipv4": "false",
 "assign_ipv6": "true"
```
```

default       my-nginx6-4089695562-8705n                  1/1       Running             0          6m        2001:db8::3    node-01
default       my-nginx6-4089695562-9jtsh                  1/1       Running             0          8m        2001:db8::1    node-01
default       my-nginx6-4089695562-v8ncd                  1/1       Running             0          6m        2001:db8::2    node-01
default       my-nginx6-4089695562-zbxnb                  1/1       Running             0          8m        2001:db8::     node-01
```

5. Pods with a annotation for a **subnet** which is a subset of an existing ipPool:
```yaml
annotations:
        "cni.projectcalico.org/ipv4pools": "[\"10.0.0.0/25\"]" 
```
```
calicoctl get ippool -o wide
CIDR             NAT     IPIP
10.0.0.0/24      false   false
192.168.0.0/16   true    true
2001:db8::/120   false   false
```
```
Feb 06 22:33:39 node-01 kubelet[12312]: time="2017-02-06T22:33:39Z" level=error msg="Error claiming new block: The given pool (10.0.0.0/25) does not exist"
Feb 06 22:33:39 node-01 kubelet[12312]: time="2017-02-06T22:33:39Z" level=error msg="Error assigning IPV4 addresses: The given pool (10.0.0.0/25) does not exist"
```
--------------

**Comment by valentin2105** [comment]
@gunjan5 Does it work with a /32 IPPool ? It seem awesome.

**Comment by gunjan5** [comment]
@valentin2105 We will have 2 new annotations for specifying a single IP. See: https://github.com/projectcalico/cni-plugin/issues/258
One bypasses IPAM and another one uses IPAM to assign that specific IP.
First one is ready to merge https://github.com/projectcalico/cni-plugin/pull/264 and we should have the other one ready either tomorrow or the day after.

**Comment by anannaya** [comment]
@caseydavenport : If i am using single repica Deployment kind, and the worker nodes crashed didn't come up for some time. Deployment tries to bring up the pod in another worker node. Since we are using the static ip pod won't come up.  Is there any webhook planned to cleanup the ip from etcd(ipam) in case the worker node crashes.?

**Comment by caseydavenport** [comment]
@anannaya nothing in the immediate roadmap. Could you raise a separate enhancement issue to track this?
