### ISSUE TITLE
support etcdUsername and etcdPassword

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/cni-plugin#216]
`calicoctl` supports etcdUsername and etcdPassword for configured role-based authentication.

Calico-CNI should process these variables from the CNI config file and use them to log in as the configured etcd role.

**Comment by tmjd** [comment]
With the work being done under this issue https://github.com/projectcalico/calico/issues/563. If the CNI plugin can read the config file that has those values then do we still want to add these variables to the CNI config?

**Comment by caseydavenport** [comment]
@tmjd with 563, this certainly becomes less important.  I think 563 would close this issue.

**Comment by caseydavenport** [comment]
This can be done with certs, so going to close this as wontfix.
