### ISSUE TITLE
[k8s] Better support for running w/o policy controller

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#224]
Ideally we'd have a mode where you can run without the policy controller, everything gets added to a single Profile with allow rules, and then users can use `calicoctl` to configure policy based on labels.

We still want the label integration with k8s, but we would want to change the behavior where:

```
policy: {type: k8s}
```

triggers using `k8s_ns.<name>` profiles.

**Comment by ozdanborne** [comment]
Closing as wontfix, as there doesn't seem to be a need for this.
