### ISSUE TITLE
Logs missing context in kubelet output

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/cni-plugin#236]
I think this log came from us:
```
Dec 08 17:34:49 tigera-scale-fd-003.c.unique-caldron-775.internal kubelet[1493]: time="2016-12-08T17:34:49Z" level=info msg="Fetched K8s labels" Workload=default.getter-py7hy labels=map[role:getter calico/k8s_ns:default]
```
But the message and level are buried in the middle and it's hard to grep for Calico logs.  Can we get something grep-able in there and some context to identify the function/file/line number?

(There's code in Felix that sets all that up; we could move that to libcalico-go and share it.)

**Comment by tomdee** [comment]
Sounds like a good idea. Are you talking about this code @fasaxc https://github.com/projectcalico/felix/blob/1ac3d64e7d2901887a515a5d06651d1e9c687045/go/felix/logutils/logutils.go#L176?

**Comment by djosborne** [comment]
+1 to this. Since we're using Logrus in calico-cni, can we just add `"component": "calico-cni"` to this line? https://github.com/projectcalico/cni-plugin/blob/57e3c6afd19f2880c3633e6d63120b8a6df94278/utils/utils.go#L230

**Comment by caseydavenport** [comment]
@djosborne I'd rather not use the context logging mechanism for this. 

I do think we should have consistent log formatting across our components and that the format should make it clear that the log came from Calico.

We used to have logs at the start / end of a Calico CNI execution like "Beginning Calico CNI execution" and "Calico CNI execution finished with RC=%d", which were useful.
