### ISSUE TITLE
use calico as the cni network in k8s, when connect some pods return     connect: Invalid argument 

### ISSUE THREAD

**Issue by du2016** [projectcalico/cni-plugin#241]
ping 192.168.7.151
connect: Invalid argument

some other pods works good ,they are in the same namespace and i don't have networkpolicy

**Comment by du2016** [comment]
when i use  ip route s,it only show some of pods ip router,other is not

**Comment by caseydavenport** [comment]
@du2016 could you share which version of Calico you're using?

Could you also share the output of `ip route` within a working pod, within a non-working pod, and from the host that is running the pods?

**Comment by du2016** [comment]
cat calico.yaml | grep image
image: quay.io/calico/node:v0.23.0
image: calico/cni:v1.4.3
image: calico/kube-policy-controller:v0.4.0
image: calico/ctl:v0.23.0

**Comment by du2016** [comment]
[root@Master ~]# docker exec 8bf1b0dadd37 ip addr s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if15: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 32:da:22:a7:be:95 brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.128/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::30da:22ff:fea7:be95/64 scope link 
       valid_lft forever preferred_lft forever
[root@Master ~]# docker exec 8bf1b0dadd37 ip route s
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 

in the bad pod:
[root@Master ~]# docker exec a88213b9ec5e ip route s            
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0  scope link 
[root@Master ~]# docker exec a88213b9ec5e ip addr s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if18: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 9a:c1:d1:48:4b:39 brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.131/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::98c1:d1ff:fe48:4b39/64 scope link 
       valid_lft forever preferred_lft forever

on my  host:
[root@Master ~]# ip route s
default via 10.10.11.251 dev ens192  proto static  metric 100 
10.10.8.0/22 dev ens192  proto kernel  scope link  src 10.10.10.150  metric 100 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
blackhole 192.168.100.64/26  proto bird 
192.168.100.128 dev cali4069cd2dfde  scope link 
blackhole 192.168.100.128/26  proto bird 


ping test:
[root@Master ~]# ping 192.168.100.128
PING 192.168.100.128 (192.168.100.128) 56(84) bytes of data.
64 bytes from 192.168.100.128: icmp_seq=1 ttl=64 time=0.073 ms
--- 192.168.100.128 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.073/0.073/0.073/0.000 ms
[root@Master ~]# ping  192.168.100.131
connect: Invalid argument

**Comment by du2016** [comment]
@caseydavenport  
Is it a problem with my host environment?

**Comment by lidajia** [comment]
@du2016 I have the same problem, How did you solve the problem?

**Comment by msavlani** [comment]
@du2016 @lidajia  how did you guys solve this issue ? I am having exact same problem.

**Comment by caseydavenport** [comment]
@msavlani what version of Calico are you using?

**Comment by hellolittlewei** [comment]
[root@server1 ansible]# calicoctl node status
Calico process is running.

IPv4 BGP status
No IPv4 peers found.

IPv6 BGP status
No IPv6 peers found.

[root@server1 ansible]# ping 172.20.116.130
connect: Invalid argument

**Comment by hellolittlewei** [comment]
[root@server1 ansible]# calicoctl version
Client Version:    v3.15.5
Git commit:        20918766
Cluster Version:   v3.15.5
Cluster Type:      k8s,bgp
