### ISSUE TITLE
CentOS container create with IPv6 failing

### ISSUE THREAD

**Issue by pmichali** [projectcalico/cni-plugin#266]
Using bare-metal  (Cisco UCS) and Kubeadm with the calico.yaml file (master), an nginx container with IPv4 was created successfully. Running CentOS Linux release 7.3.1611 (Core).

Then created IPv6 pool and retried with failure to get IPv6 address...

Feb 09 21:59:00 devstack-77 kubelet[27390]: Calico CNI IPAM request count IPv4=0 IPv6=1
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Auto assigning IP" Workload=default.my-nginx2-3281239120-08z5c assignArgs={0 1 0xc4201046c0 map[]  [] []}
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Auto-assign 0 ipv4, 1 ipv6 addrs for host 'devstack-77'"
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="New allocation attribute: {AttrPrimary:0xc4201046c0 AttrSecondary:map[]}"
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Creating new handle: default.my-nginx2-3281239120-08z5c"
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Auto-assigned 1 out of 1 IPv6s: [2001:2::6d47:e62d:8139:d1db]"
Feb 09 21:59:00 devstack-77 kubelet[27390]: Calico CNI IPAM assigned addresses IPv4=[] IPv6=[2001:2::6d47:e62d:8139:d1db]
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="IPAM Result" Workload=default.my-nginx2-3281239120-08z5c result.IP4=<nil> result.IP6=&{{2001:2::6d47:e62d:8139:d1db ffffffffffffffffffffffffffffffff} <nil> []}
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Populated endpoint" Workload=default.my-nginx2-3281239120-08z5c endpoint=&{{workloadEndpoint v1} {{} eth0 default.my-nginx2-3281239120-08z5c k8s devstack-77 map[pod-template-hash:3281239120 run:my-nginx2 calico/k8s_ns:default]} {[2001:2::6d47:e62d:8139:d1db/128] [] <nil> <nil> [k8s_ns.default]  <nil>}}
Feb 09 21:59:00 devstack-77 kubelet[27390]: Calico CNI using IPs: [2001:2::6d47:e62d:8139:d1db/128]
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=error msg="Error getting IPv6 address: Failed to get IPv6 addresses for container veth" Workload=default.my-nginx2-3281239120-08z5c
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=error msg="Error creating veth: Failed to get IPv6 addresses for container veth" Workload=default.my-nginx2-3281239120-08z5c
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=error msg="Error setting up networking: Failed to get IPv6 addresses for container veth" Workload=default.my-nginx2-3281239120-08z5c
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Cleaning up IP allocations for failed ADD" Workload=default.my-nginx2-3281239120-08z5c
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Configured environment: [LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local CNI_COMMAND=DEL CNI_CONTAINERID=7c1a172d7ba3e3696edfdbed0edf3c1867129eec4d905d793c0db8947ebff236 CNI_NETNS=/proc/3789/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=my-nginx2-3281239120-08z5c;K8S_POD_INFRA_CONTAINER_ID=7c1a172d7ba3e3696edfdbed0edf3c1867129eec4d905d793c0db8947ebff236 CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://10.96.232.136:6666 KUBECONFIG=/etc/cni/net.d/calico-kubeconfig K8S_API_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLWJxZjZwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkNTc1YzEzYS1lZjBkLTExZTYtYjlhNi0wMDNhN2Q2OWY3M2MiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.nr4Hv2oJEZzCNC6e29auv3jzOOE2cFD1cMrQ8dkb3oy6o8KMOFKL1L97U4aBTV1N3QbTU7_Y_ZyWhM2615q8kOJ4a6T7J37IPZ4sihp94DqiQfjPMA5L2l395LegY1ql32ul8jjry3cjrc4dQ4dex-K3rYfa4R0KrhDG8KHryg6xfLvNjsCx8BoWAFSwzmAIKXDmVQEskEkd1osb41HjSxc2rlowUozDK2YOTxx3C-VU-8lZv7nYYSKLEuOSxi8Tx4rdSobLYvlWhjmsUXKIdBXCciJPeslo5aIQWXziWjDS6n01ouE6yzVDdVwC32IWPES_qS054Uz7RQCqffUe5g]"
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Loading config from environment"
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Releasing address using workloadID" Workload=default.my-nginx2-3281239120-08z5c
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Releasing all IPs with handle 'default.my-nginx2-3281239120-08z5c'"
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Decremented handle 'default.my-nginx2-3281239120-08z5c' by 1"
Feb 09 21:59:00 devstack-77 kubelet[27390]: time="2017-02-09T21:59:00Z" level=info msg="Released address using workloadID" Workload=default.my-nginx2-3281239120-08z5c
Feb 09 21:59:00 devstack-77 kubelet[27390]: E0209 21:59:00.810330   27390 cni.go:255] Error adding network: Failed to get IPv6 addresses for container veth
Feb 09 21:59:00 devstack-77 kubelet[27390]: E0209 21:59:00.810370   27390 cni.go:209] Error while adding to cni network: Failed to get IPv6 addresses for container veth
Feb 09 21:59:00 devstack-77 kubelet[27390]: E0209 21:59:00.810450   27390 docker_manager.go:2201] Failed to setup network for pod "my-nginx2-3281239120-08z5c_default(e6c4667a-ef12-11e6-b9a6-003a7d69f73c)" using network plugins "cni": Failed to get IPv6 addresses for container veth; Skipping pod

**Comment by gunjan5** [comment]
We should add this into our QA process next week
