### ISSUE TITLE
Could we check for incompatible kube-proxy settings?

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/cni-plugin#268]
kube-proxy has a few settings that can break a calico network and the issues can be hard to diagnose, would it be crazy to at least try to check the kube-proxy's command line flags in stratup.go?  Obviously, we could only do that if we have permissions and if it's already running but it might save a lot of debugging pain.

Known offenders:

- `--masquerade-all` SNATs everything, meaning Calico sees all traffic as from the hosts
- non `iptables` proxy mode.

**Comment by fasaxc** [comment]
Opened a docs issue as a workaround, but it's much  better if we can police this case instead. https://github.com/projectcalico/calico/pull/498

**Comment by caseydavenport** [comment]
> would it be crazy to at least try to check the kube-proxy's command line flags in stratup.go

I don't think there's a reliable way to check for this given all the ways the kube-proxy can be installed (or not at all).  I'm going to close this since the documentation has been merged.
