### ISSUE TITLE
IPAM support webhook or notification

### ISSUE THREAD

**Issue by rikatz** [projectcalico/cni-plugin#277]
This is a feature request / questioning:

Is it possible that IPAM supports some kind of webhook notification or different logging? Explainig, we're going to use Calico in our environment, but need to audit any leaving communication from the container environment to outside world (as Internet via proxying, Oracle databases, and so).

So we need to know what container was using which IP address in a determinate date/time to future audits. I was going to achieve this by notificating some endpoint about the IP change, and log it (with the containers hostname, that contains the namespace + the deployment name) and the assigned IP address.

Thanks!

**Comment by caseydavenport** [comment]
@rikatz It sounds like the simplest solution here is just logging which correlates the IP address with container / timestamp metadata.  How about updating this log with the right info https://github.com/projectcalico/cni-plugin/blob/master/k8s/k8s.go#L234?

Another option I'd consider if you're using Kubernetes would be to watch the Kubernetes API for Pod updates and monitor the IP addresses for each Pod.

**Comment by rikatz** [comment]
@caseydavenport Both options seems nice.

I don't know how to achieve any of them, but will try developing a simple Go program to watch the API and do so, probably feeding Graylog with that.

Thanks :D

**Comment by tomdee** [comment]
I'm closing this as I think the best way to implement it is through an additional tool.
