### ISSUE TITLE
Mesos CNI plugin set calico hostname

### ISSUE THREAD

**Issue by hegand** [projectcalico/cni-plugin#278]
Hi,

I have not found any options how can i set the hostname of the containers using marathon. Marathon gives a generated name to the docker containers and i would like to use other names as a hostname for the containers with calico.

For example i would like to use the hostname ngnix.calico_net instead of mesos-7ec3bb00-8e69-40df-8bc3-5d8a0a402454-S4.2870fd43-be4e-4b30-87dd-7995f5b1c8f0.calico_net.

Is this possible? Thank you very much.

**Comment by tmjd** [comment]
This https://groups.google.com/forum/#!topic/marathon-framework/s8Y6wQNYoRw 
says that it is possible by specifying parameters that translate to docker parameters.  And I don't think has anything to do with the cni-plugin.  @djosborne do you know?

**Comment by djosborne** [comment]
@hegand apologies this issue has taken so long for a response, seems to have slipped by.

@tmjd is right in that Mesos does not use CNI when networking docker containers. It uses Calico's docker-networking plugin: https://github.com/projectcalico/libnetwork-plugin

However, Calico is not responsible for setting the hostname container. It only reads the Agent's hostname and uses it as an ID. Calico has actually renamed / deprecated `HOSTNAME` in favor of `NODENAME` for this reason.

I believe it is Mesos' responsibility to set a task's hostname when it creates the container's namespace. You'll want to consult the Mesos / Marathon community for information on
