### ISSUE TITLE
Support CNI spec version 0.3.0

### ISSUE THREAD

**Issue by tomdee** [projectcalico/cni-plugin#280]
See https://github.com/rosenhouse/cni/blob/09e5feae1f9ac912f4c4fcfb688b95953a4c7f08/Documentation/spec-upgrades.md#for-plugin-authors

- [x] Step 1 - work out what this task involves...
- [x] Need VERSION command
- [ ] Support for chaining?
- [x] Updated tests?
- [ ] Any blockers now for better documented IPv6 support? Can we show it working with k8s and rkt?

**Comment by gunjan5** [comment]
The plan is to do this in 3 phases:

- [ ] (**v2.2.0**) Vendor in the latest CNI Spec 0.3.0 and change the code to compile.
- [ ] (**v2.2.0**) Refactor, use CNI repo helpers/utils, UTs
- [ ] (**v2.2.0?**) Chaining support, proper IPv6 support, support multiple IPs per pod, use upstream CNI testing framework, etc.

**Comment by tomdee** [comment]
Closing, @gunjan5 feel free to raise enhancements issue for the bits you didn't do if you want.
