### ISSUE TITLE
New IPAM feature tests are happy path only

### ISSUE THREAD

**Issue by lwr20** [projectcalico/cni-plugin#282]
We have tests for the new CNI config and pod annotation stuff in a few places:
- https://github.com/projectcalico/libcalico-go/blob/master/lib/client/ipam_test.go
- https://github.com/projectcalico/cni-plugin/blob/master/calico_cni_ipam_test.go
- https://github.com/projectcalico/cni-plugin/blob/master/calico_cni_k8s_test.go

But those tests look like happy-path tests to me.  I don't see enough failure cases.  

I think we need to add tests for these scenarios (lifted from the 2.1 ST plan):
- Add multiple ippools to a system.  Add workloads, requesting IPs from each pool.  Check they get assigned IPs from the correct pool.  Assign all the IPs from one pool.  Request another from that pool and CHECK IT FAILS.
- Request a particular IP for a workload (ipAddrs) from an existing pool that is already in use.  Check this fails.
- Request a particular IP for a workload - within an existing pool (ipAddrs).  Check it gets it.  Check IP gets marked as in-use.  Create workloads to use all the other IPs in the pool.  Check that none of them are offered the assigned one.  Delete all workloads.  Create then all again - check that the IPs all get re-used as expected.  
- Request a particular IP for a workload (ipAddrs) - outside existing pools.  Check it gets rejected.
- Request an IP from a disabled pool (ipAddrs) - check it fails.
- Request an IP from a disabled pool (ipv4pools) - check it fails.
- Request an IP from a disabled ipv6 pool (ipv6pools) - check it fails.
- Request a particular IP for a workload (ipAddrsNoIpam) - inside a DISABLED pool.  Check it succeeds.
- Request a particular IP for a workload - inside a DISABLED pool.  Check it succeeds.  Create another workload with the same IP.  Check it succeeds too.
- Request 'interesting' IPs: special addresses, invalid addresses, etc.  e.g link-local, loopback, 0.0.0.0, 256.0.0.0, 1.2, a.b.c.d, "reboot", 0100::/64, etc.  Check that the appropriate ones are rejected correctly and that nothing bad happens.

**Comment by lwr20** [comment]
If this isn't a v2.1.0 shipstopper, we should probably fix it before v2.2.0 to avoid having to re-run these tests manually.

**Comment by tmjd** [comment]
@lwr20 Do we need a backlog issue for this? Is this still valid?
