### ISSUE TITLE
IP forwarding on cali* interfaces not enabled

### ISSUE THREAD

**Issue by alexey-medvedchikov** [projectcalico/cni-plugin#283]
We have K8S environment with strict security policies. IP forwarding is disabled on system-wide level: we're enabling it on interfaces explicitly. So, by default, cali* interfaces created with forwarding disabled this leads to ARP malfunction (no ARP for 169.254.1.1).

Is it possible to set forwarding enabled on interface creation?

**Comment by fasaxc** [comment]
@alexey-medvedchikov Once you enable IP forwarding for a particular interface does it start working (including traffic to other hosts)?

**Comment by fasaxc** [comment]
Note: if we implement this, I think the fix belongs in Felix, along with the other per-interface config settings that we make: https://github.com/projectcalico/felix/blob/master/intdataplane/endpoint_mgr.go#L694

**Comment by alexey-medvedchikov** [comment]
@fasaxc yes, I've installed k8s with calico cni on host with `sys.net.ipv4.ip_forward` set to 0. My pods were unable to communicate (they even couldn't get gw mac). After enabling ip_forward on specific cali* interface the very one pod started to work -- it now can reach gw and internet too.
