### ISSUE TITLE
install Calico CNI should exit 1 when __KUBERNETES_SERVICE_HOST__ or __KUBERNETES_SERVICE_PORT__ is not set

### ISSUE THREAD

**Issue by ijumps** [projectcalico/cni-plugin#284]
For some reason, env like `__KUBERNETES_SERVICE_HOST__` and `__KUBERNETES_SERVICE_PORT__` may not be set when installing cni plugin, this cause bad behave for cni plugin.

kubelet log:
```
Mar 03 14:22:24 c8v221 kubelet[2199]: E0303 14:22:24.200285    2199 cni.go:255] Error adding network: Get https:///api/v1/namespaces/kube-system/pods/fluentd-elasticsearch-v1-n9spc: http: no Host in request URL
Mar 03 14:22:24 c8v221 kubelet[2199]: E0303 14:22:24.200321    2199 cni.go:209] Error while adding to cni network: Get https:///api/v1/namespaces/kube-system/pods/fluentd-elasticsearch-v1-n9spc: http: no Host in request URL
```

cni log:
```
[root@c6v198 ~]# docker logs -f b86b34431a5a
Installing any TLS assets from /calico-secrets
cp: can't stat '/calico-secrets/*': No such file or directory
Wrote Calico CNI binaries to /host/opt/cni/bin/
CNI plugin version: v1.5.6
Wrote CNI config: {
    "name": "k8s-pod-network",
    "type": "calico",
    "log_level": "info",
    "datastore_type": "kubernetes",
    "hostname": "kube-node-87",
    "ipam": {
        "type": "host-local",
        "subnet": "usePodCidr"
    },
    "policy": {
        "type": "k8s",
        "k8s_auth_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXpveThxIiwia3ViZXJuZXRlcy9zZXJ2aWNlYW3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJlNWRlZTJhNi1kZmYwLTExZTYtOGQwNS01MjU0MDBkOTg3YmQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.l3aHAY1WNj_rS-lZ4sM6O6ssJBuELLBb-xFi2jVzeWleAeFBbgo9KX0SQ_KglcI58XDNVopNzSqaequdbIck0tubinvtksBL0D_tMT7C_kRcSxf_3k3MyVwLr3TKilNW94Hs-6ani7ox2Iwo2AUUthGzI48zo_qMufMVy48qiN1fFpGGfCwRbl5Ax4aXaEQUDTxL8-34EpHwFUdiPB626YLWzTaUWWqFqbXC3DQJMimWLIMXmSE5Bt1siOBxTv1RqQlJ1RowAwfZ9xvQOnRtj8lYhfP0bzJXQouMmxDFuNiCFM6_hyHeDo5tPXM6cpysIz7XuU521lNko0sEEAwHuA"
    },
    "kubernetes": {
        "k8s_api_root": "https://:",
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
    }
}
Done configuring CNI.  Sleep=true
```

cni container env:
```
[root@c6v198 ~]# docker exec -it b86b34431a5a sh
/opt/cni/bin # env
KUBERNETES_NODE_NAME=kube-node-87
HOSTNAME=c6v198
SHLVL=1
HOME=/root
CNI_NETWORK_CONFIG={
    "name": "k8s-pod-network",
    "type": "calico",
    "log_level": "info",
    "datastore_type": "kubernetes",
    "hostname": "__KUBERNETES_NODE_NAME__",
    "ipam": {
        "type": "host-local",
        "subnet": "usePodCidr"
    },
    "policy": {
        "type": "k8s",
        "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
    },
    "kubernetes": {
        "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
        "kubeconfig": "__KUBECONFIG_FILEPATH__"
    }
}
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/cni/bin
PWD=/opt/cni/bin
```

Issue about env is not set: https://github.com/kubernetes/kubernetes/issues/40973

This's not really a calico bug, bug if `install-cni.sh` check the env and exit 1 when `__KUBERNETES_SERVICE_HOST__` or `__KUBERNETES_SERVICE_PORT__` is not set, kubelet will restart the container and set the env properly.

**Comment by caseydavenport** [comment]
Looks like we currently default to "" when that isn't set, which is wrong. https://github.com/projectcalico/cni-plugin/blob/master/k8s-install/scripts/install-cni.sh#L119

^ I think changing those lines to not use a default will do the trick.

We already `set -u` to ensure undefined variables cause an error: https://github.com/projectcalico/cni-plugin/blob/master/k8s-install/scripts/install-cni.sh#L9

**Comment by ijumps** [comment]
This right.

I run a k8s cluster about 90 nodes, after I reboot all those nodes, 7 of them face this issue. I will do the trick before this issue or k8s upstream issue is fixed

**Comment by zytek** [comment]
Confirmed when using kops to provision cluster with calico networking on AWS. One out of 3 nodes had wrong /etc/cni/net.d/10-calico.conf

**Comment by tomdee** [comment]
To fix this issue we could just remove the defaulting of variables (e.g. on https://github.com/projectcalico/cni-plugin/blob/master/k8s-install/scripts/install-cni.sh#L119) so the `set -u` causes a failure. But this will make the script rely on k8s specific env vars being present. To resolve this we could make it only care about doing the templating if it needs to, e.g. change the line to:
`grep "__KUBERNETES_SERVICE_HOST__" calico.conf.tmp && sed -i s/__KUBERNETES_SERVICE_HOST__/${KUBERNETES_SERVICE_HOST}/g calico.conf.tmp`

**Comment by tomdee** [comment]
This isn't going to make it into v2.2 anymore

**Comment by qiujian16** [comment]
We met the same issue...Is there any progress on this ticket?

**Comment by tmjd** [comment]
It has not been fixed yet.  Seems like a relatively small fix from the suggestions above. We welcome PRs. :smiley:
