### ISSUE TITLE
Clean up ADD code for Kubernetes

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#305]
The Calico CNI plugin uses the pod name / namespace to identify workload endpoints for Pods.

In the CNI ADD code, we handle a special case where we get an ADD for the same pod/namespace combo, to handle a historical bug where we didn't get DEL calls.

In v1.6, we no longer need to do this.

When v1.8 rolls around, we can simplify our ADD code to not need to do this any more (we'll leave it as is so we get a good amount of version overlap, simplifying the compatibility story)

**Comment by tmjd** [comment]
@caseydavenport I think this has been fixed. WDYT?

**Comment by caseydavenport** [comment]
I'm not sure if this has been fixed, but I don't think it's worth tracking this here either way.
