### ISSUE TITLE
Include container ID in WorkloadEndpoint Key

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#310]
We need to encode the container ID into the identifying information of the WorkloadEndpoint to fix https://github.com/projectcalico/calicoctl/issues/1592.

#### Design, as discussed with @tomdee:

- Add a new field called `ContainerID` to the WorkloadEndointMetadata struct in libcalico.

For example: 

```go
// ContainerID, when populated, contains an identifier for the container networked for 
// this WorkloadEndpoint. ContainerID is an optional field.
ContainerID string `json:containerID,omitempty" value:"omitempty,name"`
```

This field will need to be supported in the etcd datastore driver, but does not need to be populated by the Kubernetes datastore driver, since the KDD doesn't perform CRUD on WorkloadEndpoints. 

- The CNI ADD call will be modified to populate the new ContainerID field on the WorkloadEndpoints it creates.

- The CNI DEL call will be modified to respect the ContainerID field in the following ways.
  - If ContainerID != "" and ContainerID does not match CNI_CONTAINERID, return without deleting.
  - If ContainerID != "" and ContainerID matches CNI_CONTAINERID, then execute the delete.
  - If ContainerID == "", then execute the delete.

#### Testing

#1592 primarily affects the etcd datastore driver, and so testing should primarily be done against the etcd datastore, with simple smoke testing against the KDD.

We should add a unit test which does:
- CNI ADD with container ID X
- CNI DEL with container ID X
- CNI ADD with container ID Y
- CNI DEL with **_container  ID X_**

The end result of the test will be that a WorkloadEndpoint exists with container ID Y.

#### Documentation

Likely just a release note, with no user documentation updates required. 

#### Releases

This should go into v2.2, and be ported back to v2.1 as well.

**Comment by fasaxc** [comment]
Would it work to consider `pod A with container ID X` and `pod A with container ID Y` as different workloads.  I.e just encode the pod and container ID into the Workload field?

The datamodel was meant to be orthogonal to whether we're networking a container or a VM, for example, so the intention was the orchestrator would put whatever it needed in the Workload and Endpoint fields.

**Comment by tomdee** [comment]
Changing the workload "ID" is tricky for upgrade/downgrade so we judged it not to be the best design approach

**Comment by immesys** [comment]
Is there a hotfix?

**Comment by fasaxc** [comment]
@tomdee but where are you going to store this in etcd?  Where does it go in the backend key/data?

**Comment by robbrockbank** [comment]
I don't think this is the correct fix.  There is no way to easily engineer an extra index into the datastore key and so you'll end up needing to include this as part of the workload endpoint value and to perform the necessary checks on the CONTAINER_ID we'll need to do some CaS operations in the ds.  Seems like an overkill to me.

Can we do the following:

-  Update the CNI binary to use the container ID as the Workload ID (and feel free to prefix with the namespace and pod if so desired).
-  In the CNI plugin, perform up to two deletes:
  -  The first using the new Workload ID  (based on the container ID)
  -  If object does not exist,  try again using the old Workload ID (not based on the container ID)

I think that has the same effect no?

**Comment by tomdee** [comment]
Let's discuss this offline. Casey and I have already been over that option but decided against it.
