### ISSUE TITLE
Not creating route for tunl0

### ISSUE THREAD

**Issue by silentred** [projectcalico/cni-plugin#314]
I created a k8s cluster with kubeadm. When calico is deployed, I cannot find route for tunl0 interface. The full description is [here](http://stackoverflow.com/questions/43485770/route-not-working-in-kubernetes-with-calico). Is it because there are some conflicts in route table?

When I try to add a route manually, I got this error.
```
# route add -net 192.168.31.128 gw 10.30.248.80 netmask 255.255.255.192 dev tunl0
SIOCADDRT: Network is unreachable
```

**Comment by fasaxc** [comment]
@silentred you shouldn't need to manually add any routes via tunl0, the instance of BIRD running inside calico/node should do that for you if you have IPIP mode enabled and multiple hosts.  If you have multiple hosts but you're not seeing that, try `calicoctl node status` to see if BIRD is "established" or not.

**Comment by silentred** [comment]
@fasaxc  I found the problem. calico/node uses the public ip address of peers. But in my cloud environment, nodes cannot communicate with each other. 
```
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+------------+---------+
| PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |  INFO   |
+---------------+-------------------+-------+------------+---------+
| 47.93.161.177 | node-to-node mesh | start | 2017-04-19 | Connect |
+---------------+-------------------+-------+------------+---------+
```

Can I use internal ip?

**Comment by gunjan5** [comment]
@silentred you should be able to use `IP_AUTODETECTION_METHOD` to specify which interface/network to use. See http://docs.projectcalico.org/master/reference/node/configuration

**Comment by silentred** [comment]
Thanks. Problems solved! @gunjan5

**Comment by fasaxc** [comment]
Great, I'll close this issue.
