### ISSUE TITLE
[install-cni] k8s 1.6 refuses to launch pods due to absence of "bridge" plugin

### ISSUE THREAD

**Issue by eugene-chow** [projectcalico/cni-plugin#321]
The upgrade from k8s 1.5 to 1.6 produced a new error `failed to find plugin bridge`. I fixed the error by copying hyperkube's `bridge` plugin to `/opt/cni/bin`. I'm not sure why v1.5 can do without the bridge but v1.6 needs it.

I noticed that the `install-cni` container only installs `calico`, `calico-ipam`, `flannel`, `host-local`, `loopback`. Should the bridge plugin be included in future releases?

**Comment by ae6rt** [comment]
I have a k8s 1.6.2 cluster with calico v2.1.4 binaries and the calico-cni plugin with the loopback plugin.  I can launch pods and establish basic IP networking between them.  My cluster is assembled from a set of binaries and provisioned with Ansible scripts of my own making.  I wonder why I don't see what you see?

**Comment by tmjd** [comment]
@eugene-chow Could you retrieve your CNI configuration file and attach it here, please redact any sensitive information?

**Comment by eugene-chow** [comment]
I used a BASH [script](https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/generic/controller-install.sh#L830) by CoreOS that installs both flannel and calico.

On 2nd thought, it might be an issue with flannel but I'm not certain. Please advise. Thanks!
```
{
    "name": "calico",
    "type": "flannel",
    "delegate": {
      "type": "calico",
      "etcd_endpoints": "https://10.246.40.30:2379,https://10.246.40.31:2379,https://10.246.40.32:2379",
      "etcd_ca_cert_file": "/etc/calico/ssl/ca.pem",
      "etcd_cert_file": "/etc/calico/ssl/client.pem",
      "etcd_key_file": "/etc/calico/ssl/client-key.pem",
      "log_level": "info",
      "policy": {
          "type": "k8s",
          "k8s_api_root": "https://10.3.0.1:443",
          "k8s_auth_token": <auth_token_goes_here>
      },
      "kubernetes": {
          "kubeconfig": "/etc/kubernetes/cni/net.d/calico-kubeconfig"
      }
    }
}
```

**Comment by tmjd** [comment]
Yeah I think that would be something that flannel is trying to use in this configuration but I'm not real sure. 
@tomdee do you happen to know?

**Comment by caseydavenport** [comment]
The calico CNI plugin doesn't require the bridge plugin installed.

Make sure that you've got the kubelet configured with `--network-plugin=cni` and not `kubenet`
