### ISSUE TITLE
Shouldn't configure-calico resource be job, instead of pod?

### ISSUE THREAD

**Issue by dolftax** [projectcalico/cni-plugin#322]
In kubernetes, the configure calico `configure-calico-foo` pod should be a job? Because, as the configuration is done, the pod is terminated. But, kops validator shows

```
Pod Failures in kube-system
NAME
configure-calico-foo
```

Can't blame kops as it considers the config as pod resource. Why not move it as a job?

**Comment by tmjd** [comment]
Could you please provide a link where you found the manifest that runs it as a pod?

In the latest v2.1 Calico release the configure job has been removed in favor of flags set on the calico-node pod (latest release example http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/calico.yaml).

In the previous release v2.0 the configuration was a `kind: Job` (see http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/calico.yaml).

**Comment by dolftax** [comment]
Via kops - https://github.com/kubernetes/kops/blob/master/docs/networking.md#installing-calico-on-a-new-cluster

Looks like they are using very old version of calico, then.

cc: @chrislovecnm

**Comment by tmjd** [comment]
Thank you for the link.  It certainly looks like the templates they use aren't updated with the absolute latest but I could not locate any in the latest kops or the 1.5.3 release that are not already using a Kubernetes `kind: Job` for the configuration.  What version of kops are you using?  Did I perhaps misunderstand your suggestion to use a Job?  Is the job you are referring to a kops concept or referring to a K8s Job?

Thanks for the info.

**Comment by caseydavenport** [comment]
CC @heschlie

**Comment by dolftax** [comment]
@tmjd It doesn't use a job. It uses pod. But short-running pod just to configure calico and auto terminates. Since the status of the pod is changed to `terminated`, our monitoring systems alert that a pod is down.

I was suggesting to use a job to configure calico instead of a pod.

**Comment by caseydavenport** [comment]
AFAIK, this is already a Job and has never been a standalone Pod.  Do you have a link to the manifest that uses a Pod?

This is the only one I'm aware of for Kops: https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.6.yaml.template#L227

Jobs start Pods, so you may see stopped Pods in the output of kubectl that were started by the Job.

**Comment by tmjd** [comment]
I'm going to close this issue since the manifests Kops is using already use a Job for the configure step (and Calico has actually eliminated the need for that configure step in the latest release).  @dolftax if there is still something you think needs to be fixed in the cni-plugin or Calico please feel free to reopen and help us understand what the existing issue is.
Thank you for your report.

**Comment by dolftax** [comment]
@tmjd Not sure if its related. Check https://github.com/kubernetes/kops/issues/2529

**Comment by tmjd** [comment]
@dolftax The solution that @ozdanborne is working as on will remove the need for that job/pod

**Comment by dolftax** [comment]
Yeah. Sounds good.
