### ISSUE TITLE
Host port support

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/cni-plugin#323]
Tasks:
- [x] Build the hostport binary
- [x] Obtain/build a version of kubernetes that supports plugin chaining 
- [x] Create a CNI config for CNI and hostports (reviewed) 
- [x] manual test
- [x] docs update, integrating into automated tests
- [x] include hostport binary in the release

**Comment by caseydavenport** [comment]
For those listening in, hostport support is present in v2.3.0 of Calico (cni-plugin release v1.9) using the upstream containernetworking/plugins `portmap` plugin.

The missing bits are adding it to all the checked-in manifests and documentation, which I think we should hold off on for a little bit since it requires k8s version <v1.7.0 and we want to give a bit of a window before making breaking changes to the docs.

**Comment by gtaylor** [comment]
For those of us who would like to try this before the manifests are updated, do we have the new versions in a branch somewhere? Would be keen to test.

**Comment by caseydavenport** [comment]
@gtaylor I've put this PR up with the changes I think we'd need: https://github.com/projectcalico/calico/pull/903/files

I haven't done much (any) testing on those changes yet, so feedback is appreciated if you do try them out!

**Comment by gtaylor** [comment]
Thank you very much, @caseydavenport!

**Comment by gtaylor** [comment]
@caseydavenport I just tried doing something like this:
[calico-ex.txt](https://github.com/projectcalico/cni-plugin/files/1261798/calico-ex.txt)
Looks like a "cannot find network namespace" error:
[kubelet.log.txt](https://github.com/projectcalico/cni-plugin/files/1261803/kubelet.log.txt)
This is a 1.7.4 cluster with Calico 2.4.1 in datastore + user-supplied networking mode. I'm only doing IPIP across subnets (which differs from your configs).

**Comment by gtaylor** [comment]
Updated with my results here: https://github.com/projectcalico/calico/pull/903#issuecomment-325811639

**Comment by caseydavenport** [comment]
Closing since the manifests at docs.projectcalico.org include hostport support.
