### ISSUE TITLE
client: response is invalid json.

### ISSUE THREAD

**Issue by Slahser** [projectcalico/cni-plugin#327]
thx for your work.

and i setup a external etcd v3 cluster

with doc <Standard Hosted Install> and i change it with RBAC setting .

but i get 

'client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.'

i think the etcd api difference cause it

is there a roadmap about support etcd v3 cluster?

or there is other solution?

below is complete log: 

```
 »»»» kubectl logs po/calico-node-rd3bl -n kube-system -c calico-node                                         0|19:31:02
time="2017-05-04T11:31:12Z" level=info msg="NODENAME environment not specified - check HOSTNAME"
time="2017-05-04T11:31:12Z" level=info msg="Loading config from environment"
Skipping datastore connection test
time="2017-05-04T11:31:12Z" level=info msg="Unhandled error: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint."
time="2017-05-04T11:31:12Z" level=info msg="Unable to query node configuration" Name=k8s-node-3 error="client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint."
ERROR: Unable to access datastore to query node configuration
Terminating
Calico node failed to start
```

**Comment by tmjd** [comment]
The etcd v3 server still supports the etcd v2 API.  Etcdv3 has been tested to work with Calico with Calico just using the v2 API, so it is doubtful that etcd v3 is the problem.  You should be able to hit/curl the etcd endpoint you are specifying and append `/version` to see the version of the etcd server.

**Comment by caseydavenport** [comment]
@Slahser can you share the configuration you're using? Specifically the value you've set for `etcd_endpoints`?

**Comment by Slahser** [comment]
Ah i test it after this issue. my k8s-dns can not write into etcd too.
maybe it is because the etcd cluster ... 

i will close this issue.
