### ISSUE TITLE
Change installation defaults for cni-plugins 

### ISSUE THREAD

**Issue by timothysc** [projectcalico/cni-plugin#342]
Calico CNI plugins install themselves via daemonsets onto the hosts but default to the /opt path when in reality it should check a set of directories in order to determine cni path.  Different OS distributions and packages will have different policies.  For example RH/CentOS/Fedora will package cni into `/usr/libexec/cni` per packaging guidelines.  

## Expected Behavior
installs the calico plugin to the proper location according to distribution which could be /usr/libexec/cni for distributions that have formal packages and /opt for informal packages. 

## Current Behavior
defaults to /opt

## Possible Solution
Update the installation script to check location of cni installation.  

## Steps to Reproduce (for bugs)
Kubeadm installation using fedora cni package

## Context
NONE

## Your Environment
*

/cc @jbeda

**Comment by timothysc** [comment]
erik.stidham [2:02 PM] 
yeah, it is done by the `install-cni` container.

[2:02] 
it installs the calico and calico-ipam binaries

tstclair [2:02 PM] 
Where does it install them to?

erik.stidham [2:03 PM] 
`/opt/cni/bin`

tstclair [2:03 PM] 
k, that explains the weirdness.

[2:04] 
https://github.com/kubernetes/release/pull/334/files#diff-e5aea90ad6dcb89b302f426c24cfaa52R187
GitHub
WIP: Include cni source builds into the specs by timothysc · Pull Request #334 · kubernetes/release
Includes source build spec for CNI. Fixes: #324 #310 #242 Todo: Obsoletes : kubernetes-cni What todo with the other plugins and which plugins to include? calico, weave ... ? /cc @mikedanese
 

[2:05] 
Packaging guidelines would prefer /usr/libexec/cni then /opt

[2:05] 
opt would be "when all else fails"  where is that script?

**Comment by tmjd** [comment]
What is the issue that you would like to see addressed?
That the default be changed to /usr/libexec/cni/bin/plugins?

**Comment by timothysc** [comment]
It should check /usr/libexec/cni 1st, then /opt 2nd.  There are "official" and "unofficial" cni packages.

**Comment by timothysc** [comment]
for completeness all plugins are installed to a flat location 

` 
%{_libexecdir}/cni/* 
`

**Comment by caseydavenport** [comment]
I'm not sure I understand this issue, so could use some clarification :)

Some k8s deployments I've seen use `/home/kubernetes/cni/bin`, but most use `/opt/cni/bin` and `/etc/cni/net.d`.  Sometimes one or more of the common directories is read-only.   The place that the Calico DaemonSet installs the binaries is configurable [via volume mounts](https://github.com/projectcalico/calico/blob/master/master/getting-started/kubernetes/installation/hosted/calico.yaml#L206)

The default for kubelet is `--cni-bin-dir=/opt/cni/bin` and `--cni-net-dir=/etc/cni/net.d`, so I don't see why those shouldn't be the defaults in the DaemonSet Calico ships?

**Comment by timothysc** [comment]
The default cni directory for the kubelet plugin violates packaging guidelines for upstream channel packages.  Fedora/RHEL/CentOS

**Comment by caseydavenport** [comment]
Hm.  A long time ago the kubelet default was changed out of `/usr` because CoreOS [mounts that directory as read-only](https://coreos.com/os/docs/latest/sdk-disk-partitions.html#read-only-usr) meaning that you can't install plugins to that directory.

**Comment by timothysc** [comment]
@caseydavenport It's going to vary slightly by distro.

**Comment by caseydavenport** [comment]
Ok.  Would you mind updating the issue description with the expected behavior? I think this isn't so much about using a DaemonSet to install the CNI binaries, rather its about where the already existing DaemonSet installs those binaries.

**Comment by timothysc** [comment]
@caseydavenport updated.

**Comment by timothysc** [comment]
It boils down to slightly changing your submission .yaml for volume mounts based on targets OS deployment.  

from: 

```
hostPath:
            path: /opt/cni/bin
```

to:

```
hostPath:
            path: /usr/libexec/cni
```

**Comment by jasonbrooks** [comment]
Fedora/CentOS Atomic also have a read only /usr, so to the extent that plugins need to drop their own binaries somewhere, something under /usr isn't going to work. Fedora has a containernetworking-cni package now, and it puts binaries into /usr/libexec/cni, but that's not going to be a writable location when the pod is running.

**Comment by timothysc** [comment]
@ingvagabund thoughts here?

**Comment by ingvagabund** [comment]
> Calico CNI plugins install themselves via daemonsets onto the hosts

How does it actually works? The CNI plugins should live inside a container that is distributed via the DaemonSets. So it should not matter where it is installed. Or, is the container mounting host paths through which it "installs" the CNI plugins on the host itself?

**Comment by timothysc** [comment]
@ingvagabund the kubelet on the host needs access to the plugins, so there is a daemonset which mounts the host location and drops a binary there, which is sketchy, but that's pretty much how all cni-plugins work 2day.

**Comment by jasonbrooks** [comment]
Pretty much, /var and /etc -- /home points to /var/home, /opt points to /var/opt -- so in some of the kubeadm tests I've done, I made a dir at /var/opt/cni/bin and put symlinks to the cni binaries from the cni pkg there, and then when the plugin tried to put stuff into /opt/cni/bin itself, that worked because those binaries were actually going under /var/opt

**Comment by timothysc** [comment]
@jasonbrooks I could update the packaging to create the symlinks.?.? 
Thoughts?

**Comment by jasonbrooks** [comment]
I used tmpfiles.d to create them like this: 

https://github.com/jasonbrooks/release/blob/atomic/rpm/kubernetes-cni.conf
install -p -m 755 -t %{buildroot}/%{_prefix}/lib/tmpfiles.d/ kubernetes-cni.conf

I don't know if that's janky, though.

**Comment by timothysc** [comment]
Ok, I've updated my .spec to alternative install to /opt and use softlinks and cleanup with %ghost... 

It feels janky, but it works and follows the rules so I'm going to close this.

**Comment by rparulek** [comment]
@jasonbrooks I was reading the content on this issue and saw your replies wrt CNI plugin binaries and creating synlinks as follows:

I used tmpfiles.d to create them like this:

https://github.com/jasonbrooks/release/blob/atomic/rpm/kubernetes-cni.conf
install -p -m 755 -t %{buildroot}/%{_prefix}/lib/tmpfiles.d/ kubernetes-cni.conf

I don't know if that's janky, though.

Can you explain how and where these tmpfiles will get invoked and built to for the CNI symlinks to take effect?
