### ISSUE TITLE
V1.7.0:Failed get valid IP addresses when node reboot

### ISSUE THREAD

**Issue by mozhuli** [projectcalico/cni-plugin#349]
## Expected Behavior

Pod should get the right ip when reboot node
## Current Behavior

Pod incurred error when reboot node
```
E0623 06:52:51.949289    2738 cni.go:255] Error adding network: cannot convert: no valid IP addresses
E0623 06:52:51.949333    2738 cni.go:209] Error while adding to cni network: cannot convert: no valid IP addresses
E0623 06:52:51.949382    2738 docker_manager.go:2231] Failed to setup network for pod "ddd-hh04r_kube-system(faf4f66e-572d-11e7-b1d3-00219ba7a2aa)" using network plugins "cni": cannot convert: no valid IP addresses; Skipping pod
E0623 06:52:51.958733    2738 docker_manager.go:372] NetworkPlugin cni failed on the status hook for pod 'ddd-hh04r' - Unexpected command output nsenter: cannot open /proc/8953/ns/net: No such file or directory
```
But kill the error pod and the recreated pod work.

## Steps to Reproduce (for bugs)

1.create a deployment
2.reboot a node which has the pod creatd by step one

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):`v1.7.0`
* Orchestrator version (e.g. kubernetes, mesos, rkt):`kubernetes 1.5.3`
* CNI config:
* Operating System and version:centos7.0
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@mozhuli can you share the CNI config you're using (likely found on the node at /etc/cni/net.d/10-calico.conf)?

That error message appears to be coming from the CNI conversion code.  It sounds like it might be a problem with the IPAM plugin failing to get an IP address. 

How are you deploying Calico - is it via a kubernetes manifest? If so, which one?

**Comment by mozhuli** [comment]
I just use the official calico.yaml with calico v2.1.4. but it is work with k8s 1.6.4, Is there some conflict in calico v2.1.4 with k8s v1.5.3？

**Comment by mozhuli** [comment]
@caseydavenport 
```
cat /etc/cni/net.d/10-calico.conf
{    
    "name": "k8s-pod-network",   
    "type": "calico",  
    "etcd_endpoints": "http://10.18.210.129:2379,http://10.18.210.231:2379,http://10.18.210.179:2379", 
    "log_level": "info",    
    "ipam": {      
        "type": "calico-ipam"  
     },   
    "policy": {     
         "type": "k8s",        
         "k8s_api_root": "https://10.96.0.1:443",    
         "k8s_auth_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTVuNWR2Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5NTUzODFjZi01NjZhLTExZTctOWVhYi0wMDIxOWJhN2EyYWEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.e04Yxsec64L7ostBlyFhY1t_2stwn1WKMMbJ4O-nOThYiifA_koJmVbkZErFOJPTHe2CqLq-7vu6fnt8T2-u1d0VVS7Oyw1G6W_PS57y_cWAPoCUwyubueTlP5ff24i2aJSc0nJEHIO_7wL0WnM2AgUs42h7wUOI3kAAQLRok708axp2KS9KihiDIAWdmbMYiu62j_UeqaJWPTS1bB_awuUtm3LNdQR_zqkS9BVRI2bd_UmiN6lwvkOsQepJOF_soHSzwPAy-yw4CcfdVbOXOjSRM1_PRWaTIVlbEaIQoZ8wIPRm-BEL2wQW1UkOhKAMxilpuTesXQx5crH1yC5WBA"  
     },  
     "kubernetes": {     
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"  
     }
}
```

**Comment by tmjd** [comment]
The release notes for Calico v2.1.5 has
> Include a new version of the CNI plugin to fix a data parsing crash when nodes restart

@mozhuli I think you should upgrade to the newer Calico version which includes CNI plugin (v1.8.0) and try again?

**Comment by mozhuli** [comment]
@tmjd Thank you very much！Upgrading cni to v1.8.0 has solved my problem.

**Comment by tmjd** [comment]
That's great.  Thank you for reporting back.  I'm going to close this issue then.  Please let us know if you run into any additional issues.
