### ISSUE TITLE
Error creating: No API token found for service account "calico-policy-controller",

### ISSUE THREAD

**Issue by eqkou** [projectcalico/cni-plugin#353]
## Expected Behavior

Successfully install calico on k8s 1.7

## Current Behavior

Cannot install calico on k8s 1.7

## Steps to Reproduce (for bugs)

1. install k8s 1.7
2. download calico.yaml
3. kubectl apply -f calico.yaml
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
* Orchestrator version (e.g. kubernetes, mesos, rkt):
k8s
* CNI config:
* Operating System and version:
centos 7.3
* Link to your project (optional):

```NAMESPACE     NAME                              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/calico-policy-controller   1         0         0            0           19m

NAMESPACE     NAME                                     DESIRED   CURRENT   READY     AGE
kube-system   rs/calico-policy-controller-3271399580   1         0         0         19m
```
```Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  21m           8m              18      replicaset-controller                   Warning         FailedCreate    Error creating: No API token found for service account "calico-policy-controller", retry after the token is automatically created and added to the service account```

**Comment by caseydavenport** [comment]
@eqkou sounds like your k8s v1.7 cluster isn't generating API tokens automatically. 

Is your cluster configured to do that?  
See here for more info: https://kubernetes.io/docs/admin/service-accounts-admin/

**Comment by eqkou** [comment]
@caseydavenport not sure, let me take a look, thanks
