### ISSUE TITLE
How to install calico onto master node?

### ISSUE THREAD

**Issue by zucig** [projectcalico/cni-plugin#357]
Hello, can you tell me how to install calico onto master node? 

`kubectl apply -f calico.yaml` only install calico onto worker nodes

Currently I have k8s 1.7 cluster with 1 master, 3 nodes

master: kube-apiserver, kube-controller-manager, kube-scheduler
nodes: kubelet, kube-proxy, docker

**Comment by caseydavenport** [comment]
@zucig one option would be to install the kubelet on your master - that way the Pod would get started on the master.

Alternatively, you _can_ run `calico/node` directly using Docker or systemd.  [This doc](http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/integration#installing-caliconode) talks a bit about that.

**Comment by zucig** [comment]
thank you
