### ISSUE TITLE
Output from install-cni.sh prints k8s_auth_token field in plaintext to logs

### ISSUE THREAD

**Issue by struz** [projectcalico/cni-plugin#360]
## Expected Behavior

k8s_auth_token field should be masked.

## Current Behavior

k8s_auth_token field is printed in plain text, along with the rest of 10-calico.conf.

## Possible Solution

Mask that field away by piping to sed before using echo.

## Context

In our cluster we log all container logs from `/var/logs/container/*` which then goes into a centralised logging platform. Logging the service account token like this allows anyone with access to the log platform to impersonate the calico service account in our cluster which is an undesirable outcome for cluster security. In some clusters this will be the kube-system service account which has a lot of privileges. Thankfully in our cluster we already made a separate account with limited permissions.

## Your Environment
calico/cni:1.9.1

**Comment by caseydavenport** [comment]
@struz thanks for raising - definitely want to fix this.  @gunjan5 do you have time this week? It should be a quick one.

**Comment by struz** [comment]
Any movement on this? In the meantime we have made sure that the role interacting with the cni installer only has access to the minimum necessary cluster privileges to do its job, but it would be nice to keep the credentials hidden.

**Comment by caseydavenport** [comment]
@struz there is a PR open here https://github.com/projectcalico/cni-plugin/pull/361 that's really close to being merged, just waiting on @gunjan5 to make the final markups.

Expecting this to be in Calico v2.6.0 provided @gunjan5 has the time.
