### ISSUE TITLE
Use upstream portmap plugin releases (when available)

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#362]
We currently host our own build of the portmap plugin to include in calico/cni. We should switch to the upstream release when v0.6.0 comes out.

**Comment by dada941** [comment]
v0.6.0 is out now. It would be great to have the latest portmap binary included in the calico-cni container, as the current one doesn't work with chaining, cf : https://github.com/containernetworking/plugins/issues/43

**Comment by caseydavenport** [comment]
@dada941 thanks for the update - we should definitely switch to using v0.6.0.

However, I'm not sure what you mean by the current one not working with chaining.  I know we've successfully tested the portmap plugin that ships with Calico in chained environments. Is there a specific issue?

The one you linked appeared to be a flannel CNI issue rather than a portmap issue.  Sounds like we should pull in the latest flannel binary as well.

**Comment by dada941** [comment]
@caseydavenport - yes you're right, it is indeed a flannel issue not portmap. Sorry for the confusion.
We've tested it manually with cni 0.6.0-rc1 and all works as expected.
