### ISSUE TITLE
Some questions for porting Calico cni-plugin to ARM64 platform

### ISSUE THREAD

**Issue by TrevorTaoARM** [projectcalico/cni-plugin#364]
Dear Calico cni-plugin authors:

Now I am porting Calico cni-plugin to ARM64(aarch64) platform, but I met some problems when I did the porting:
1.  Calico cni-plugin currently uses some docker images for testing purpose, such as calico/go-build, etcd, but I can't find the correponding images for ARM64(aarch64)  on other public Dockerhub.  So I built the 2 docker images of aarch64 and put them on to trevortaonb/go-build-aarch64 and trevortaonb/etcd-aarch64 on Dockerhub.  
The question is if I give the possible patch for AArch64,   do you accept that docker image? 
If not, can you give out where the docker image should I put to? 
If my company gives out some other places (in the Dockerhub) to put docker images, would them be acceptable?

2. For the Makefile in the latest master branch,   K8S_VERSION=1.6.1, but when I do the 'make' operation, it shows some errors with:
•! Panic in Spec Setup (BeforeEach) [0.004 seconds]
CalicoCni
/go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:947
  Run Calico CNI plugin in K8s mode [BeforeEach]
  /go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:946
    using host-local IPAM
    /go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:945
      successfully networks the namespace
      /go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:206

      Test Panicked
      Get http://localhost:8080/api/v1/namespaces/test/pods: dial tcp [::1]:8080: getsockopt: connection refused
      /usr/local/go/src/runtime/panic.go:489

      Full Stack Trace
        /usr/local/go/src/runtime/panic.go:489 +0x1e4
      github.com/projectcalico/cni-plugin/test_utils.WipeK8sPods()
If I use K8S_VERSION=1.6.6, the error is like:
•! Panic in Spec Setup (BeforeEach) [60.006 seconds]
CalicoCni
/go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:947
  Run Calico CNI plugin in K8s mode [BeforeEach]
  /go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:946
    using host-local IPAM
    /go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:945
      successfully networks the namespace
      /go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:206

      Test Panicked
      the server cannot complete the requested operation at this time, try again later (get pods)
      /usr/local/go/src/runtime/panic.go:489

      Full Stack Trace
        /usr/local/go/src/runtime/panic.go:489 +0x1e4
      github.com/projectcalico/cni-plugin/test_utils.WipeK8sPods()
        /go/src/github.com/projectcalico/cni-plugin/test_utils/utils.go:115 +0x2e8
      github.com/projectcalico/cni-plugin_test.glob..func2.1()
        /go/src/github.com/projectcalico/cni-plugin/calico_cni_k8s_test.go:41 +0x18
      github.com/projectcalico/cni-plugin/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0x4420016ba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/projectcalico/cni-plugin/calico_cni_suite_test.go:12 +0x64
      testing.tRunner(0x442030aa90, 0x10902d8)
        /usr/local/go/src/testing/testing.go:657 +0x84
      created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:697 +0x240

But I can make successfully if I set the K8S_VERSION=1.5.3, and I think it may be related to the setting of "kubeconfig" file(and I see a kubeconfig.sample file in the dir), so what is the problem with K8s 1.6.x and where should I put the "kubeconfig" file? Can I just uses the 1.5.3 for possible ARM64 patch?

3.  Now the Makefile uses portmap, but for ARM64, there is no corresponding portmap binary but in the latest cni plugins with 
https://github.com/containernetworking/plugins/releases/download/v0.6.0-rc1/cni-plugins-arm64-v0.6.0-rc1.tgz, 
can I just uses that version?

4.  What about the email addresses for discussing some technical issues for Calico and its cni-plugin?

Thank you very much,

Trevor Tao

**Comment by tmjd** [comment]
1. I'm not sure about this one, I don't know if we've answered this question before.
2. I don't think we would want to start out using a kubernetes version that is several versions behind to start with.  You may want to check the Kubernetes release notes for ARM64 to see if there are any differences for the ARM64 builds vs the amd64 builds since 1.6.1 works on amd64.
3. @gunjan5 do you know the answer to this?
4. The best place to discuss technical issues would be the calicousers.slack.com, you can get an invite here https://www.projectcalico.org//community

**Comment by gunjan5** [comment]
@TrevorTaoARM @tmjd 
3. yes you should be able to use the latest upstream `portmap` plugin, we had to ship the binary for with Calico CNI 1.9.0 because portmap plugin wasn't merged and released at the time, so we built the binary before it was in an actual release

**Comment by TrevorTaoARM** [comment]
@gunjan5 @tmjd 
3. yes, if the pre-release of plugins v0.6.0-rc1 can be accepted, it is posssible to just use a unified CNI_VERSION for both amd64 and arm64. 
If not, I would just set a separate process to arm64 just like:
ifeq ($(ARCH), arm64)
CNI_VERSION=v0.6.0-rc1
endif
What's your opinion on this?

For question 2, after some retrying, I find it is due to some problems of my etcd docker img, so it is resolved now. 
Thank you,

**Comment by tmjd** [comment]
@caseydavenport What do you think about question 1?  If we don't have an answer we need to figure out how to handle these cases.

**Comment by caseydavenport** [comment]
> such as calico/go-build, etcd, but I can't find the correponding images for ARM64(aarch64) on other public Dockerhub

Yeah, I think we'd at least want to own the `calico/go-build` image.

If CoreOS doesn't maintain an ARM etcd image then I'm happy to use whatever the accepted version is (if one exists) or anything that works and gets us unblocked.

**Comment by TrevorTaoARM** [comment]
@caseydavenport @tmjd  Thank you, I would choose the most appropriate images as I can for it.

**Comment by TrevorTaoARM** [comment]
@caseydavenport Since I have not found any Calico and its related images from public docker hub for arm64 until now, and actually I am doing the Calico enabling work on ARM64, so I think some( maybe most) images used in building Calico( and all its components) would have to built by myself, and I would push them to docker hub for public access. 
At the same time, if I can access a public account of docker hub in the near future with the help of my company, I would like to push the images there too and use those images(in Calico's building for arm64).
If you have any ideas on this issue, feel free to contact me.
Thanks a lot for your care and help

**Comment by caseydavenport** [comment]
@TrevorTaoARM would you be open to upstreaming your build work into the projectcalico organization?

Then we could include the ARM64 binaries as part of our standard releases and host them alongside other official images.

**Comment by TrevorTaoARM** [comment]
@caseydavenport Yes, I am very willing to upstream my build work into projectcalico organization :-), which would greatly facilitate my subsequent work on Calico for arm64. 
But now with the policy restriction of my company, I can not provide the built image directly to the community.   
A trade-off solution to this problem from my company's suggestion is that I provide the related Dockerfiles to 'linaro.org' which would review the Dockerfile and build the docker image to the 'linaro' account of docker hub.  So I would provide the related files to 'linaro.org' to build the Calico related images for arm64. If my commit is reviewed and accepted, the name of built images for Calico ARM64 would be something like 'linaro/calico-xxx-arm64', such as 'linaro/calico-go-build-arm64', 'linaro/calico-etcd-arm64'.  And I would use that images in my possible commit for Calico arm64 patches to Calico org. 
(in this way it would certainly add some delay to my work to a large extent, but now actually I have no other choices)

You can see my Dockerfile submit to linaro.org with Gerrit site of linaro:
https://review.linaro.org/ci/dockerfiles
 which is open for accessing.
(Btw, as now I don't have a linaro account of myself, you may see another commit person for Calico related dockerfiles, but actually it's me)

I think you are free to use those built calico images from the 'linaro' account in docker hub, and also free to put those binaries to Calico's standard releases as official images if you will,  which would also greatly facilitate my work on Calico's enabling work on arm64.

For the docker images under my personal account, I think it's open for access.

How about your ideas, and it's glad to hear from you.

Thank you very much,

**Comment by TrevorTaoARM** [comment]
@caseydavenport @tmjd @gunjan5 
Now I am trying to push my arm64 support patch to Calico cni-plugin, but it shows that I don't have the correct access rights as following:
cni-plugin# git push origin arm64_support
ERROR: Permission to projectcalico/cni-plugin.git denied to trevortao.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I have signed the Contributor License Agreement at:
https://www.projectcalico.org/community/individual-contributor-agreement/, and the signed PDF files to maintainers@projectcalico.org.

What should I do for it?

Thanks,

**Comment by caseydavenport** [comment]
Going to close this for now since I _think_ your questions have been answered, and there's various bits of multi-arch stuff going on elsewhere.

Please open another if there are more questions, or reach out on slack.projectcalico.org channel #calico-dev
