### ISSUE TITLE
Statefulsets with initContainers can lose networking

### ISSUE THREAD

**Issue by carsonoid** [projectcalico/cni-plugin#385]
This is most likely a continuation of #310.

I have a cluster running all the components from the v2.5.1 release. This includes cni well over v1.7.0 which fixed #310.  Most StatefulSets work exactly as expected now.  The issue is when StatefulSets are combined with an initContainer that modifies the pod before the primary container is created.

## Expected Behavior

Statefulsets should be able to handle pod updates/deletions for all use-cases

## Current Behavior

Statefulsets with initContainers that modify the pod can break networking entirely.

## Steps to Reproduce

Here are some commands to replicate. It creates:
 *  a new namespace
 * a basic nginx deployment/service to test against
 * two statefulsets:
   * One that has a trivial initContainer
   * One that uses the initcontainer to label the pod before it starts. 
      See https://github.com/kubernetes/kubernetes/issues/44103 to understand why I would want to label pods using an init container.

Commands:

```bash
kubectl create namespace ss-test
kubectl --namespace=ss-test run nginx --image=nginx
kubectl --namespace=ss-test expose deployment nginx --port=80
set +o history
kubectl --namespace=ss-test create -f <(cat <<'EOF'
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ss-tester
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ss-tester
---
apiVersion: v1
kind: Service
metadata:
  name: ss-tester
spec:
  ports:
  - port: 80
    name: default
  clusterIP: None
  selector:
    app: ss-tester
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ss-tester
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: "ss-tester"
  replicas: 3
  template:
    metadata:
      labels:
        app: ss-tester
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-config
        image: alpine
        command: ['/bin/sh', '-c', 'date']
      containers:
      - name: ss-tester
        image: alpine
        command:
        - /bin/sh
        - -e
        - -c
        - while true; do wget -T 3 -O - nginx; sleep 1; done
---
apiVersion: v1
kind: Service
metadata:
  name: ss-tester-brittle
spec:
  ports:
  - port: 80
    name: default
  clusterIP: None
  selector:
    app: ss-tester-brittle
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ss-tester-brittle
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: "ss-tester-brittle"
  replicas: 3
  template:
    metadata:
      labels:
        app: ss-tester-brittle
    spec:
      serviceAccountName: ss-tester
      terminationGracePeriodSeconds: 10
      initContainers:
      - args:
        - -c
        - /usr/local/bin/kubectl label pods "${HOSTNAME}" test=value
        command:
        - /bin/sh
        image: lachlanevenson/k8s-kubectl
        imagePullPolicy: IfNotPresent
        name: label-set
        resources: {}
        terminationMessagePath: /dev/termination-log
      containers:
      - name: ss-tester
        image: alpine
        command:
        - /bin/sh
        - -e
        - -c
        - while true; do wget -T 3 -O - nginx; sleep 1; done
EOF
)
set -o history
```

Once you run the commands above you will get a ss-test namespace with two happy statefulsets constantly talking to the nginx container.

```
# kubectl --namespace=ss-test get po -o wide
NAME                     READY     STATUS    RESTARTS   AGE       IP                NODE
nginx-4217019353-0b266   1/1       Running   0          2m        192.168.144.157   ip-172-30-6-62.ec2.internal
ss-tester-0              1/1       Running   0          2m        192.168.200.218   ip-172-30-6-246.ec2.internal
ss-tester-1              1/1       Running   0          1m        192.168.144.168   ip-172-30-6-62.ec2.internal
ss-tester-2              1/1       Running   0          1m        192.168.124.245   ip-172-30-6-234.ec2.internal
ss-tester-brittle-0      1/1       Running   0          2m        192.168.144.169   ip-172-30-6-62.ec2.internal
ss-tester-brittle-1      1/1       Running   0          1m        192.168.124.240   ip-172-30-6-234.ec2.internal
ss-tester-brittle-2      1/1       Running   0          26s       192.168.200.217   ip-172-30-6-246.ec2.internal
```

The issue comes whenever you trigger a rolling update:

```bash
kubectl --namespace=ss-test patch statefulset ss-tester -p \
  "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
kubectl --namespace=ss-test patch statefulset ss-tester-brittle -p \
  "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
```

If you watch the pods you will see that the set with the trivial initContainer is still working. While the brittle one which re-labels pods will have all/some failed pods.

```
# kubectl --namespace=ss-test get po -o wide
NAME                     READY     STATUS             RESTARTS   AGE       IP                NODE
nginx-4217019353-0b266   1/1       Running            0          7m        192.168.144.157   ip-172-30-6-62.ec2.internal
ss-tester-0              1/1       Running            0          4m        192.168.124.247   ip-172-30-6-234.ec2.internal
ss-tester-1              1/1       Running            0          4m        192.168.144.167   ip-172-30-6-62.ec2.internal
ss-tester-2              1/1       Running            0          4m        192.168.182.236   ip-172-30-6-94.ec2.internal
ss-tester-brittle-0      1/1       Running            0          4m        192.168.182.237   ip-172-30-6-94.ec2.internal
ss-tester-brittle-1      0/1       CrashLoopBackOff   5          4m        192.168.124.246   ip-172-30-6-234.ec2.internal
ss-tester-brittle-2      0/1       CrashLoopBackOff   5          4m        192.168.200.219   ip-172-30-6-246.ec2.internal
```

You can fix the set by scaling down to 0 and back up but that isn't really a solution.

I realize that this is an edge case. But the underlying issue may be causing other problems that have yet to be reported or discovered.

## Your Environment

- Kubernetes 1.7.3
- Calico 2.5.1

**Comment by caseydavenport** [comment]
@carsonoid thanks for raising. 

I think the issue you're hitting actually has to do with the fact that your init container labels the pod, which causes the policy-controller to inadvertently overwrite some important metadata used by the CNI plugin.  The rolling update on a statefulset then puts the CNI plugin in a situation where it accidentally deletes the workloadendpoint for the running pod.

I've seen this sort of error in a few issues recently, all stemming from this discussion: https://github.com/projectcalico/libcalico/issues/189

Luckily, Calico v2.6.0 should be released today which includes a fix for this issue. Could you try to reproduce with v2.6.0 when it's available and report back if it fixes your case?

**Comment by carsonoid** [comment]
@caseydavenport Sure thing! I can't do it today but I should have time tomorrow to upgrade and re-test.

**Comment by heschlie** [comment]
@carsonoid were you able to verify if you Calico v2.6.0 fixed the issue you were seeing?

**Comment by carsonoid** [comment]
@heschlie Yes, sorry, After upgrading to calico v2.6.0 we are able to reliably use statefulsets.
