### ISSUE TITLE
Pended test leaks a veth and route

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/cni-plugin#428]
`Create a container then send another ADD for the same container but with a different interface` test leaks a veth and route, which causes flakes if other tests try to use the same IP.

I've pended the test while I diagnose and fix.

## Expected Behavior

No leak.
## Current Behavior

veth and route are left over.  It's not clear if that's a test bug or a code bug.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* CNI config:
* Operating System and version:
* Link to your project (optional):

**Comment by bcreane** [comment]
@fasaxc , @caseydavenport - is this a v3.0.0 blocker or can we retarget to v3.0.1?

**Comment by fasaxc** [comment]
I think it can be v3.0.1
