### ISSUE TITLE
kube-proxy not working with calico on kubeadm 

### ISSUE THREAD

**Issue by MackJM** [projectcalico/cni-plugin#434]
I've deployed a 3 node cluster using kubeadm. While using NodePort, kube-proxy doesn't forward my request to the correct node. This does work from the master itself, but not from any other machine. However, I've recreated the steps with weave and it worked.

## Expected Behavior

`curl <master ip>:<node port>` --> nginx welcome page

## Current Behavior

`curl <master ip>:<node port>` --> timeout

## Steps to Reproduce (for bugs)

1. Step up kubeadm cluster with 3 nodes (2 might work) and an untainted master
2. `kubectl run my-nginx --image=nginx  --port=80`
3. `kubectl expose deployment my-nginx --port=80 --type=NodePort`
4. `curl <master ip>:<node port>` from another machine on the network

## Context

Trying access a svc through the master ip, regardless of which node the front-end is scheduled on.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
`# /opt/cni/bin/calico -v`
`v1.11.0`

* Orchestrator version (e.g. kubernetes, mesos, rkt):
`# kubeadm version`
`kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
`# kubectl version`
`Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

* CNI config: Nothing special, fresh install

* Operating System and version: 
`# uname -r`
`3.10.0-693.5.2.el7.x86_64`
`# cat /etc/centos-release`
`CentOS Linux release 7.4.1708 (Core)`

* Link to your project (optional):

**Comment by caseydavenport** [comment]
@tmjd could this be the Docker FORWARD issue?

@MackJM could you share the version of docker you're using? I think this might have to do with Docker changing the default iptables forward action to DROP (issue [here](https://github.com/kubernetes/kubernetes/issues/40182)).

There is a fix going into the kube-proxy in v1.9 - https://github.com/kubernetes/kubernetes/pull/52569

IIRC, Weave net works around this by adding some code to set the default forward action to ACCEPT. However, I don't think that is the right call for Calico to make, since some users may want more control over that default.

**Comment by MackJM** [comment]
@caseydavenport  my pleasure.

`# docker version`
`Client:`
 `Version:      17.09.0-ce`
` API version:  1.32`
 `Go version:   go1.8.3`
` Git commit:   afdb6d4`
 `Built:        Tue Sep 26 22:41:23 2017`
` OS/Arch:      linux/amd64`

`Server:`
` Version:      17.09.0-ce`
` API version:  1.32 (minimum version 1.12)`
` Go version:   go1.8.3`
` Git commit:   afdb6d4`
` Built:        Tue Sep 26 22:42:49 2017`
` OS/Arch:      linux/amd64`
` Experimental: false`

**Comment by tobad357** [comment]
@caseydavenport until 1.9 is out is there a workaround
Any settings we can apply to iptables manually?

**Comment by fasaxc** [comment]
You could mimic the k8s v1.9 fix by applying these iptables rules on each node:
```
iptables -N accept-node-ports
iptables -A accept-node-ports -m mark --mark <kube-proxy masquerade mark> -j ACCEPT
iptables -A accept-node-ports -s <cluster CIDR> -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A accept-node-ports -d <cluster CIDR> -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -j accept-node-ports
```

Where 

- `<kube-proxy masquerade mark>` is the configured mark used by kube-proxy.  This defaults to `0x4000/0x4000`.
- `<cluster CIDR>` is a CIDR that contains all your pod IPs, as used to configure kube-proxy.

Note: if you do not currently set a cluster CIDR then it can lead to subtle problems, where kube-proxy cannot tell whether an IP is inside the cluster or outside.

**Comment by bboreham** [comment]
> Weave net works around this by adding some code to set the default forward action to ACCEPT. 

Nope.  It adds specific rules for packets leaving the Weave network and packets allowed by Kubernetes network policy.

**Comment by caseydavenport** [comment]
@bboreham thanks for the clarification!

**Comment by Zwordi** [comment]
Hi,
I got the same behavior.
1 master 3nodes, an service based on 2 pods running on two nodes.
Port are accessible from localhost:PORT from anynods but from the master it's only accessible from IPNODESPODRUNNINGONIT.

Do you think my behavior is the same with the same solution ?

Some information:

kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

/opt/cni/bin/calico -v
v1.11.2

Thanks, Zwordi

**Comment by caseydavenport** [comment]
Yeah, that sounds like it's probably the same thing. Make sure you configure `--cluster-cidr` on the kube-proxy and see if that fixes it.

**Comment by caseydavenport** [comment]
@Zwordi @MackJM did specifying `--cluster-cidr` help?

**Comment by xuchenhao001** [comment]
@caseydavenport I got the same problem too. I have checked my kube-proxy:
```bash
# kubectl describe pod kube-proxy-cxl9t -n kube-system
Name:           kube-proxy-cxl9t
Namespace:      kube-system
Node:           hy-ubuntu/10.4.20.127
Start Time:     Thu, 08 Mar 2018 20:40:52 +0800
Labels:         controller-revision-hash=3497872265
                k8s-app=kube-proxy
                pod-template-generation=1
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"DaemonSet","namespace":"kube-system","name":"kube-proxy","uid":"e78fe136-22cd-11e8-be2d-90fba61fb1ee","api...
Status:         Running
IP:             10.4.20.127
Created By:     DaemonSet/kube-proxy
Controlled By:  DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Container ID:  docker://2bfc629b4d8e836d75eb25fcc5ada567af67b1d7a9d93a20807a90cbc18648c5
    Image:         gcr.io/google_containers/kube-proxy-amd64:v1.8.4
    Image ID:      docker-pullable://gcr.io/google_containers/kube-proxy-amd64@sha256:8dce98802846d5219093f0313dcb8697a8a5d7cad647c3b71a816cf3a2b2eb2a
    Port:          <none>
    Command:
      /usr/local/bin/kube-proxy
      --kubeconfig=/var/lib/kube-proxy/kubeconfig.conf
      --cluster-cidr=33.5.0.0/16
    State:          Running
      Started:      Sat, 10 Mar 2018 16:24:48 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 08 Mar 2018 20:40:54 +0800
      Finished:     Sat, 10 Mar 2018 16:24:05 +0800
    Ready:          True
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-proxy-token-72ffm (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:  HostPath (bare host directory volume)
    Path:  /run/xtables.lock
  lib-modules:
    Type:  HostPath (bare host directory volume)
    Path:  /lib/modules
  kube-proxy-token-72ffm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-proxy-token-72ffm
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.alpha.kubernetes.io/notReady:NoExecute
                 node.alpha.kubernetes.io/unreachable:NoExecute
                 node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
Events:          <none>
```
My cluster cider is `33.5.0.0/16`. I have 1 master and 1 worker, and I cannot access my dashboard running on master from `http://<worker-ip>:<dashboard-port>`, but `http://<master-ip>:<dashboard-port>` works. 
I have working on this for several days. `iptables -L` shows that `FORWARD` policy on two nodes both are `ACCEPT`. Also I have tried to restart docker and that did nothing. However, I even don't know how to troubleshooting this problem. Can you help me?

**Comment by jfpucheu** [comment]
Hello @xuchenhao001 , Did you solve your pb ? i have the same kind of probleme using Calico .
For example impossible to use https://10.171.XX.XXX/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/ after fex minutes i get : 

Error: 'read tcp 172.12.237.64:48230->172.12.45.197:8443: read: connection reset by peer'
Trying to reach: 'https://172.12.45.193:8443/'

From my master: 

[root@kubemaster1 ~]# curl --insecure https://172.12.45.197:8443 response is OK .

if anybody find a Solution, 

I'm Testing calico 3.1 on K8S 1.8

Thanks 

Jeff

**Comment by xuchenhao001** [comment]
@jfpucheu fortunately I have solved by problem by these steps:

1. Download `calicoctl` and move it to your `PATH` (maybe `/usr/bin/`), then we need an env parameter for calicoctl: ([see here](https://docs.projectcalico.org/v3.1/usage/calicoctl/configure/etcd))
```bash
$ export ETCD_ENDPOINTS=http://10.96.232.136:6666
```

2. Check node status for both node A & node B.
In my case, node A's external IP is `9.115.76.16` and node B is `9.125.72.206`.
```bash
$ calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+------------+---------+
| PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |  INFO   |
+---------------+-------------------+-------+------------+---------+
| 172.18.0.1    | node-to-node mesh | start | 2018-03-19 | Connect |
| 9.123.153.247 | node-to-node mesh | start | 2018-03-19 | Connect |
+---------------+-------------------+-------+------------+---------+

IPv6 BGP status
No IPv6 peers found.
```
It is wrong.
In calico network, when we check node status on node A(`9.115.76.16`), we must see node B's IP (`9.125.72.206`).
Here is the target node status from node A:
```bash
$ calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 9.125.72.206 | node-to-node mesh | up    | 08:32:21 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```
target node status from node B:
```bash
$ calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 9.115.76.16  | node-to-node mesh | up    | 08:32:21 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
So we need to modify node config in calico network.
```
In calico network, calico node name is the same as the host name.
So, check calico node list and then delete the wrong node:
```bash
$ calicoctl get node
NAME
ubt1604
ubuntu
ubuntu247

$ calicoctl delete node ubuntu247
Successfully deleted 1 'Node' resource(s)

$ calicoctl get node
NAME
ubt1604
ubuntu
```
Now we check the node status on node A:
```bash
$ calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+------------+---------+
| PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |  INFO   |
+---------------+-------------------+-------+------------+---------+
| 172.18.0.1    | node-to-node mesh | start | 2018-03-19 | Connect |
+---------------+-------------------+-------+------------+---------+

IPv6 BGP status
No IPv6 peers found.
```
See that the wrong node is deleted.
But the node B's IP (`ubt1604`) is still wrong, we need to modify it:
```
$ calicoctl get node ubt1604 -o yaml
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  creationTimestamp: 2018-03-06T04:29:11Z
  name: ubt1604
  resourceVersion: "32896"
  uid: eb13a7b8-20f6-11e8-882c-020000f48963
spec:
  bgp:
    ipv4Address: 172.18.0.1/16
    ipv4IPIPTunnelAddr: 76.16.13.64


# Now reconfigure the node with updated ipv4Address to include the correct
# subnet.
$ calicoctl apply -f - << EOF
- apiVersion: projectcalico.org/v3
  kind: Node
  metadata:
    name: ubt1604
  spec:
    bgp:
      ipv4Address: 9.125.72.206/24
      ipv4IPIPTunnelAddr: 76.16.13.64
EOF
```
Then you will see the IP through `$ calicoctl node status` is correct.
Then check the node status on your node B.
In my case, after doing this, my calicoctl network works well.
Hope this can help you!

**Comment by caseydavenport** [comment]
This thread seems to have gone cold, so I'm going to close for now.

Please re-open another thread if you encounter any more issues.
