### ISSUE TITLE
calico-kube-controllers ERRORs - "Failed to load workload endpoint cache, etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.96.232.136:6666: getsockopt: connection refused"

### ISSUE THREAD

**Issue by matthewmodestino** [projectcalico/cni-plugin#435]
Running k8s on AWS Ubuntu (heptio quickstart) -  1 master, 2 worker node cluster - after kube-apiserver outage (apiserver was up and down due to manifest updates) and after kubelet restart, calico-kube-controller pod is spitting errors about inability to talk to calico-etcd every 5 secs. 

`{"log":"2017-11-24 04:59:59.722 [ERROR][1] pod_controller.go 198: Failed to load workload endpoint cache, retrying in 5s error=client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.96.232.136:6666: getsockopt: connection refused\n","stream":"stderr","time":"2017-11-24T04:59:59.723274061Z"}`

Looking for guidance on how to troubleshoot/diagnose calico-kube-controller pod errors and understand how to restore. kubelet has been restarted since issue began, with no change in symptom. I have also ensured that src/dst checks are off in aws. sec groups allow all traffic between nodes. 

iptables-save shows no rules for the service ip. 

```
ubuntu@ip-10-0-7-109:~$ kubectl -n kube-system get endpoints
NAME                      ENDPOINTS                           AGE
calico-etcd               10.0.7.109:6666                     2d
kube-controller-manager   <none>                              2d
kube-dns                  192.168.254.2:53,192.168.254.2:53   2d
kube-scheduler            <none>                              2d
kubernetes-dashboard      192.168.254.1:9090                  2d
```

## Expected Behavior

Expectation is that calico-kube-controller pod can reach etcd and is not spitting constant stderr. 

## Current Behavior

Cluster seems to be surviving regardless. 

## Possible Solution

Somehow refresh calico set up?

## Steps to Reproduce (for bugs)

1. take down apiserver by editing manifest to add audit config
2.restart kubelet
3.monitor pods logging trends.

## Context

Audit is working after my changes, but need to understand why these errors have been introduced before closing up on this work. 

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v1.11.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.8.2
* CNI config:
`{
    "name": "k8s-pod-network",
    "cniVersion": "0.1.0",
    "type": "calico",
    "etcd_endpoints": "http://10.96.232.136:6666",
    "log_level": "info",
    "mtu": 1500,
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s",
         "k8s_api_root": "https://10.96.0.1:443",
         "k8s_auth_token": #REDACTED#
    },
    "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"`
* Operating System and version:
`Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial`

* Link to your project (optional):

**Comment by caseydavenport** [comment]
> iptables-save shows no rules for the service ip.

This seems to be the smoking gun. Can you check the kube-proxy on that node to see if it is healthy? I'd expect iptables rules for the etcd service IP.

**Comment by matthewmodestino** [comment]
Look like i had to use `-t nat` to see it on aws ubuntu:

`root@ip-10-0-7-109:/home/ubuntu# iptables-save -t nat | grep 10.96.232.136
-A KUBE-SERVICES -d 10.96.232.136/32 -p tcp -m comment --comment "kube-system/calico-etcd: cluster IP" -m tcp --dport 6666 -j KUBE-SVC-NTYB37XIWATNM25Y`

**Comment by tmjd** [comment]
You might want to take a look at the `KUBE-SVC-NTYB37XIWATNM25Y` chain it is jumping to, you should be able to find the endpoint IP for the etcd pod.  Kind of along the same lines you should probably look at the kube-proxy logs (something like `sudo journalctl -u kube-proxy`).

If neither of those show what the problem might be then I'd try checking connectivity from the host where calico-kube-controllers is running with `curl -L http://10.96.232.136:6666/version` and `curl -L http://10.0.7.109:6666/version` (assuming I have it right that 10.96.232.136 is the service IP for the etcd endpoint which is at 10.0.7.109), those should have the same behavior, if they behave differently then that is pointing at a problem with kube-proxy too.

Another thing to take a look at would be the logs from the `calico-etcd` pod, TBH though I've never seen a problem with the pod. If it has been restarted there is the possibility of corruption and it being broke.

**Comment by matthewmodestino** [comment]
nada in the kube-proxy logs, they look clean. calico-etcd hasnt said much since it came up, but looks clean. 

curls directly from the host looking good:
```ubuntu@ip-10-0-7-109:~$ curl -L http://10.0.7.109:6666/version
{"etcdserver":"3.1.10","etcdcluster":"3.1.0"}ubuntu@ip-10-0-7-109:```

```ubuntu@ip-10-0-7-109:~$ curl -L http://10.96.232.136:6666/version
{"etcdserver":"3.1.10","etcdcluster":"3.1.0"}ubuntu@ip-10-0-7-109:~$ ```

trying make sense and follow these rules thru the chain...

**Comment by tmjd** [comment]
Have you made any progress with this?  I'm reviewing it again and not sure what to try next except to exec into the calico-kube-controllers and try doing those curls again (may have to use wget).
If those both work from inside the pod I'd suggest doing a `kubectl -n kube-system delete pod <calico-kube-controllers-pod>` so it gets restarted.

If one (or both) of the curls from inside the pod fails I'd probably break out `tcpdump` and `iptables-save -c` to find out where the connection is getting dropped.

**Comment by matthewmodestino** [comment]
Hey @tmjd!

So far the cluster is operational, but I will definitely try jumping into the pod and running the curls/gets, and worse case blowing away the pod. 

Its part of my demo enviro im using at kubecon this week so I’ll probably not touch it till after ;), Or better yet if y’all are in Austin we can have a look togeher lol

**Comment by caseydavenport** [comment]
@matthewmodestino I'm here in Austin, so feel free to stop by!

DM me on Slack @caseydavenport if you'd like to say hi :)

**Comment by matthewmodestino** [comment]
Hey @caseydavenport, sorry I missed you at Kubecon! Was a whirlwind!

@tmjd wgets below. am i doing this right?

```
/ # wget http://10.0.7.109:6666/version
Connecting to 10.0.7.109:6666 (10.0.7.109:6666)
version              100% |*****************************************************************************************************************************************************|    45   0:00:00 ETA
/ # 


/ # wget http://10.96.232.136:6666/version
Connecting to 10.96.232.136:6666 (10.96.232.136:6666)
wget: can't open 'version': File exists
```

Going to blow away the pod now. If it returns will break out tcpdump.

**Comment by kiman223** [comment]
thanks a lot. I've solved the problem too!
