### ISSUE TITLE
Race? CNI plugin releases IP before removing interface

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/cni-plugin#455]
This, in k8s.go, looks wrong to me.  I think we should remove the interface first, and then free the IP. 
 Otherwise, another instance could claim the IP before we've actually removed it (and if we die before removing it, we'll let two interfaces share an IP.:
```
	// Release the IP address by calling the configured IPAM plugin.
	ipamErr := utils.CleanUpIPAM(conf, args, logger)

	// Clean up namespace by removing the interfaces.
	err = utils.CleanUpNamespace(args, logger)
	if err != nil {
		return err
	}
```
## Expected Behavior

Remove the IP first, then release the allocation.

## Current Behavior

Release then remove.

## Possible Solution

Swap the order?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): 
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* CNI config:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Yeah, I think switching the order here would be good, and should be a pretty straightforward change.

**Comment by akhilesh2410** [comment]
@fasaxc : I can help you on this, if you want.

**Comment by caseydavenport** [comment]
I think this has actually been fixed here: https://github.com/projectcalico/cni-plugin/pull/746
