### ISSUE TITLE
CNI plugin always stores WEP with name eth0, even if called with different name

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/cni-plugin#456]
While fixing up a test under #452, I came across this rather icky behaviour.  If the CNI plugin is called with an interface name other than eth0, we still call the WEP "eth0", but we _do_ honour the name when creating the veth.  Seems like those two should be in sync.

## Expected Behavior

WEP name and veth name should agree.

## Current Behavior

WEP name always eth0, 

## Possible Solution

Use the iface name in the WEP name and in the IPAM handle.  That should give us multi-interface support too.  I guess the question is whether it would also cause problems elsewhere!?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* CNI config:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Yeah, should be an easy fix if anyone is interested in contributing!

**Comment by caseydavenport** [comment]
@fasaxc was this fixed? I can't seem to find the code that's hard-coding this.

**Comment by ozdanborne** [comment]
ping @fasaxc , any idea?
