### ISSUE TITLE
TLS secrets readable by all users after copy to host

### ISSUE THREAD

**Issue by hafe** [projectcalico/cni-plugin#459]
Provided etcd TLS secrets are readable by all users on the host after the CNI plugin has executed. This has security implications, depending if the etcd cluster is shared and/or RBAC is enabled the credentials could means indirect K8S cluster admin access.

## Expected Behavior
TLS secrets should have "-r--r-----" or "-r-----" mode.

## Current Behavior
File after copy has "-rw-r--r--" mode.

## Possible Solution
Instead of using cp in the install script, install can be used where mode can be specified as an option.

## Steps to Reproduce (for bugs)

1. deploy kubernetes and calico as CNI
2.
3.
4.

## Context
Unintentional sec audit after k8s+calico installation

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): 2.6.5 (problem exist in master)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* CNI config:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@hafe yeah. would be great to do this, and should be an easy fix somewhere around here: https://github.com/projectcalico/cni-plugin/blob/master/k8s-install/scripts/install-cni.sh#L26-L33

Anyone interested in submitting a PR?

**Comment by caseydavenport** [comment]
Looks like we should be setting permissions, since k8s defaults to 0644: https://kubernetes.io/docs/concepts/configuration/secret/

Then, we just need to use `cp -p` to make sure permissions are transferred as well. I've done that as part of this PR: https://github.com/projectcalico/cni-plugin/pull/481
