### ISSUE TITLE
cannot unmarshal bool into Go struct field .assign_ipv4 of type string

### ISSUE THREAD

**Issue by valentin2105** [projectcalico/cni-plugin#461]
The CNI plugin seem to fail to fetch the config in 10-calico.conf file. 

## Expected Behavior
Assign pod with IP from the IPPools. 

## Current Behavior
The pod is not scheduled and block with this error : 
```
Error syncing pod 9b24470b-0489-11e8-a3bb-2ea73ef3f6db ("toolbox-5b4c9d799d-d2v5h_default(9b24470b-0489-11e8-a3bb-2ea73ef3f6db)"), skipping: failed to 

"CreatePodSandbox" for "toolbox-5b4c9d799d-d2v5h_default(9b24470b-0489-11e8-a3bb-2ea73ef3f6db)" with CreatePodSandboxError: "CreatePodSandbox for pod \"toolbox-5b4c9d799d-d2v5h_default(9b24470b-0489-11e8-a3bb-2ea73ef3f6db)\"

failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"\": 

failed to load netconf: json: cannot unmarshal bool into Go struct field .assign_ipv4 of type string"
```

## Your Environment
* CNI plugin version : v2.0.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.9.2
* CNI config: 

```
{
  "name": "calico-k8s-network",
  "type": "calico",
  "datastore_type": "etcdv3",
  "etcd_endpoints": "https://k8s-master:2379",
  "etcd_key_file": "/var/lib/kubernetes/kubernetes-key.pem",
  "etcd_cert_file": "/var/lib/kubernetes/kubernetes.pem",
  "etcd_ca_cert_file": "/var/lib/kubernetes/ca.pem",
  "ipam": {
    "type": "calico-ipam",
    "assign_ipv4": "true",
    "assign_ipv6": "true"
  },
  "policy": {
    "type": "k8s"
  },
  "kubernetes": {
    "kubeconfig": "/etc/calico/kube/kubeconfig"
  }
}
```

* Operating System and version: Debian 9.1

**Comment by fasaxc** [comment]
@valentin2105 did you start with ```
  "ipam": {
    "type": "calico-ipam",
    "assign_ipv4": true,
    "assign_ipv6": true
  },
```
and then change to 
```
  "ipam": {
    "type": "calico-ipam",
    "assign_ipv4": "true",
    "assign_ipv6": "true"
  },
```
I'm wondering if you need to restart kubelet to pick up that change.

**Comment by gunjan5** [comment]
I think kubelete reads this config fresh everytime it calls it and doesn't cache it, so changing it should take effect at the next call to the CNI plugin. 

@valentin2105 can you turn up the logging in the CNI config to debug and paste the debug logs? 
Just need to add `"log_level": "debug",` to the config

**Comment by caseydavenport** [comment]
On a related note, it might be worth us adding some trickery to support both boolean and string values (for compat) here so it's not so confusing and hard to get right...

**Comment by valentin2105** [comment]
Hey, thanks for your answers, 

With `"log_level": "debug"`, there is no more logs : 

```
pod_workers.go:186] Error syncing pod 71b0caee-06c8-11e8-9c23-2ea73ef3f6db ("toolbox-5b4c9d799d-5b569_default(71b0caee-06c8-11e8-9c23-2ea73ef3f6db)"),
 skipping: failed to "CreatePodSandbox" for "toolbox-5b4c9d799d-5b569_default(71b0caee-06c8-11e8-9c23-2ea73ef3f6db)" with CreatePodSandboxError: "CreatePodSandbox for pod \"toolbox-5b4c9d799d-5b569_default(71b0caee-06c8-11e8-9c23-2ea73ef3f6db)\" 

failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"a952f9491161c55ab422568ffcf168153f3b3d9b57d6997f27e433ac51a62039\":

 failed to load netconf: json: cannot unmarshal bool into Go struct field .assign_ipv4 of type string"
```

I have tried to use `"true"` and `true` while restarting kubelet, 
Same effect.

**Comment by valentin2105** [comment]
I have deleted all my ETCD ressources, and restart from scratch with `"true"` and it work as expected. Maybe Calico put the config in ETCD and can't change the type on variable ?
