### ISSUE TITLE
kubectl port-forward is blocked by Calico rule

### ISSUE THREAD

**Issue by nbosscher** [projectcalico/cni-plugin#462]
I'm not sure if this is the right place to be posting this, if not please point me where to go.

## Expected Behavior
```
$ curl <my-docker-registry-pod-ip>:5000 -v
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Date: Tue, 30 Jan 2018 15:38:50 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host <my-docker-registry-pod-ip> left intact
$ kubectl port-forward my-docker-registry-pod 5000:5000
$ curl localhost:5000 -v
<some-output>
```

## Current Behavior
```
$ curl <my-docker-registry-pod-ip>:5000 -v
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Date: Tue, 30 Jan 2018 15:38:50 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host <my-docker-registry-pod-ip> left intact
$ kubectl port-forward my-pod 5000:5000
$ curl localhost:5000 -v
curl: (7) Failed connect to localhost:5000; Connection refused
```
## Possible Solution
In my very limited knowledge of the inner workings of Calico, I think it has to do with the last iptables rule in this chain.
```
Chain cali-INPUT (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* cali:i7okJZpS8VxaJB3n */ mark match 0x1000000/0x1000000
ACCEPT     ipv4 --  anywhere             anywhere             /* cali:kLJdl8-9MpSKcclh */ /* Allow IPIP packets from Calico hosts */ match-set cali4-all-hosts src ADDRTYPE match dst-type LOCAL
DROP       ipv4 --  anywhere             anywhere             /* cali:JhfQUFFJ2v0jbipF */ /* Drop IPIP packets from non-Calico hosts */ <---- this one
```

## Steps to Reproduce (for bugs)
1. Using steps verbatim from [https://docs.projectcalico.org/v3.0/getting-started/kubernetes/](https://docs.projectcalico.org/v3.0/getting-started/kubernetes/)
2. Setup docker registry using [https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry)
3. `docker <my-image> localhost:5000/<my-image>`
4. `docker push localhost:5000/<my-image>`

## Context
I'm trying to push docker image to a private docker registry in my kubernetes cluster from a host machine. 
- Docker only allows `localhost` name prefixes for private registries. 
- This can be achieved using kubectl port-forward

I have this working on another kubernetes environment that doesn't use Calico

## Your Environment
* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v2.0.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): `Client:v1.9.2` `Server:v1.9.2`
* CNI config:
```
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "etcd_endpoints": "__ETCD_ENDPOINTS__",
      "log_level": "info",
      "mtu": 1500,
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s",
           "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
           "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
```
* Operating System and version: `Centos 7`

**Comment by caseydavenport** [comment]
@nbosscher one way to check which rules are dropping the traffic would be to use `iptables-save` to view packet counters.


1. Clear the counters - `iptables -Z`
2. Run the command to generate traffic
3. Check which drop rules are getting hit: `iptables-save -c | grep DROP`

**Comment by nbosscher** [comment]
Thanks @caseydavenport. Just this morning I've abandoned this, as I couldn't get this configured before a deadline. I was unable to rectify this issue and I also ran into issues with calico when trying to reload iptables after reboot.
