### ISSUE TITLE
latest Calico CNI give a IPv4 whatever we do (assign_ipv4: "false")

### ISSUE THREAD

**Issue by valentin2105** [projectcalico/cni-plugin#463]
Hi,

I'm currently building my new IPv6-only cluster w/ Calico3 & k8s 1.9.x
 (the latest was Calico2/k8s1.8)

Here is my CNI-config file : 
```
{
    "name": "calico-k8s-network",
    "type": "calico",
    "datastore_type": "etcdv3",
    "etcd_endpoints": "https://candy.domain.tld:2379",
    "etcd_key_file": "/var/lib/kubernetes/kubernetes-key.pem",
    "etcd_cert_file": "/var/lib/kubernetes/kubernetes.pem",
    "etcd_ca_cert_file": "/var/lib/kubernetes/ca.pem",
    "log_level": "debug", 
    "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "false",
        "assign_ipv6": "true"
    },
    "policy": {
        "type": "k8s"
    },
    "kubernetes": {
        "kubeconfig": "/etc/calico/kube/kubeconfig"
    }
}
```

My IPPools : 

```
root@caesar:~# calicoctl get ippool
NAME                  CIDR
default-ipv4-ippool   192.168.0.0/16
default-ipv6-ippool   1404:f200:ff:ff::/64
```

When I deploy a pod : 

```
NAMESPACE     NAME                                      READY     STATUS    RESTARTS   AGE       IP                                  NODE
default       toolbox-5b4c9d799d-5c2h6                  1/1       Running   1          12m       192.168.237.193                     caesar.domain.tld
```

Each pod are scheduled with an IP from 192.168.0.0/16 IPPool without take care of `"assign_ipv4": "false"`. 

This bug make Calico 3.0 not useable for IPv6-only counter to Calico 2.0.

Any idea what going on ? 

**EDIT :** 

After a while, I'm able to get a pod without IPv4, but it got killed by k8s with a lot of error like that in the kubelet logs : 

```
failed to get IP addresses for "eth0": <nil>
 Sandbox for pod "toolbox-5b4c9d799d-s4fzq_default(b1e78e65-06e3-11e8-bb70-a2d5171170a0)" has no IP address.  Need to start a new one


default       toolbox-5b4c9d799d-s4fzq                  0/1       Error     0
```

It seem to be a k8s regression that doesn't show the IPv6 and think the pod doesn't get an IP ? 

I opened this issue too : https://github.com/kubernetes/kubernetes/issues/59160
@caseydavenport  @gunjan5  @fasaxc 

Thanks !

**Comment by valentin2105** [comment]
Found the issue, it's on Cri-Containerd side.

**Comment by gunjan5** [comment]
@valentin2105 curious, what was the issue with CRI-Containerd? Is there a bug/issue link?

**Comment by valentin2105** [comment]
I don't find the cause, but with Docker it work at glance !    
https://github.com/containerd/cri-containerd/issues/580
