### ISSUE TITLE
Add tuning plugin

### ISSUE THREAD

**Issue by eranreshef** [projectcalico/cni-plugin#517]
## Expected Behavior
Calico cni should include the `tuning` plugin

## Current Behavior
The tuning cni plugin is a lite and useful addition, and it exists in flannel's cni plugin.

## Context
I wanted to increase the `net.core.somaxconn` parameter in my cluster and I found a very easy way to do so using the [tuning plugin](https://github.com/containernetworking/plugins/tree/master/plugins/meta/tuning). Unfortunately, the plugin is missing in calico's cni.

**Comment by eranreshef** [comment]
What does a guy need to do here in order to get write permissions to the repo?

**Comment by ozdanborne** [comment]
We accept contributions by pull request, if that's what you mean.

**Comment by eranreshef** [comment]
https://github.com/projectcalico/cni-plugin/pull/519

**Comment by eranreshef** [comment]
#519
