### ISSUE TITLE
Race condition: docker rm loses IP allocations

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/cni-plugin#520]
Saw this when playing around with `docker rm` commands. Deleting the sandbox container managed to end up in a state where two pods had IP addresses, but the host-local plugin wasn't aware of the allocations.

i.e.

```
$ ip route
default via 10.128.0.1 dev ens4 
10.128.0.1 dev ens4  scope link 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
192.168.0.0/24 via 10.128.0.34 dev tunl0  proto bird onlink 
192.168.1.0/24 via 10.128.0.36 dev tunl0  proto bird onlink 
blackhole 192.168.2.0/24  proto bird 
192.168.2.2 dev cali7f038ce39ed  scope link 
192.168.2.3 dev calie3a7f661282  scope link
```

```
$ ls /var/lib/cni/networks/k8s-pod-network/
192.168.2.3  last_reserved_ip.0
```
## Expected Behavior

The number of allocated IPs should always match the number of running pods. 

## Possible Solution

My guess is that this is the bit of code that's not behaving properly - https://github.com/projectcalico/cni-plugin/blob/master/k8s/k8s.go#L62-L73

I think it needs to release and re-allocate the IP address for that pod. Otherwise the IP is still attached to the old container ID and will eventually be GC'd. 

This likely applies to Calico IPAM too as of this change: https://github.com/projectcalico/cni-plugin/pull/445 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* CNI config:
* Operating System and version:
* Link to your project (optional):

**Comment by calixwu** [comment]
I don't understand why this would happen with the codes below:

```
if endpointAlreadyExisted {
		// This happens when Docker or the node restarts. K8s calls CNI with the same parameters as before.
		// Do the networking (since the network namespace was destroyed and recreated).
		// There's an existing endpoint - no need to create another. Find the IP address from the endpoint
		// and use that in the response.
		result, err = utils.CreateResultFromEndpoint(endpoint)
		if err != nil {
			return nil, err
		}
		logger.WithField("result", result).Debug("Created result from existing endpoint")
		// If any labels changed whilst the container was being restarted, they will be picked up by the policy
		// controller so there's no need to update the labels here.
	} 
```

Even though we play around with docker rm command, delete the sandbox container, it will use the same IP. Why would it end up with too IP addresses??
