### ISSUE TITLE
not able to ping  pods over calico networks

### ISSUE THREAD

**Issue by nik786** [projectcalico/cni-plugin#524]
Pods are not pinging b/w each other over calico network
## Expected Behavior
Pinging should happen b/w each other
## Current Behavior
Pods are nt pinging across nodes

## Context
Trying to setup kubernetes 1.10 cluster over calico 3.0

## Your Environment

./calico -v
v3.1.1

./calicoctl version
Client Version:    v3.1.1

./calico-ipam -v
v3.1.1

cni version is 0.30.0

/opt/bin/etcdctl -version
etcdctl version: 3.0.10

/opt/bin/etcd -version
etcd Version: 3.0.10

core-1:

./calicoctl node run --ip 172.17.8.101

./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.17.8.102 | node-to-node mesh | up    | 08:26:38 | Established |
| 172.17.8.103 | node-to-node mesh | up    | 08:26:47 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

ip r
10.1.11.0/24 dev docker0 proto kernel scope link src 10.1.11.1 linkdown 
172.17.0.0/16 dev eth1 proto kernel scope link src 172.17.8.101 
192.168.174.0/26 via 172.17.8.102 dev eth1 proto bird 
192.168.210.128/26 via 172.17.8.103 dev eth1 proto bird 

route -n
10.1.11.0       0.0.0.0         255.255.255.0   U     0      0        0 docker0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth1
192.168.174.0   172.17.8.102    255.255.255.192 UG    0      0        0 eth1
192.168.210.128 172.17.8.103    255.255.255.192 UG    0      0        0 eth1

etcdctl ls /calico/v1/ipam/v4/pool/

/calico/v1/ipam/v4/pool/192.168.0.0-16

core-01 calico # kubectl get  pods --all-namespaces -o wide | grep calico
kube-system            calico-kube-controllers-6ddfbf7775-j8qkz   1/1       Running   1          15h       172.17.8.103      172.17.8.103

core2:

./calicoctl node run --ip 172.17.8.102

./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.17.8.101 | node-to-node mesh | up    | 08:26:37 | Established |
| 172.17.8.103 | node-to-node mesh | up    | 08:26:46 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

ip r

172.18.0.0/16 dev docker0 proto kernel scope link src 172.18.0.1 linkdown 
blackhole 192.168.174.0/26 proto bird 
192.168.210.128/26 via 172.17.8.103 dev eth1 proto bird 

route -n

172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.174.0   0.0.0.0         255.255.255.192 U     0      0        0 *
192.168.210.128 172.17.8.103    255.255.255.192 UG    0      0        0 eth1

core-3:
./calicoctl node run --ip 172.17.8.103

core-03 bin # ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.17.8.101 | node-to-node mesh | up    | 08:26:46 | Established |
| 172.17.8.102 | node-to-node mesh | up    | 08:26:46 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

ip r
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.174.0   172.17.8.102    255.255.255.192 UG    0      0        0 eth1
192.168.210.128 0.0.0.0         255.255.255.192 U     0      0        0 *
192.168.210.132 0.0.0.0         255.255.255.255 UH    0      0        0 cali2fcb7f3501f

route -n
192.168.174.0   172.17.8.102    255.255.255.192 UG    0      0        0 eth1
192.168.210.128 0.0.0.0         255.255.255.192 U     0      0        0 *
192.168.210.132 0.0.0.0         255.255.255.255 UH    0      0        0 cali2fcb7f3501f

kubelet service

/opt/bin/kubelet --kubeconfig=/opt/bin/kubeconfig    --address=0.0.0.0  --hostname_override=172.17.8.103  --cluster-dns=10.254.0.15  --cluster-domain=cluster.local --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --v=0

proxy service

/opt/bin/kube-proxy   --proxy-mode=iptables --master=https://172.17.8.101:6443  --v=2

core-03 system # cat /etc/cni/net.d/10-calico.conf 
{
    "name": "calico-k8s-network",
    "cniVersion": "0.3.0",
    "type": "calico",
    "etcd_endpoints": "http://127.0.0.1:2379",
    "log_level": "debug",
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s"
    },
    "kubernetes": {
        "kubeconfig": "/opt/bin/kubeconfig"
    }

}

can any one tell me how to set up pod to pod pinging across calico nodes with out flashing iptables ???

**Comment by nik786** [comment]
@tmjd 

probelm is solved now.issue may be closed
thank you

**Comment by damon4u** [comment]
same problem... please share your story @nik786

**Comment by BenChand** [comment]
Reveal your secrets @nik786

**Comment by tobi97h** [comment]
scumbag

**Comment by tobi97h** [comment]
in my case i hadnt enabled ipv4 forwarding on my machines. 

sudo nano /etc/sysctl.conf

  # Uncomment the next line to enable packet forwarding for IPv4
  net.ipv4.ip_forward=1

=> then reboot

**Comment by caseydavenport** [comment]
@tobi97h name calling or derogatory comments of any form are **not acceptable** in the Calico community. Please review the Calico [code of conduct](https://github.com/projectcalico/community/blob/master/CODE_OF_CONDUCT.md) before future posts.

I have deleted the offending comment from this thread.
