### ISSUE TITLE
Question: for the network policy part, how calico interact witch k8s-apiserver when k8s configured witch tls

### ISSUE THREAD

**Issue by peiqi-caicloud** [projectcalico/cni-plugin#533]
Hello, 

I install k8s with tls, apiserver listens on 6443. 

my /etc/cni/net.d/calico-10.conf
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_endpoints": "http://10.50.61.163:2379",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    },
    "kubernetes": {  
        "k8s_api_root": "https://10.50.61.161:6443"  
    }  
}

I am wondering how should I config the ssl key for calico so that calico can interact with apiserver for network policy ...

OR calico interact with etcd?   k8s creates some network policy, the network policy is stored in etcd and calico interacts with etcd ??? 

I am not sure how it works ...

@tomdee @bjwbell thanks for your help

**Comment by caseydavenport** [comment]
@peiqi-caicloud Calico supports using a standard kubeconfig file to configuring access to the Kubernetes API - you can specify your TLS assets in that file.

For etcd, there are options in the CNI config you can set.

**Comment by peiqi-caicloud** [comment]
thanks for your replay @caseydavenport .

could you give me an example for tls format to interact with k8s api.

like this format in your Makefile?

./Makefile:462:#	echo '{"log_level":"DEBUG","name": "k8s","type": "calico","etcd_authority": "${LOCAL_IP_ENV}:2379", "kubernetes":{"node_name":"127.0.0.1"}, "policy": {"k8s_insecure_skip_tls_verify":true,"type": "k8s", "k8s_api_root":"https://10.7.50.75:6443", "k8s_auth_token":"YcFKOZdGR2c1XagRzhT6E5dHjNlbzmO9"},"ipam": {"type": "host-local", "subnet": "usePodCidr"}}' >net.d/10-calico.conf

./Makefile:463:#	echo '{"log_level":"DEBUG","name": "k8s","type": "calico","etcd_authority": "${LOCAL_IP_ENV}:2379", "kubernetes":{"node_name":"127.0.0.1"}, "policy": {"k8s_insecure_skip_tls_verify":true,"type": "k8s", "k8s_api_root":"https://10.7.50.75:6443", "k8s_username":"admin", "k8s_password":"admin"},"ipam": {"type": "host-local", "subnet": "usePodCidr"}}' >net.d/10-calico.conf

besides, what the difference between policy struct and k8s structs, we interact with k8s apiserver only for network policy , don't  we?

 23 // Policy is a struct to hold policy config (which currently happens to also contain some K8s config)
 24 type Policy struct {
 25         PolicyType              string `json:"type"`
 26         K8sAPIRoot              string `json:"k8s_api_root"`
 27         K8sAuthToken            string `json:"k8s_auth_token"`
 28         K8sClientCertificate    string `json:"k8s_client_certificate"`
 29         K8sClientKey            string `json:"k8s_client_key"`
 30         K8sCertificateAuthority string `json:"k8s_certificate_authority"`
 31 }
 
 38 // Kubernetes a K8s specific struct to hold config
 39 type Kubernetes struct {
 40         K8sAPIRoot string `json:"k8s_api_root"`
 41         Kubeconfig string `json:"kubeconfig"`
 42         NodeName   string `json:"node_name"`
 43 }
 44

**Comment by caseydavenport** [comment]
All of the Policy sections except for "PolicyType" are essentially deprecated in favor of using a kubeconfig file, referenced through the `Kubernetes.Kubeconfig` section. PolicyType should be set to `k8s` for Kubernetes. 

Here's some info on kubeconfig files:
- https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/
- https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/
