### ISSUE TITLE
calico restart again and again

### ISSUE THREAD

**Issue by steinliber** [projectcalico/cni-plugin#534]
I use calico in kubernetes and use demonset to run it, but it restart again and again

## Expected Behavior

All calico should run normally

## Current Behavior

They just restart again and again
Here is the log

>   Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "var-run-calico"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "etcd-certs"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "cni-net-dir"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "cni-bin-dir"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "lib-modules"
  Normal   SuccessfulMountVolume  46m                kubelet, 192.168.0.37  MountVolume.SetUp succeeded for volume "calico-node-token-8wf2l"
  Normal   Pulled                 44m (x2 over 46m)  kubelet, 192.168.0.37  Container image "calico/cni:v2.0.3" already present on machine
  Normal   Started                44m (x2 over 46m)  kubelet, 192.168.0.37  Started container
  Normal   Created                44m (x2 over 46m)  kubelet, 192.168.0.37  Created container
  Normal   Started                44m (x2 over 46m)  kubelet, 192.168.0.37  Started container
  Normal   Killing                40m (x2 over 44m)  kubelet, 192.168.0.37  Killing container with id docker://calico-node:Need to kill Pod
  Normal   Created                40m (x3 over 46m)  kubelet, 192.168.0.37  Created container
  Normal   Pulled                 40m (x3 over 46m)  kubelet, 192.168.0.37  Container image "calico/node:v3.0.4" already present on machine
  Normal   Killing                40m (x2 over 44m)  kubelet, 192.168.0.37  Killing container with id docker://install-cni:Need to kill Pod
  Normal   SandboxChanged         19m (x8 over 44m)  kubelet, 192.168.0.37  Pod sandbox changed, it will be killed and re-created.
  Warning  BackOff                6m (x48 over 16m)  kubelet, 192.168.0.37  Back-off restarting failed container
  Warning  BackOff                1m (x85 over 19m)  kubelet, 192.168.0.37  Back-off restarting failed container

## Steps to Reproduce (for bugs)

1. use host network version

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): calico3.0.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes1.9 docker
* CNI config:
* Operating System and version: 
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@steinliber could you provide the logs from the Calico pod so we can see why it's getting restarted?

e.g.

```
kubectl logs -p -n kube-system <failing-pod-name>
```
