### ISSUE TITLE
quay.io/calico/cni:v3.1.3 startup failure

### ISSUE THREAD

**Issue by jesse1993** [projectcalico/cni-plugin#560]
## Current Behavior
the cni plugin container logs:
[root@worker2 ~]# docker logs f17ad1ffaa66
ls: /calico-secrets: No such file or directory
Wrote Calico CNI binaries to /host/opt/cni/bin
CNI plugin version: v3.1.3
/host/secondary-bin-dir is non-writeable, skipping
cat: can't open '/var/run/secrets/kubernetes.io/serviceaccount/token': No such file or directory

## Steps to Reproduce (for bugs)

1.kubectl apply -f \
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
quay.io/calico/cni:v3.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes1.8.3
* CNI config:
* Operating System and version:
centos7
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@jesse1993 do you have serviceaccount token creation enabled on your cluster? 

e.g. does `kubectl get secrets -n kube-system` show a token for the Calico service accounts?

**Comment by jesse1993** [comment]
sorry for my late response, i tried changing the config as per your suggestion, but i got the same error
`[root@master1 ~]# kubectl --server 172.18.11.249:8080 get secrets -n kube-system`
NAME TYPE DATA AGE
calico-cni-plugin-token-54mt2 kubernetes.io/service-account-token 2 2m
calico-kube-controllers-token-qpzh8 kubernetes.io/service-account-token 2 2m
default-token-9jmhg kubernetes.io/service-account-token 2 21m

**error log:**
ls: /calico-secrets: No such file or directory
Wrote Calico CNI binaries to /host/opt/cni/bin
CNI plugin version: v3.1.3
/host/secondary-bin-dir is non-writeable, skipping
cat: can't open '/var/run/secrets/kubernetes.io/serviceaccount/token': No such file or directory

**Comment by tmjd** [comment]
Since this is a dup I'm closing it.  Please let me know if it should remain open and I can reopen.
