### ISSUE TITLE
Add interfaces field in result of adding new device

### ISSUE THREAD

**Issue by GhostComputing** [projectcalico/cni-plugin#593]
Add `interfaces` field in result of adding new device.

## Expected Behavior

After adding new device, cni-plugin will response the result with `interfaces` field.

## Current Behavior

According to [cni 0.3.0 spec](https://github.com/containernetworking/cni/blob/spec-v0.3.0/SPEC.md), the format of result when add new device is shown below:

```
{
  "cniVersion": "0.3.0",
  "interfaces": [                                            (this key omitted by IPAM plugins)
      {
          "name": "<name>",
          "mac": "<MAC address>",                            (required if L2 addresses are meaningful)
          "sandbox": "<netns path or hypervisor identifier>" (required for container/hypervisor interfaces, empty/omitted for host interfaces)
      }
  ],
  "ip": [
      {
          "version": "<4-or-6>",
          "address": "<ip-and-prefix-in-CIDR>",
          "gateway": "<ip-address-of-the-gateway>",          (optional)
          "interface": <numeric index into 'interfaces' list>
      },
      ...
  ],
  "routes": [                                                (optional)
      {
          "dst": "<ip-and-prefix-in-cidr>",
          "gw": "<ip-of-next-hop>"                           (optional)
      },
      ...
  ]
  "dns": {
    "nameservers": <list-of-nameservers>                     (optional)
    "domain": <name-of-local-domain>                         (optional)
    "search": <list-of-additional-search-domains>            (optional)
    "options": <list-of-options>                             (optional)
  }
}
```
I found cni-plugin don't return `interfaces` field after adding new device. If I want to use [bandwidth plugin](https://github.com/containernetworking/plugins/blob/master/plugins/meta/bandwidth/main.go#L170), it needs the `interfaces` field from last plugin (calico), otherwise bandwidth plugin cannot work.

Although I use v1.9.1, I found the master also don't return the field.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
   **v1.9.1**
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* CNI config:
* Operating System and version:
  **Ubuntu 16.04**
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Sounds reasonable to me!
