### ISSUE TITLE
"the given pool does not exist, or is not enabled" / "no configured Calico pools" when creating pods with assign_ipv6 set to "true"

### ISSUE THREAD

**Issue by teran-mckinney** [projectcalico/cni-plugin#598]
## Expected Behavior

Should be able to assign IPv6 addresses to pods when ipPool exists.

## Current Behavior
Pod fails to start. If ipv6_pools is set, says "the given pool does not exist, or is not enabled". If ipv6_pools is not set, it says: "no configured Calico pools".

IPv4 only does not cause this problem, IPv4 ipPools are fine.

```network for pod "busybox2": NetworkPlugin cni failed to set up pod "busybox2_default" network: the given pool (2001:19f0:5001:2b34::/64) does not exist, or is not enabled
root@calico-master:~# calicoctl get ippools -o wide
NAME           CIDR                       NAT     IPIPMODE   DISABLED  
local-range    2001:19f0:5001:2b34::/64   false   Never      false      
local-range4   192.168.0.0/16             true    Never      false
```

## Steps to Reproduce (for bugs)
1. Create Kubernetes cluster.
2. Configure IPv4 and IPv6 ip pools.
3. Restart kubelet to load configuration.
4. Launch pod.

## Context
Hoping to run dualstack Kubernetes pods.

## Your Environment
* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): 3.2.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.11.3
* CNI config: assign_ipv4 and assign_ipv6 are true, pretty stock otherwise.
* Operating System and version: Ubuntu 16.04

**Comment by neiljerram** [comment]
@tmjd Wonder if you have any immediate ideas (or questions) about this, as I think you looked quite recently at IPv6.

**Comment by teran-mckinney** [comment]
Issue was that I set calicoctl to the wrong etcd. Maybe there would be a way calicoctl could warn you if it's not connected to one with existing entries?

Anyway, thank you! I appreciate your time. Was able to spin up a dual stack pod, although host is not answering for it in ICMPv6 requests looking for a mac to associate with the IPv6 address. Will keep digging.
