### ISSUE TITLE
Can calico setup IPv4 address on host veth ?

### ISSUE THREAD

**Issue by GhostComputing** [projectcalico/cni-plugin#602]
Can calico setup IPv4 address on host veth ?

## Expected Behavior

Setup IPv4 address on creating host veth.

## Current Behavior

In my scenario, we use dnsmasq on host machine to cache DNS query.  If the container on such host make DNS query, it will query dnsmasq service on localhost directly for performance. When the DNS response body is too large, the DNS query will change to TCP mode.  When dnsmasq working in TCP mode, it will check whether virtual network (which is host veth) is legal or not through netlink interface. If the host veth don't setup IPv4 address, dnsmasq will refuse the DNS query.

## Possible Solution

I think setup the IPv4 address on host veth is OK (same as container side).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
v1.9.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
v1.9.2
* CNI config:
* Operating System and version:
CentOS
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I don't think we can assign an IP address to the host-side veth interface. If we do that, traffic destined to processes within the container will not reach the process.

We could put a _different_ address on the host-side, but then I'm not sure if that fixes your scenario, and it means we waste half the IP space. 

Why is dnsmasq refusing to accept queries in this scenario? I'm not sure I understand why that is the right behavior.

**Comment by GhostComputing** [comment]
@caseydavenport It's default behavior of dnsmasq. 

You can check the following logic in [dnsmasq code](http://www.thekelleys.org.uk/dnsmasq/):

```c
// in dnsmasq 2.66 network.c:

static int iface_allowed_v4(struct in_addr local,
                            int if_index,
                            struct in_addr netmask,
                            struct in_addr broadcast,
                            void* vparam) {
  union mysockaddr addr;

  memset(&addr, 0, sizeof(addr));
#ifdef HAVE_SOCKADDR_SA_LEN
  addr.in.sin_len = sizeof(addr.in);
#endif
  addr.in.sin_family = AF_INET;
  addr.in.sin_addr = broadcast; /* warning */
  addr.in.sin_addr = local;
  addr.in.sin_port = htons(daemon->port);

  return iface_allowed((struct irec**)vparam, if_index, &addr, netmask, 0);
}
```

If we use [`--bind-dynamic`](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html)(it's default setting on Linux), the dnsmasq will only check IPv4 interface, which it cannot see `cali*`. For resolving the question, we change to use `--bind-interface` option.
