### ISSUE TITLE
fail to build cni-plugin with release-3.2

### ISSUE THREAD

**Issue by pencc** [projectcalico/cni-plugin#616]
I try to build calico(release-3.2), but it failed.

1) follows logs:

[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/beorn7/perks 3a771d992973f24aa725d07868b467d1ddfceafb!
[INFO]	--> Found desired version locally github.com/coreos/go-iptables 259c8e6a4275d497442c721fa52204d7a58bde8b!
[INFO]	--> Found desired version locally github.com/davecgh/go-spew 782f4967f2dc4564575ca782fe2d04090b5faca8!
[INFO]	--> Found desired version locally github.com/dgrijalva/jwt-go 01aeca54ebda6e0fbfafd0a524d234159c05ec20!
[INFO]	--> Found desired version locally github.com/ghodss/yaml 73d445a93680fa1a78ae23a5839bad48f32ba1ee!
[INFO]	--> Found desired version locally github.com/golang/glog 44145f04b68cf362d9c4df2182967c2275eaefed!
[INFO]	--> Found desired version locally github.com/google/btree 7d79101e329e5a3adf994758c578dab82b90c017!
[INFO]	--> Found desired version locally github.com/google/gofuzz 44d81051d367757e1c7c6a5a86423ece9afcf63c!
[INFO]	--> Found desired version locally github.com/gregjones/httpcache 787624de3eb7bd915c329cba748687a3b22666a6!
[INFO]	--> Found desired version locally github.com/hashicorp/golang-lru a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4!
[INFO]	--> Found desired version locally github.com/imdario/mergo 6633656539c1639d9d78127b7d47c622b5d7b6dc!
[INFO]	--> Found desired version locally github.com/kelseyhightower/envconfig dd1402a4d99de9ac2f396cd6fcb957bc2c695ec1!
[INFO]	--> Found desired version locally github.com/matttproud/golang_protobuf_extensions c12348ce28de40eed0136aa2b644d0ee0650e56c!
[INFO]	--> Found desired version locally github.com/mcuadros/go-version 6d5863ca60fa6fe914b5fd43ed8533d7567c5b0b!
[INFO]	--> Found desired version locally github.com/modern-go/concurrent bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94!
[INFO]	--> Found desired version locally github.com/modern-go/reflect2 05fbef0ca5da472bbf96c9322b84a53edc03c9fd!
[INFO]	--> Found desired version locally github.com/pborman/uuid ca53cad383cad2479bbba7f7a1a05797ec1386e4!
[INFO]	--> Found desired version locally github.com/peterbourgon/diskv 5f041e8faa004a95c88a202771f4cc3e991971e6!
[INFO]	--> Found desired version locally github.com/projectcalico/go-json 6219dc7339ba20ee4c57df0a8baac62317d19cb1!
[INFO]	--> Found desired version locally github.com/projectcalico/go-yaml-wrapper 598e54215bee41a19677faa4f0c32acd2a87eb56!
[INFO]	--> Found desired version locally github.com/prometheus/client_model 5c3871d89910bfb32f5fcab2aa4b9ec68e65a99f!
[INFO]	--> Found desired version locally github.com/prometheus/common c7de2306084e37d54b8be01f3541a8464345e9a5!
[INFO]	--> Found desired version locally github.com/prometheus/procfs a6e9df898b1336106c743392c48ee0b71f5c4efa!
[INFO]	--> Found desired version locally github.com/satori/go.uuid f58768cc1a7a7e77a3bd49e98cdd21419399b6a3!
[INFO]	--> Found desired version locally github.com/spf13/pflag 583c0c0531f06d5278b7d917446061adc344b5cd!
[INFO]	--> Found desired version locally github.com/vishvananda/netns 54f0e4339ce73702a0607f49922aaa1e749b418d!
[INFO]	--> Found desired version locally gopkg.in/go-playground/validator.v8 5f1438d3fca68893a817e4a66806cea46a9e4ebf!
[INFO]	--> Found desired version locally gopkg.in/inf.v0 3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4!
[INFO]	--> Found desired version locally gopkg.in/yaml.v2 670d4cfef0544295bc27a114dbac37980d83185a!
[INFO]	--> Found desired version locally k8s.io/apimachinery 103fd098999dc9c0c88536f5c9ad2e5da39373ae!
[INFO]	--> Fetching cloud.google.com/go
[INFO]	--> Fetching updates for github.com/Azure/go-autorest
[INFO]	--> Fetching updates for github.com/containernetworking/plugins
[INFO]	--> Fetching updates for github.com/coreos/etcd
[INFO]	--> Fetching updates for github.com/gogo/protobuf
[INFO]	--> Fetching updates for github.com/golang/protobuf
[INFO]	--> Fetching updates for github.com/googleapis/gnostic
[INFO]	--> Fetching updates for github.com/gophercloud/gophercloud
[INFO]	--> Fetching updates for github.com/json-iterator/go
[INFO]	--> Fetching updates for github.com/onsi/ginkgo
[INFO]	--> Fetching updates for github.com/onsi/gomega
[INFO]	--> Fetching updates for github.com/projectcalico/go-yaml
[INFO]	--> Fetching updates for github.com/projectcalico/libcalico-go
[INFO]	--> Fetching updates for github.com/prometheus/client_golang
[INFO]	--> Fetching updates for github.com/sirupsen/logrus
[INFO]	--> Fetching updates for github.com/vishvananda/netlink
[INFO]	--> Fetching golang.org/x/crypto
[INFO]	--> Fetching golang.org/x/net
[INFO]	--> Fetching golang.org/x/oauth2
[INFO]	--> Fetching updates for github.com/containernetworking/cni
[ERROR]	Update failed for github.com/projectcalico/go-yaml: Unable to retrieve checked out version: exit status 128
[INFO]	--> Fetching golang.org/x/sys
[ERROR]	Update failed for github.com/containernetworking/plugins: Unable to retrieve checked out version: exit status 128
[INFO]	--> Fetching golang.org/x/text
[ERROR]	Update failed for github.com/Azure/go-autorest: Unable to retrieve checked out version: exit status 128
[INFO]	--> Fetching golang.org/x/time
[ERROR]	Update failed for github.com/gogo/protobuf: Unable to retrieve checked out version: exit status 128
[INFO]	--> Fetching google.golang.org/appengine
[ERROR]	Update failed for github.com/gophercloud/gophercloud: Unable to retrieve checked out version: exit status 128
[INFO]	--> Fetching google.golang.org/genproto
[ERROR]	Update failed for github.com/coreos/etcd: Unable to retrieve checked out version: exit status 128
[INFO]	--> Fetching google.golang.org/grpc
[ERROR]	Update failed for github.com/golang/protobuf: Unable to retrieve checked out version: exit status 128
[INFO]	--> Fetching updates for k8s.io/api
[ERROR]	Update failed for github.com/onsi/ginkgo: Unable to retrieve checked out version: exit status 128
[INFO]	--> Fetching updates for k8s.io/client-go
[ERROR]	Update failed for github.com/json-iterator/go: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for github.com/googleapis/gnostic: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for github.com/onsi/gomega: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for github.com/projectcalico/libcalico-go: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for github.com/prometheus/client_golang: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for github.com/sirupsen/logrus: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for github.com/vishvananda/netlink: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for github.com/containernetworking/cni: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for k8s.io/api: Unable to retrieve checked out version: exit status 128
[ERROR]	Update failed for k8s.io/client-go: Unable to retrieve checked out version: exit status 128
[WARN]	Unable to checkout cloud.google.com/go
[ERROR]	Update failed for cloud.google.com/go: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/crypto
[ERROR]	Update failed for golang.org/x/crypto: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/oauth2
[ERROR]	Update failed for golang.org/x/oauth2: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/sys
[ERROR]	Update failed for golang.org/x/sys: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/text
[ERROR]	Update failed for golang.org/x/text: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/time
[ERROR]	Update failed for golang.org/x/time: Cannot detect VCS
[WARN]	Unable to checkout google.golang.org/appengine
[ERROR]	Update failed for google.golang.org/appengine: Cannot detect VCS
[WARN]	Unable to checkout google.golang.org/grpc
[ERROR]	Update failed for google.golang.org/grpc: Cannot detect VCS
[WARN]	Unable to checkout google.golang.org/genproto
[ERROR]	Update failed for google.golang.org/genproto: Cannot detect VCS
[ERROR]	Failed to install: Unable to retrieve checked out version: exit status 128

2) glide.lock:

hash: be841b36147b6b64889723c00718029f1f9fce00b774524ac71905e0debd8268
updated: 2018-08-10T10:21:31.966194486-07:00
imports:
- name: cloud.google.com/go
  version: 3b1ae45394a234c385be014e9a488f2bb6eef821
  subpackages:
  - compute/metadata
  - internal
- name: github.com/Azure/go-autorest
  version: 1ff28809256a84bb6966640ff3d0371af82ccba4
  subpackages:
  - autorest
  - autorest/adal
  - autorest/azure
  - autorest/date
- name: github.com/beorn7/perks
  version: 3a771d992973f24aa725d07868b467d1ddfceafb
  subpackages:
  - quantile
- name: github.com/containernetworking/cni
  version: a2da8f8d7fd8e6dc25f336408a8ac86f050fbd88
  subpackages:
  - pkg/invoke
  - pkg/skel
  - pkg/types
  - pkg/types/020
  - pkg/types/current
  - pkg/version
- name: github.com/containernetworking/plugins
  version: 7480240de9749f9a0a5c8614b17f1f03e0c06ab9
  subpackages:
  - pkg/ip
  - pkg/ipam
  - pkg/ns
  - pkg/utils/hwaddr
- name: github.com/coreos/etcd
  version: 33245c6b5b49130ca99280408fadfab01aac0e48
  subpackages:
  - auth/authpb
  - client
  - clientv3
  - etcdserver/api/v3rpc/rpctypes
  - etcdserver/etcdserverpb
  - mvcc/mvccpb
  - pkg/tlsutil
  - pkg/transport
  - pkg/types
- name: github.com/coreos/go-iptables
  version: 259c8e6a4275d497442c721fa52204d7a58bde8b
  subpackages:
  - iptables
- name: github.com/davecgh/go-spew
  version: 782f4967f2dc4564575ca782fe2d04090b5faca8
  subpackages:
  - spew
- name: github.com/dgrijalva/jwt-go
  version: 01aeca54ebda6e0fbfafd0a524d234159c05ec20
- name: github.com/ghodss/yaml
  version: 73d445a93680fa1a78ae23a5839bad48f32ba1ee
- name: github.com/gogo/protobuf
  version: c0656edd0d9eab7c66d1eb0c568f9039345796f7
  subpackages:
  - gogoproto
  - proto
  - protoc-gen-gogo/descriptor
  - sortkeys
- name: github.com/golang/glog
  version: 44145f04b68cf362d9c4df2182967c2275eaefed
- name: github.com/golang/protobuf
  version: b4deda0973fb4c70b50d226b1af49f3da59f5265
  subpackages:
  - proto
  - ptypes
  - ptypes/any
  - ptypes/duration
  - ptypes/timestamp
- name: github.com/google/btree
  version: 7d79101e329e5a3adf994758c578dab82b90c017
- name: github.com/google/gofuzz
  version: 44d81051d367757e1c7c6a5a86423ece9afcf63c
- name: github.com/googleapis/gnostic
  version: 0c5108395e2debce0d731cf0287ddf7242066aba
  subpackages:
  - OpenAPIv2
  - compiler
  - extensions
- name: github.com/gophercloud/gophercloud
  version: 781450b3c4fcb4f5182bcc5133adb4b2e4a09d1d
  subpackages:
  - openstack
  - openstack/identity/v2/tenants
  - openstack/identity/v2/tokens
  - openstack/identity/v3/tokens
  - openstack/utils
  - pagination
- name: github.com/gregjones/httpcache
  version: 787624de3eb7bd915c329cba748687a3b22666a6
  subpackages:
  - diskcache
- name: github.com/hashicorp/golang-lru
  version: a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4
  subpackages:
  - simplelru
- name: github.com/imdario/mergo
  version: 6633656539c1639d9d78127b7d47c622b5d7b6dc
- name: github.com/json-iterator/go
  version: f2b4162afba35581b6d4a50d3b8f34e33c144682
- name: github.com/kelseyhightower/envconfig
  version: dd1402a4d99de9ac2f396cd6fcb957bc2c695ec1
- name: github.com/matttproud/golang_protobuf_extensions
  version: c12348ce28de40eed0136aa2b644d0ee0650e56c
  subpackages:
  - pbutil
- name: github.com/mcuadros/go-version
  version: 6d5863ca60fa6fe914b5fd43ed8533d7567c5b0b
- name: github.com/modern-go/concurrent
  version: bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94
- name: github.com/modern-go/reflect2
  version: 05fbef0ca5da472bbf96c9322b84a53edc03c9fd
- name: github.com/onsi/ginkgo
  version: 7f8ab55aaf3b86885aa55b762e803744d1674700
  subpackages:
  - config
  - extensions/table
  - internal/codelocation
  - internal/containernode
  - internal/failer
  - internal/leafnodes
  - internal/remote
  - internal/spec
  - internal/specrunner
  - internal/suite
  - internal/testingtproxy
  - internal/writer
  - reporters
  - reporters/stenographer
  - types
- name: github.com/onsi/gomega
  version: 2152b45fa28a361beba9aab0885972323a444e28
  subpackages:
  - format
  - gbytes
  - gexec
  - internal/assertion
  - internal/asyncassertion
  - internal/oraclematcher
  - internal/testingtsupport
  - matchers
  - matchers/support/goraph/bipartitegraph
  - matchers/support/goraph/edge
  - matchers/support/goraph/node
  - matchers/support/goraph/util
  - types
- name: github.com/pborman/uuid
  version: ca53cad383cad2479bbba7f7a1a05797ec1386e4
- name: github.com/peterbourgon/diskv
  version: 5f041e8faa004a95c88a202771f4cc3e991971e6
- name: github.com/projectcalico/go-json
  version: 6219dc7339ba20ee4c57df0a8baac62317d19cb1
  subpackages:
  - json
- name: github.com/projectcalico/go-yaml
  version: 955bc3e451ef0c9df8b9113bf2e341139cdafab2
- name: github.com/projectcalico/go-yaml-wrapper
  version: 598e54215bee41a19677faa4f0c32acd2a87eb56
- name: github.com/projectcalico/libcalico-go
  version: cac4ce6d0f2f1fdcaac2dcbe613374465cfd4953
  subpackages:
  - lib/apiconfig
  - lib/apis/v1
  - lib/apis/v1/unversioned
  - lib/apis/v3
  - lib/backend
  - lib/backend/api
  - lib/backend/etcdv3
  - lib/backend/k8s
  - lib/backend/k8s/conversion
  - lib/backend/k8s/resources
  - lib/backend/model
  - lib/clientv3
  - lib/errors
  - lib/hash
  - lib/ipam
  - lib/ipip
  - lib/logutils
  - lib/names
  - lib/namespace
  - lib/net
  - lib/numorstring
  - lib/options
  - lib/scope
  - lib/selector
  - lib/selector/parser
  - lib/selector/tokenizer
  - lib/set
  - lib/validator/v3
  - lib/watch
- name: github.com/prometheus/client_golang
  version: 5b23715facdef1452016bae512489c3cdf82458c
  subpackages:
  - prometheus
- name: github.com/prometheus/client_model
  version: 5c3871d89910bfb32f5fcab2aa4b9ec68e65a99f
  subpackages:
  - go
- name: github.com/prometheus/common
  version: c7de2306084e37d54b8be01f3541a8464345e9a5
  subpackages:
  - expfmt
  - internal/bitbucket.org/ww/goautoneg
  - model
- name: github.com/prometheus/procfs
  version: a6e9df898b1336106c743392c48ee0b71f5c4efa
  subpackages:
  - xfs
- name: github.com/satori/go.uuid
  version: f58768cc1a7a7e77a3bd49e98cdd21419399b6a3
- name: github.com/sirupsen/logrus
  version: d682213848ed68c0a260ca37d6dd5ace8423f5ba
- name: github.com/spf13/pflag
  version: 583c0c0531f06d5278b7d917446061adc344b5cd
- name: github.com/vishvananda/netlink
  version: 6e453822d85ef5721799774b654d4d02fed62afb
  subpackages:
  - nl
- name: github.com/vishvananda/netns
  version: 54f0e4339ce73702a0607f49922aaa1e749b418d
- name: golang.org/x/crypto
  version: de0752318171da717af4ce24d0a2e8626afaeb11
  subpackages:
  - ssh/terminal
- name: golang.org/x/net
  version: 1c05540f6879653db88113bc4a2b70aec4bd491f
  subpackages:
  - context
  - context/ctxhttp
  - html
  - html/atom
  - http2
  - http2/hpack
  - idna
  - internal/timeseries
  - lex/httplex
  - trace
  - websocket
- name: golang.org/x/oauth2
  version: a6bd8cefa1811bd24b86f8902872e4e8225f74c4
  subpackages:
  - google
  - internal
  - jws
  - jwt
- name: golang.org/x/sys
  version: 1b2967e3c290b7c545b3db0deeda16e9be4f98a2
  subpackages:
  - unix
  - windows
- name: golang.org/x/text
  version: b19bf474d317b857955b12035d2c5acb57ce8b01
  subpackages:
  - secure/bidirule
  - transform
  - unicode/bidi
  - unicode/norm
- name: golang.org/x/time
  version: f51c12702a4d776e4c1fa9b0fabab841babae631
  subpackages:
  - rate
- name: google.golang.org/appengine
  version: 4216e58b9158e5f1c906f1aca75162a46a2ec88a
  subpackages:
  - internal
  - internal/app_identity
  - internal/base
  - internal/datastore
  - internal/log
  - internal/modules
  - internal/remote_api
  - internal/urlfetch
  - urlfetch
- name: google.golang.org/genproto
  version: 09f6ed296fc66555a25fe4ce95173148778dfa85
  subpackages:
  - googleapis/rpc/status
- name: google.golang.org/grpc
  version: 5b3c4e850e90a4cf6a20ebd46c8b32a0a3afcb9e
  subpackages:
  - balancer
  - codes
  - connectivity
  - credentials
  - grpclb/grpc_lb_v1/messages
  - grpclog
  - health
  - health/grpc_health_v1
  - internal
  - keepalive
  - metadata
  - naming
  - peer
  - resolver
  - stats
  - status
  - tap
  - transport
- name: gopkg.in/go-playground/validator.v8
  version: 5f1438d3fca68893a817e4a66806cea46a9e4ebf
- name: gopkg.in/inf.v0
  version: 3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4
- name: gopkg.in/yaml.v2
  version: 670d4cfef0544295bc27a114dbac37980d83185a
- name: k8s.io/api
  version: 072894a440bdee3a891dea811fe42902311cd2a3
  subpackages:
  - admissionregistration/v1alpha1
  - admissionregistration/v1beta1
  - apps/v1
  - apps/v1beta1
  - apps/v1beta2
  - authentication/v1
  - authentication/v1beta1
  - authorization/v1
  - authorization/v1beta1
  - autoscaling/v1
  - autoscaling/v2beta1
  - batch/v1
  - batch/v1beta1
  - batch/v2alpha1
  - certificates/v1beta1
  - core/v1
  - events/v1beta1
  - extensions/v1beta1
  - networking/v1
  - policy/v1beta1
  - rbac/v1
  - rbac/v1alpha1
  - rbac/v1beta1
  - scheduling/v1alpha1
  - scheduling/v1beta1
  - settings/v1alpha1
  - storage/v1
  - storage/v1alpha1
  - storage/v1beta1
- name: k8s.io/apimachinery
  version: 103fd098999dc9c0c88536f5c9ad2e5da39373ae
  subpackages:
  - pkg/api/errors
  - pkg/api/meta
  - pkg/api/resource
  - pkg/apis/meta/internalversion
  - pkg/apis/meta/v1
  - pkg/apis/meta/v1/unstructured
  - pkg/apis/meta/v1beta1
  - pkg/conversion
  - pkg/conversion/queryparams
  - pkg/fields
  - pkg/labels
  - pkg/runtime
  - pkg/runtime/schema
  - pkg/runtime/serializer
  - pkg/runtime/serializer/json
  - pkg/runtime/serializer/protobuf
  - pkg/runtime/serializer/recognizer
  - pkg/runtime/serializer/streaming
  - pkg/runtime/serializer/versioning
  - pkg/selection
  - pkg/types
  - pkg/util/cache
  - pkg/util/clock
  - pkg/util/diff
  - pkg/util/errors
  - pkg/util/framer
  - pkg/util/intstr
  - pkg/util/json
  - pkg/util/net
  - pkg/util/runtime
  - pkg/util/sets
  - pkg/util/uuid
  - pkg/util/validation
  - pkg/util/validation/field
  - pkg/util/wait
  - pkg/util/yaml
  - pkg/version
  - pkg/watch
  - third_party/forked/golang/reflect
- name: k8s.io/client-go
  version: 7d04d0e2a0a1a4d4a1cd6baa432a2301492e4e65
  subpackages:
  - discovery
  - kubernetes
  - kubernetes/scheme
  - kubernetes/typed/admissionregistration/v1alpha1
  - kubernetes/typed/admissionregistration/v1beta1
  - kubernetes/typed/apps/v1
  - kubernetes/typed/apps/v1beta1
  - kubernetes/typed/apps/v1beta2
  - kubernetes/typed/authentication/v1
  - kubernetes/typed/authentication/v1beta1
  - kubernetes/typed/authorization/v1
  - kubernetes/typed/authorization/v1beta1
  - kubernetes/typed/autoscaling/v1
  - kubernetes/typed/autoscaling/v2beta1
  - kubernetes/typed/batch/v1
  - kubernetes/typed/batch/v1beta1
  - kubernetes/typed/batch/v2alpha1
  - kubernetes/typed/certificates/v1beta1
  - kubernetes/typed/core/v1
  - kubernetes/typed/events/v1beta1
  - kubernetes/typed/extensions/v1beta1
  - kubernetes/typed/networking/v1
  - kubernetes/typed/policy/v1beta1
  - kubernetes/typed/rbac/v1
  - kubernetes/typed/rbac/v1alpha1
  - kubernetes/typed/rbac/v1beta1
  - kubernetes/typed/scheduling/v1alpha1
  - kubernetes/typed/scheduling/v1beta1
  - kubernetes/typed/settings/v1alpha1
  - kubernetes/typed/storage/v1
  - kubernetes/typed/storage/v1alpha1
  - kubernetes/typed/storage/v1beta1
  - pkg/apis/clientauthentication
  - pkg/apis/clientauthentication/v1alpha1
  - pkg/apis/clientauthentication/v1beta1
  - pkg/version
  - plugin/pkg/client/auth
  - plugin/pkg/client/auth/azure
  - plugin/pkg/client/auth/exec
  - plugin/pkg/client/auth/gcp
  - plugin/pkg/client/auth/oidc
  - plugin/pkg/client/auth/openstack
  - rest
  - rest/watch
  - third_party/forked/golang/template
  - tools/auth
  - tools/cache
  - tools/clientcmd
  - tools/clientcmd/api
  - tools/clientcmd/api/latest
  - tools/clientcmd/api/v1
  - tools/metrics
  - tools/pager
  - tools/reference
  - transport
  - util/buffer
  - util/cert
  - util/connrotation
  - util/flowcontrol
  - util/homedir
  - util/integer
  - util/jsonpath
  - util/retry
testImports: []

**Comment by caseydavenport** [comment]
@pencc running `make image` on that branch works fine for me, as well as our [CI](https://semaphoreci.com/calico/cni-plugin/branches/release-v3-2)

I think this is probably an issue with your local build environment.
