### ISSUE TITLE
Support Error as log level in CNI v3.0

### ISSUE THREAD

**Issue by lunaimaginea** [projectcalico/cni-plugin#672]
I’d recommend against disabling infor/warning logs 

## Expected Behavior
If you  hit an error (that you can’t reproduce with info/debug logs on), there’ll be too little to go on in the logs to help since we’ll have no context.

## Current Behavior
Currently the supported log level in the CNI configuration are as follows.
1.WARNING
2.DEBUG
3.INFO

## Possible Solution
The log level should be overridable to error too.

## Steps to Reproduce (for bugs):
I have deployed [Openstack AIO](https://docs.openstack.org/devstack/latest/guides/single-vm.html) .have changed the log_level in the calico chart as ERROR in the following file.
[CNI Config](https://github.com/openstack/openstack-helm-infra/blob/master/calico/values.yaml#L420)
1. The info logs are still coming
2. The override to the default log_level (which is info) to ERROR is not working.
3. According to the docs also I found the error is not currently supported. [https://docs.projectcalico.org/v3.0/reference/cni-plugin/configuration](url)

4.exec into install-cni container in calico/node

Then run cat 

`/host/etc/cni/net.d/10-calico.conf`

The output is as follows:

`{"cniVersion":"0.1.0","etcd_endpoints":"...","ipam":{"type":"calico-ipam"},"kubernetes":{"kubeconfig":"/etc/cni/net.d/calico-kubeconfig"},"log_level":"error","mtu":1480,"name":"k8s-pod-network","policy":{"k8s_api_root":"...","k8s_auth_token":"...","type":"k8s"},"type":"calico"} `

But according to according to [https://github.com/projectcalico/cni-plugin/blob/master/internal/pkg/utils/utils.go#L563](url) it suppose to take warning in case of error

## Your Environment

* CNI plugin version:v3.0 :
* Orchestrator  kubernetes.

**Comment by caseydavenport** [comment]
@lunaimaginea which INFO logs in particular are you still seeing?

**Comment by caseydavenport** [comment]
Right, so those logs are not from the CNI plugin - they come from the Felix component, as well as our BGP components. 

have you also adjusted the log levels for those components?

**Comment by lunaimaginea** [comment]
@caseydavenport I believe you are indicating FELIX_LOGSEVERITYSCREEN for felix .

**Comment by lunaimaginea** [comment]
@caseydavenport  [https://github.com/openstack/openstack-helm-infra/blob/master/calico/templates/daemonset-calico-node.yaml#L215](https://github.com/openstack/openstack-helm-infra/blob/master/calico/templates/daemonset-calico-node.yaml#L215) adding the following 
``` 
- name: CALICO_STARTUP_LOGLEVEL
  value: {{ .Values.conf.cni_network_config.plugins[0].log_level }}
```
`.Values.conf.cni_network_config.plugins[0].log_level`  can be set as error.
and can successfully override the default log level of some logs after running 
`kubectl -n kube-system logs calico-node-pod -c calico-node` and  rest of the logs are coming from bgp and felix components as you have mentioned .

**Comment by caseydavenport** [comment]
This was added here: https://github.com/projectcalico/cni-plugin/pull/676
