### ISSUE TITLE
K8S_API_TOKEN is leaking here, security vulnerability

### ISSUE THREAD

**Issue by kevdowney** [projectcalico/cni-plugin#687]
https://github.com/projectcalico/cni-plugin/blob/1d6bd9c7ba885fa07497385b545aa755187baf9c/utils/utils.go#L259

https://github.com/projectcalico/cni-plugin/blob/1d6bd9c7ba885fa07497385b545aa755187baf9c/utils/utils.go#L263

You should remove this log line or set this to debug.

**Comment by caseydavenport** [comment]
@kevdowney this has been fixed and backported as far as Calico v2.6. Which release are you using?

Original fix was here: https://github.com/projectcalico/cni-plugin/pull/628/

The backports made it into these patch releases:
- v2.6.12
- v3.2.4
- v3.3.1

**Comment by kevdowney** [comment]
Looks like kops is using an unpatched version. I’ll close this. Thanks.
