### ISSUE TITLE
Missing s390x build

### ISSUE THREAD

**Issue by diederichm** [projectcalico/cni-plugin#706]
The Kubernetes Dokumentation lists s390x as supported architecture, but ist not being built
## Expected Behavior
have valid s390x build on dockerhub

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
* Orchestrator version (e.g. kubernetes, mesos, rkt):
Kubernetes 1.12
* CNI config:
* Operating System and version: s390x, SLES12SP3
* Link to your project (optional):

if there are build issues - maybe I can help ?

**Comment by fasaxc** [comment]
s390x support is community-maintained.  Currently, the s390x cross-build doesn't succeed from Tigera's build infrastructure so we're not able to publish those builds as we do for arm64 and ppc64; the linux-on-ibm-z team maintain a guide explaining how to build Calico for s390x here: https://github.com/linux-on-ibm-z/docs/wiki/Building-Calico-3.x
