### ISSUE TITLE
bad outbound tcp checksum

### ISSUE THREAD

**Issue by ms4720** [projectcalico/cni-plugin#712]
I have one set of pods setup in 2 stateful sets in aws that produce bad tcp checksum errors and not downloading data, all the other pods are working.  They are komodo crypto coin nodes.  

I opened a ticket in the komodo repo [kmodo 1337](https://github.com/jl777/komodo/issues/1337) and was told sometimes it does not work

and works on an older k8s cluster, 1.10.x, broken on the newer cluster, 1.11.8.  

What I am looking for is some pointers about what to check.  
## Expected Behavior

I would like the pods to download their blockchain files 

## Current Behavior

After the intital download things stop at block 0 and do not progress.  There are some other files it downloads.  

## Possible Solution

it looks like this writeup from twitter https://tech.vijayp.ca/linux-kernel-bug-delivers-corrupt-tcp-ip-data-to-mesos-kubernetes-docker-containers-4986f88f7a19

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v1.11.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.11.8
* CNI config:
```
more calico-kubeconfig 10-calico.conflist
::::::::::::::
calico-kubeconfig
::::::::::::::
# Kubeconfig file for Calico CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
users:
- name: calico
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico
current-context: calico-context
::::::::::::::
10-calico.conflist
::::::::::::::
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "etcd_endpoints": "http://etcd-a.internal.DOMAIN.com:4001,http://etcd-c.internal.DOMAIN.com:4001,http://etcd-d.internal.DOMAINcom:4001",
      "log_level": "info",
      "ipam": {
        "type": "calico-ipam"
      },
      "policy": {
        "type": "k8s",
        "k8s_api_root": "https://100.64.0.1:443",
        "k8s_auth_token": "REDACTED"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
```
* Operating System and version: ubuntu 16.4 kernel 4.15.0-45-generic
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> After reading through the kernel networking code, it became apparent that the bug was in the veth kernel module

Have you checked the kernel versions on the two clusters to see if they are different? It's a bit of a stretch, but if you're hitting the linked bug that would help identify it.

> produce bad tcp checksum errors and not downloading data

What produces these errors? IIUC, the linked bug would result in _not_ producing an error, and instead seeing bogus information show up in the application. So it leads me to think this might be something different.

> /opt/cni/bin/calico --version): v1.11.5

This is a super old version of Calico - I recommend upgrading to a newer version to see if it's any different. We've done a lot of work since then!

**Comment by ms4720** [comment]
Thanks for the help

- they are both 4.15, different patch levels
- the checksum errors were reported by tcpdump, looks like far end dropped/ignored them 
- the 1.11.5 is the default for kops when building clusters for k8s 1.11, kops 1.12 just entered alpha and that may update things

**Comment by caseydavenport** [comment]
@ms4720 any updates on this? Did you try with a newer Calico version? It's not obvious that this is a Calico issue to me.
