### ISSUE TITLE
Fixed IP support for Mesos

### ISSUE THREAD

**Issue by newffy** [projectcalico/cni-plugin#738]
We need support of fixed IPs in Mesos cluster with Calico (maybe similar to Kubernetes cluster).
We propose to do it with Mesos labels, using the same syntax as already has been used for k8s annotations.
For example, if application deployed via Marathon, then `network` section of application definition can look like 
```
"networks": [
    {
      "name": "cni-net-fixedpool",
      "mode": "container",
      "labels": {
        "cni.projectcalico.org/ipAddrs": "[\"10.11.12.13\"]"
      }
    }
  ],
  "upgradeStrategy": {
    "maximumOverCapacity": 0,
    "minimumHealthCapacity": 0
  }
```
current implementation of this feature can be seen in PR #723 
Please, let me know whether it can be merged to calico cni-plugin code and what can be improved.

**Comment by caseydavenport** [comment]
@newffy sorry for the long delay on this. Are you guys currently running Calico v3.x on a Mesos / Marathon deployment?

Strictly speaking, this isn't something that the core Calico team currently supports, but I'd be happy to review and merge that PR provided it's pretty well isolated and you guys are willing to maintain the change over time if needed.

**Comment by newffy** [comment]
Hi!
We are using Calico 3.6.1 with Mesos 1.7 and it works very well.
we would like to have more tools like clearing orphaned (for whatever reason) endpoints from calico storage, but that's not annoying us too much.
And yes, we are ready to maintain this option, because we are using Calico with Mesos in production for a while.

Thanks
