### ISSUE TITLE
Bandwidth plugin can not work when use calico-ipam

### ISSUE THREAD

**Issue by zillaer** [projectcalico/cni-plugin#748]
## Expected Behavior

Use cni bandwidth pluging to control the k8s pod ingress and egress bandwidth when set the 
deployment annotation like “kubernetes.io/ingress-bandwidth: 10M”

## Current Behavior

The traffic shaping doesn't work when use calico-ipam

## Possible Solution

May be it's a bug

my cni configuration is copy from k8s offical site like fellow url:

https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#support-traffic-shaping

## Steps to Reproduce (for bugs)

1.Add the bandwidth plugin in the calico.yaml like behind:
<pre><code>
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
</code></pre>
and create the calico network
2.Set the annotation like "kubernetes.io/ingress-bandwidth: 10M" and "kubernetes.io/egress-bandwidth: 10M" in deployment
3.Create the deployment and scale the replication to 2
4.Run a iperf3 server like "iperf3 -s -p 12345 -i 1" in one pod
5.Run a iperf3 client like "iperf -c ${serverPod-ip} -p 12345 -i 1 -t 10 -w 400K"
The traffic shaping is not work and the bandwidth is up to 20 gigabytes

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):v3.7.2
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubernetes
* CNI config:
<pre><code>
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
</code></pre>
* Operating System and version:centos 7.6

**Comment by shufanhao** [comment]
I also hit this issue,  not only bandwidth plugin can not work when using calico-ipam but also can not work when using host-local

**Comment by lwr20** [comment]
You've seen this, right? 
https://github.com/projectcalico/calico/issues/797#issuecomment-493210584
