### ISSUE TITLE
Log default kubernetes network policies

### ISSUE THREAD

**Issue by zakthan** [projectcalico/cni-plugin#758]
I have changed calico LogSeverityScreen to debug and I have implemented some native kubernetes network policies. Checking the logs of my calico-nodes I could not see any entries for my dropped policies.
Do you know if logging dropped k8s network policies with calico CNI is doable?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): 3.1.7
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubernetes
* CNI config:
* Operating System and version:CentOS Linux 7
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> action | Action to perform when matching this rule. | Allow, Deny, Log, Pass | string

I think you can specify an extra rule with an explicit action of Log.

From here: https://docs.projectcalico.org/v3.7/reference/calicoctl/resources/networkpolicy

**Comment by zakthan** [comment]
Hi Casey,
Thank you very much for your reply.
This is true if you use calico network policies.
The thing is that I would like to use native Kubernetes network policies.
In that case  (native k8s network policies and calico as CNI) is there any way to log dropped traffic?

**Comment by caseydavenport** [comment]
@zakthan ah, right. No I don't think that's possible today - the Kubernetes NP API doesn't have such a feature.

**Comment by zakthan** [comment]
@casey yeah I guess so.. at the documentation it states that it is the CNI the is responsible for the logging.
But even putting all calico logging to debug level I still did not see any iptables droppes packets anywhere.
Anyways I will try to open an issue to the kubernetes project.
Thank you very much for your time.
