### ISSUE TITLE
Support for rangeStart/rangeEnd in calico-ipam

### ISSUE THREAD

**Issue by sbueringer** [projectcalico/cni-plugin#761]
It would be nice if calico-ipam would also support rangeStart/rangeEnd properties similar to the [host-local plugin](https://github.com/containernetworking/plugins/tree/master/plugins/ipam/host-local).
In my case calico-ipam assigns the .0,.1 & .255 IPs to a Pod and that's a problem in my environment as they are not routed correctly to the Pods.

Conceptually, I think it would be enough to create less IPs in the unallocated array in the IpamBlock depending on new rangeStart/rangeEnd properties (which could be added on the IPPool I guess?). Everything else should then work as expected.

I'm not really sure how & where this has to be implemented to arrive at a clean solution, maybe somebody familiar with the code base can advise. Especially how the properties could be propagated down from the initial IPPool to the IpamBlock.

**Comment by bavarianbidi** [comment]
The first ip in a subnet defines the `network` and should never assigned to any device.
would prever an implementation simular like:

if no router-ip is defined: use the second ip from the range
if no broadcast-ip is defined: use the last ip from the range

network range - network-ip - router-ip - broadcast-ip is the range to use for calico-ipam

**Comment by caseydavenport** [comment]
> The first ip in a subnet defines the network and should never assigned to any device

This isn't really the case for Calico. See [here](https://docs.projectcalico.org/v3.5/usage/troubleshooting/faq#can-calico-containers-use-any-ip-address-within-a-pool-even-subnet-networkbroadcast-addresses) and [here](https://github.com/projectcalico/calico/issues/1710) for a bit more information.

**Comment by caseydavenport** [comment]
> that's a problem in my environment as they are not routed correctly to the Pods.

Do you know what it is about your environment that is causing the routing to not be done correctly?

**Comment by sbueringer** [comment]
@caseydavenport  
To be honest we're not really sure. We tried it and we have problems at least with `.0`. `.1` actually works.

We're using for now the host-local plugin, because we don't really need the additional features of Calico IPAM in our environment.

Our environment is based on OpenStack. We're creating VMs with IPs in 10.6.0.0/24. Because in NSX-V we have to specific a list of Allowed IPs per VM we then use a dedicated /24 net per VM. For example a Kubernetes Node has the IP 10.6.0.5. The Pods on this VM will get the IPs from the range 10.6.5.0/24. We're templating routing rules so that every /24 Pod CIDR is routed to the correct VM and that's it. Somehow the .0 IP doesn't work.

**Comment by caseydavenport** [comment]
> Somehow the .0 IP doesn't work.

I think it is important that we first understand why the .0 isn't working in your environment. I'd recommend checking various stages of the network to see if the traffic is getting dropped there - that will at least identify who is the culprit.

**Comment by rafaelvanoni** [comment]
@sbueringer Have you had a chance to look at why that traffic is getting dropped?

**Comment by sbueringer** [comment]
@rafaelvanoni Sorry we didn't really have time to dig that deep. It wasn't anything obvious. I think it's okay to close the issue until somebody shows up with a valid use case :)
