### ISSUE TITLE
Is there any plan to support traffic control ? 

### ISSUE THREAD

**Issue by shufanhao** [projectcalico/cni-plugin#762]
Just want to know is there plan to support traffic control  ? Some time use bandwidth plugin is not convenient. 

Traffic control like below:
`k8s.calico.com/ingress-bandwidth: 10M
 k8s.calico.com/egress-bandwidth: 10M`

If there is not plan to support TC, I would like to contribute this feature. Because in my project need use calico to do TC directly.

**Comment by lwr20** [comment]
I think this already works:
https://github.com/projectcalico/calico/issues/797#issuecomment-493210584

**Comment by shufanhao** [comment]
Thanks for your information, let me try it.
