### ISSUE TITLE
why the calico-node is listening 127.0.0.1:9099

### ISSUE THREAD

**Issue by AL-Cui** [projectcalico/cni-plugin#767]
why the calico-node is listening 127.0.0.1:9099
## Expected Behavior

when I created the calico-node pods, I found the calico-node is listening 127.0.0.1:9099 instead of 0.0.0.0:9099.
My calico client Version and Cluster Version is v3.8.0
![image](https://user-images.githubusercontent.com/20554968/61619086-bd2b7f00-aca0-11e9-884b-cdbb4f7a3a3d.png)
So,my calico-node pod is not Ready.the Readiness probe and Liveness probe failed.
![image](https://user-images.githubusercontent.com/20554968/61619231-04b20b00-aca1-11e9-9ba8-5653e17a97e0.png)
My Docker image is calico/node:release-v3.8-arm64.
I use this '[calico.yaml'](https://docs.projectcalico.org/v3.8/manifests/calico-etcd.yaml) file 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v3.8.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubernetes version: 13.5
* CNI config: 
* Operating System and version: Linux aarch64
* Link to your project (optional):

**Comment by fasaxc** [comment]
The readiness port generally only needs to be accessed by kubelet, which can use 127.0.0.1 since it's on the same node as Felix.  Limiting the bind to 127.0.0.1 is a security feature, it blocks access from outside the node.

**Comment by rafaelvanoni** [comment]
Please add a comment if there's something that still needs to be clarified.

**Comment by AL-Cui** [comment]
> The readiness port generally only needs to be accessed by kubelet, which can use 127.0.0.1 since it's on the same node as Felix. Limiting the bind to 127.0.0.1 is a security feature, it blocks access from outside the node.

But，why k8s warned me that unhealthy,the readiness probe failed: Get http://172.23.5.22:9099/readiness.(172.23.5.22 is my Physical IP)

**Comment by tmjd** [comment]
Have you checked the logs from calico-node? Looks like maybe there might be a real problem.

**Comment by caseydavenport** [comment]
>  failed: Get http://172.23.5.22:9099/readiness.(172.23.5.22 is my Physical IP)

Does your manifest have `host: 127.0.0.1` or `host: localhost` set on the readinessProbe?

**Comment by AL-Cui** [comment]
> Have you checked the logs from calico-node? Looks like maybe there might be a real problem.

![image](https://user-images.githubusercontent.com/20554968/61779479-525e7d00-ae33-11e9-9e4a-1ccec71b083b.png)
this is calico-node log.
And,I exec the calico-node docker container,and exec calico-node -felix-ready,it's ok.
![image](https://user-images.githubusercontent.com/20554968/61779849-02cc8100-ae34-11e9-8b9e-aad6766f31aa.png)

**Comment by AL-Cui** [comment]
> > failed: Get http://172.23.5.22:9099/readiness.(172.23.5.22 is my Physical IP)
> 
> Does your manifest have `host: 127.0.0.1` or `host: localhost` set on the readinessProbe? Could you paste in your node's readinessProbe configuration here?
> 
> Here's an example for Calico v3.8: https://github.com/projectcalico/calico/blob/master/_includes/v3.8/charts/calico/templates/calico-node.yaml#L283-L297
![image](https://user-images.githubusercontent.com/20554968/61779913-1a0b6e80-ae34-11e9-8623-5fa6c2d7b962.png)

**Comment by fasaxc** [comment]
@AL-Cui Looks like your manifest is wrong.  Where did you get your manifest, is it one of the ones that we provide in our documentation?  Did you, for example, try to upgrade Calico by modifying the container image version without updating to the latest manifest?

**Comment by AL-Cui** [comment]
> @AL-Cui Looks like your manifest is wrong. Where did you get your manifest, is it one of the ones that we provide in our documentation? Did you, for example, try to upgrade Calico by modifying the container image version without updating to the latest manifest?

OK,I check it.And,My manifest is wrong. The manifest file I am using is old。
Thanks!

**Comment by AL-Cui** [comment]
My  manifest file is 3.1.3.
