### ISSUE TITLE
Dataplane interface for the CNI plugin?

### ISSUE THREAD

**Issue by AloysAugustin** [projectcalico/cni-plugin#818]
Hi Calico maintainers,

We are working on integrating Calico with an alternate dataplane (FD.io VPP). We noticed that there is a dataplane interface for felix but there is no equivalent for the CNI plugin. Is it something that you would be open to adding? This would allow us (and presumably most users of felix's dataplane interface) not to fork the entire CNI plugin.
We have a working prototype and are happy to contribute code if this is something you're interested in.

**Comment by caseydavenport** [comment]
@AloysAugustin that sounds reasonable to me. Before you get started, might be useful to sketch out the changes you're proposing in the next level of detail here in this issue?

**Comment by AloysAugustin** [comment]
Thanks @caseydavenport, sure.
Looking at the code, I think the right point to insert this interface is at the level of the `DoNetworking` / `CleanUpNamespace` pair of functions in [internal/pkg/utils/network_linux.go](https://github.com/projectcalico/cni-plugin/blob/cd887812815fbd260881d046a4574b876335c513/internal/pkg/utils/network_linux.go).
We can define a gRPC service with two rpcs whose arguments and return values match those of these functions. The CNI would then act as a client to this service, performing RPCs each time it is called. 
Regarding the configuration of this feature, I think it should be specified in the network definition, and it could look like this:
```
    "dataplane_options": {
        "type": "external",
        "socket": "unix:///var/run/calico/cni-server.sock"
    }
```
This allows several networks with different dataplanes to coexist, and the socket argument can be passed directly to `grpc.Dial`, allowing the use of unix or tcp sockets for the requests as required. The grpc dial options can be passed through additional parameters in this config section.

Do you have any questions or concerns about this approach?

**Comment by caseydavenport** [comment]
Seems reasonable to me - so we'd keep the existing implementation compiled in and default if no `dataplane_options` are provided?

@fasaxc you might be interested in this as well

**Comment by AloysAugustin** [comment]
> Seems reasonable to me - so we'd keep the existing implementation compiled in and default if no `dataplane_options` are provided?

Yes, that's the idea.
If that sounds fine to you I will clean up my fork, make the .proto file more consistent with the [Felix proto](https://github.com/projectcalico/felix/blob/master/proto/felixbackend.proto) and open a PR here.

**Comment by caseydavenport** [comment]
@AloysAugustin I think that sounds great.
