### ISSUE TITLE
calico cni image blob problem?

### ISSUE THREAD

**Issue by salamander-mh** [projectcalico/cni-plugin#822]
## Expected Behavior
```
$ docker pull quay-mirror.qiniu.com/calico/cni:v3.3.2
v3.3.2: Pulling from calico/cni
4fe2ade4980c: Downloading 
7f9ef7e5380c: Download complete 
1bcdb1c702ef: Download complete 
e60c1681ba2f: Download complete 
unknown blob
```
seems the image is broken?

**Comment by tmjd** [comment]
The images on quay.io (quay.io/calico/cni:v3.3.2) and dockerhub (calico/cni:v3.3.2) seem to pull correctly for me, please try pulling from one of those. Those are the repositories where we upload images. You should pull from one of those repositories or a mirror or repository you trust. If you trust the mirror you're using you should bring this problem up with the maintainers of that mirror.

**Comment by tmjd** [comment]
I'm closing this issue as we do not upload to that repo or have any involvement with that mirror.
If pulling from one of the above repositories does not work for you please feel free to comment and I'll re-open this issue.
