### ISSUE TITLE
install-cni.sh bash syntax error

### ISSUE THREAD

**Issue by tghartland** [projectcalico/cni-plugin#835]
## Current Behavior
`install-cni.sh` fails with this error
```
/install-cni.sh: line 195: [-z: command not found
```

## Possible Solution
Bash syntax needs spaces inside the square brackets here.
https://github.com/projectcalico/cni-plugin/blob/95276869e7b6536403f4f387fa086f8d7c1e4d90/k8s-install/scripts/install-cni.sh#L195

## Your Environment
* CNI plugin version: v3.12.0 (but installed with v3.3.6 manifests, it doesn't work but that's a separate problem)
* Orchestrator version: kubernetes
* CNI config:
* Operating System and version: Fedora CoreOS 31.20200113.3.1

**Comment by tmjd** [comment]
Are you running this 'directly'? Not in a calico-node pod as part of a kubernetes daemonset? I'm just wondering why we haven't hit this before.
If you're up for it I would happily review a PR to fix this.
Thanks for reporting.

**Comment by spikecurtis** [comment]
`install-cni.sh` is meant to be run with `sh` not `bash`; e.g. first line is

https://github.com/projectcalico/cni-plugin/blob/95276869e7b6536403f4f387fa086f8d7c1e4d90/k8s-install/scripts/install-cni.sh#L1

This is presumably why we haven't seen it in our tests

**Comment by tghartland** [comment]
Likely just an issue with my environment then. As I mentioned I'm starting with v3.3.6 ([which is the manifest version deployed by Openstack Magnum](https://github.com/openstack/magnum/blob/16ea8b6397f2bafc01e6d4ec474c1ae97f15a484/magnum/drivers/common/templates/kubernetes/fragments/calico-service.sh#L128-L132)) and then trying to swap in v3.12.0 after Calico has already initialised the nodes - not really a good idea, I know, and I'll probably just stick to using v3.3.6 from now on.

That said, I don't think there's anything in the [install-cni definition](https://github.com/openstack/magnum/blob/16ea8b6397f2bafc01e6d4ec474c1ae97f15a484/magnum/drivers/common/templates/kubernetes/fragments/calico-service.sh#L456-L486) of v3.3.6 deployed by Openstack that would cause it to error like this when the container tag is changed to v3.12.0.

Thanks for making a fix for this anyway, even if it only showed up in this extreme edge case.

**Comment by spikecurtis** [comment]
@tghartland thanks for this bug report --- turns out this is a legit bug.  `sh` barfs on the syntax just the same as `bash` and the effect was that we were always skipping the datastore check, regardless of whether that env var was set.  I've fixed this up in the PR above, FYI
