### ISSUE TITLE
Cross node network policies don't work

### ISSUE THREAD

**Issue by axozoid** [projectcalico/cni-plugin#843]
Hi guys,
please assist me in solving this mystery!

When I follow the [tutorial](https://docs.projectcalico.org/security/tutorials/kubernetes-policy-basic) from your website I end up observing a weird thing.

## Expected Behavior
When you typically hit a Kubernetes service, you get a reply from random pods that satisfy label selector and allowed in a network policy, however it's not the case I'm observing. Once I apply NP, things change!

## Current Behavior
Only pods from the same node (the source and the destination pods) are responding.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. follow the [tutorial](https://docs.projectcalico.org/security/tutorials/kubernetes-policy-basic) to deploy 2 replicas of nginx and a tester pod, along with the network policies;
2. configure nginx pods to reply with their IP instead of "welcome page" (`hostname -i > /usr/lib/share/html/index.html`);
3. try hitting the service, for example like this:
```
while true; do wget -qO- --timeout=1 nginx; sleep 1; done
```
and we should get a reply from different IPs, but in reality we get:
```
100.88.159.195
wget: download timed out
wget: download timed out
100.88.159.195
100.88.159.195
100.88.159.195
wget: download timed out
```
where `100.88.159.195` is the IP of the nginx pod running on the same node as the tester pod (from which I do wget)

## Context
I was trying to setup simple network policies that allow access to a K8s service (pods) just from specific pods (labeled properly).

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): `v3.11.2`
* Orchestrator version: `Kubernetes v1.15.6`
* CNI config:
* Operating System and version: `Debian GNU/Linux 9 (stretch) / 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux`

**Comment by rafaelvanoni** [comment]
@axozoid Does your test work without the NetworkPolicy being applied? We're wondering if it's a more generic issue with the network configuration in your cluster. Which of the NPs in the tutorial are you applying?

**Comment by axozoid** [comment]
thank you for your reply @rafaelvanoni .
yes, the network is absolutely fine.
As soon as I apply netpol, connections stop working, and when I delete the netpol, all back to normal.

**Comment by axozoid** [comment]
One of the suspicions is CIDR ranges we have.

kube-proxy: `--cluster-cidr=100.96.0.0/11`
kube-api: `--service-cluster-ip-range=100.64.0.0/13`

```
calicoctl get ippool -owide
NAME                  CIDR            NAT    IPIPMODE   VXLANMODE   DISABLED   SELECTOR
default-ipv4-ippool   100.64.0.0/10   true   Never      Always      false      all()
```

**Comment by axozoid** [comment]
To add more, we ended up having those CIDR values as a result of migration from flannel to Calico.
If I deploy a new cluster (using kops) with CNI=Calico, I have no issues at all, and `ippool`=`cluster-cidr` in that case.

**Comment by tmjd** [comment]
The ippool and kubeproxy cluster-cidr not matching could certainly cause problems with network policy. If pods are not in the 100.96.0.0/11 range then the traffic would be SNAT'ed when leaving a host. The source of the traffic would not appear to be the pods it is coming from causing the network policy to not be applied as expected.

@song-jiang how do we get the ippool when migrating from flannel? do we possibly have a bug in the migration?

**Comment by axozoid** [comment]
Thank you for your input @tmjd.
I did iptables dive yesterday and can confirm your words. All traffic that isn't coming from PODs' CIDR (which is defined in `kube-proxy`) will be marked and then masqueraded:
```
iptables --list -n -t nat -v | grep ns-dst-1
    0     0 KUBE-MARK-MASQ  tcp  --  *      *      !100.96.0.0/11        100.71.140.72        /* ns-dst-1/nginx: cluster IP */ tcp dpt:80
    0     0 KUBE-SVC-H2RWYJ54M6UZLM4E  tcp  --  *      *       0.0.0.0/0            100.71.140.72        /* ns-dst-1/nginx: cluster IP */ tcp dpt:80
```
`ns-dst-1` is my test namespace containing the service I'm trying to reach. Network policies applied there.

I also believe there is a bug in the migration scripts/process. 

We went to Calico from Flannel in order to have network polices, but unfortunately now we need to workaround this issue. Do you see an easy way to fix it? 
I know, the proper way would be updating the ippool to match the `cluster-cidr` value, however in this case we need to re-create all workloads, which will result in downtime  in a production environment with thousands of pods.

Any suggestions are highly appreciated.

**Comment by axozoid** [comment]
In the [documentation](https://docs.projectcalico.org/v3.10/networking/migrate-pools) regarding updating the ippool I can see a warning:

> Important! If you follow these steps, existing pod connectivity will not be affected. (If you delete the old IP pool before you create and verify the new pool, existing pods will be affected.) When pods are deleted, applications may be temporarily unavailable (depending on the type of application); plan accordingly.

However in our case a new ippool (`100.96.0.0/11`) overlaps the existing one (`100.64.0.0/10`), and I obviously get an error message about that. Even if I set `disabled: true` in the new ippool definition, a validation still doesn't allow me to apply it.

What would be the best (the only possible?) way to change the ippool?

Thank you in advance.

**Comment by caseydavenport** [comment]
Sorry for the long delay on this... but for anyone still wondering this is the procedure for migrating IP pools: https://docs.projectcalico.org/networking/migrate-pools
