### ISSUE TITLE
ubi-minimal:latest not command hostname

### ISSUE THREAD

**Issue by asherzhi** [projectcalico/cni-plugin#847]
![image](https://user-images.githubusercontent.com/47183904/76302072-5673d800-62fa-11ea-9571-2588503e4d75.png)

cni 3.11 ~ 3.13, not command hostname

**Comment by tmjd** [comment]
Thank you for submitting this.
Looks like we need to add `microdnf install hostname` to the dockerfiles.
I'm amazed this has not caused widespread errors in our testing.
