### ISSUE TITLE
Q. What does the allow_ip_forwarding option do?

### ISSUE THREAD

**Issue by koreansh4632** [projectcalico/cni-plugin#865]
https://docs.projectcalico.org/reference/cni-plugin/configuration#container_settings

I saw this document page, and I'm wondering what does the allow_ip_forwarding option do?
Is there any guys know about this feature?

**Comment by tmjd** [comment]
Seems like we're missing some documentation about that. But I think the name is descriptive for what it does. It allows IP forwarding inside containers.
See here https://github.com/projectcalico/cni-plugin/blob/d335c63c3184c9134a29ac20fcf87372232722a9/pkg/dataplane/linux/linux_dataplane.go#L375 for where it is used.
