### ISSUE TITLE
Support for linux/arm/v7

### ISSUE THREAD

**Issue by qbasicer** [projectcalico/cni-plugin#869]
I'm attempting to setup calico on my raspberry pi kubernetes cluster, and kubectl is reporting that the `calico-node` pods are in state `Init:ErrImagePull`.  Digging deeper, the error message is: `Failed to pull image "calico/cni:v3.11.2": rpc error: code = Unknown desc = no matching manifest for linux/arm/v7 in the manifest list entries`.  

## Expected Behavior
calico/cni images contain support for linux/arm/v7.

## Current Behavior
calico/cni images do not have support for linux/arm/v7.

## Steps to Reproduce (for bugs)
1. clean OS install of Raspbian v10 on either Raspberry Pi 3 or Raspberry Pi 4.
2. setup using kubeadm
3. run `kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml`
4. observe output of `kubectl get pods -n kube-system`

## Context
I'm trying to get kubernetes setup on a local raspberry pi network for testing purposes.  Since flannel is no longer recommended and I was having issues with weave, Calico appears to be the only real choice at this time.

## Your Environment
* Kubernetes v1.18.2
* CNI plugin version: 3.11.2
* CNI config: N/A
* Operating System and version: Rasbian Linux 10

**Comment by GijsvanDulmen** [comment]
Tried to checkout the source and build with `make build ARCH=arm` but it resulted in:
`k8s.io/client-go/kubernetes
github.com/projectcalico/libcalico-go/lib/backend/k8s/resources
github.com/projectcalico/libcalico-go/lib/backend/k8s
github.com/projectcalico/libcalico-go/lib/backend
github.com/projectcalico/libcalico-go/lib/clientv3
github.com/projectcalico/cni-plugin/internal/pkg/utils
make: *** [bin/arm/calico] Error 2`

**Comment by pgronau** [comment]
I can confirm.
The problem exists for 3.14.1 too.

**Comment by caseydavenport** [comment]
To sumamrize the currnet state here - Calico currently works for the following architectures:

- amd64
- arm64
- ppc64le

You can see the calico/cni image has these supported here: https://hub.docker.com/layers/calico/cni/v3.14.1/images/sha256-b35ff34b3d45999752579fd64afe3d897ff83bea0811edd261e16442e3609b0a?context=repo

Adding armv7 would be an ehnancement and would need a community backed contribution.

**Comment by youwalther65** [comment]
Problem still exists with 3.15.1. Just tested EKS with Bottlerocket OS 1.02 on Graviton 2. Any ETA would be highly appreciated.

**Comment by caseydavenport** [comment]
> Adding armv7 would be an ehnancement and would need a community backed contribution.

I'm not currently aware of anyone who is championing this. Any volunteers?

**Comment by aalaesar** [comment]
> > Adding armv7 would be an ehnancement and would need a community backed contribution.
> 
> I'm not currently aware of anyone who is championing this. Any volunteers?

Hey there

I managed to get calico built for arm/armhf a couple of weeks ago, (v3.16.5)
I used the <big> manifest for this version, just changing images for my own 
So far it's running "OK for now"* on my 6 rpi cluster (mix of 2b/3b & 3b+)

__(not very loaded for now, so  testing have been limited to a couple of services, nothing fancy )__

But i'm not considering the work to be anything near community support ready... very, very far from that.

I cross-compiled exclusively from amd64 so not sure I can test cross compiled binaries
I'll make [WIP] PR in the next days to add arm to the manifest so every one could enjoy  an all generation raspberry pi kubernetes cluster with calico as CNI.

To avoid the 'it works for me' joke,  images used are:
- aalaesar/calico-cni-plugin:armhf-v3.16.5
- aalaesar/calico-pod2daemon:v3.16.5-arm
- aalaesar/calico-node:3.16.5-arm
- aalaesar/calico-kube-controllers:v3.16.5-arm
for anyone willing to try.

Regards, 

Aal.

PS: even after reading dev et contributing guides, I'm still a little lost in the Makefiles. any hints from the project would be welcome 😃 


-------
*a.k.a: 'no smoke yet'

**Comment by lmm** [comment]
> PS: even after reading dev et contributing guides, I'm still a little lost in the Makefiles. any hints from the project would be welcome
Hey @aalaesar , if you've got specific questions about the makefile I might be able to help here or on our Slack channel. It might help to reference the common makefile that is sourced: https://github.com/projectcalico/go-build/blob/master/Makefile.common

**Comment by mibaboo** [comment]
Hi 

Any update on support for Graviton2? Any alternatives?

**Comment by caseydavenport** [comment]
ARMv7 should work in v3.21 now after all the great work done by @frozenprocess and @aalaesar
