### ISSUE TITLE
Featurerequest: Allow configuring ip forwarding on a container/pod level

### ISSUE THREAD

**Issue by alvaroaleman** [projectcalico/cni-plugin#872]
Currently, IP forwarding can only be configured globally in the CNI via the `allow_ip_forwarding` setting: https://github.com/projectcalico/cni-plugin/blob/bdbfef5b85c31df6f0c7522a47ce1a262e1f0361/pkg/types/types.go#L105

This means that if a single container needs this, it has to be activated for all containers.

In most cases, this is only needed for some very specific containers, but not for all. Thus it would be great if it was somehow possible to configure this on the container.

**Comment by tmjd** [comment]
I don't believe that it is necessary for Calico to set forwarding for individual pods, I think a pod should be able to set IP forwarding (/proc/sys/net/ipv4/ip_forward or /proc/sys/net/ipv6/conf/all/forwarding set to 1). I wonder if you could just run an init container to set those proc entries and enable ip forwarding.

**Comment by alvaroaleman** [comment]
@tmjd I thought calico would reset that flag if I set it myself from within the container?

**Comment by caseydavenport** [comment]
Calico doesn't currently reconcile sysctls within the pod's netns - it will disable it when the CNI plugin runs, but init containers run after CNI, so you should be able to configure sysctls within the container as you wish at that point, provided you have permission. 

host-side sysctls are a different story, though :D

**Comment by gerricchaplin** [comment]
@caseydavenport I know this is late to the party and it has been mentioned before that init containers can be used to set the required sysctls but allowing and using init containers in a privileged mode goes against the general direction of travel for K8s and various security benchmarks?

The alternative to init containers which are for example turning on IP forwarding on every container in the cluster perhaps a recipe for all sort of security implications.

Shouldn't our securityContext definitions take preference and on an individual basis?
