### ISSUE TITLE
mv requires care on SELinux enforcing systems

### ISSUE THREAD

**Issue by dghubble** [projectcalico/cni-plugin#874]
`install-cni.sh` uses `mv` to place the CNI configs. Use of `mv` affects the way SELinux context's are set for placed configs and binaries.

Related: With https://github.com/projectcalico/cni-plugin/pull/849 (v3.14.0), `install-cni.sh` switched from placing CNI binaries with `cp` to using `mv` which may cause related issues, depending on the setup.

## Current Behavior

Using `mv`, the SELinux context of moved files is kept as-is when its moved from temporary to final locations (mounted from host). That means the SELinux file context is determined when the temp file is written, which depends on the SELinux context the `calico/cni` container is run with.

With `cp`, the SELinux context of the target directory or host transition rules would determine the SELinux context of palced binary and conf files. 

Best described in https://danwalsh.livejournal.com/56534.html

## Expected Behavior

`calico/node` may run multiple times (due to pod restarts, anything, etc.) and must continue to be able to manage/write the CNI config and CNI binaries its responsible for. To do that, keeping a stable context across restarts is important ("shared" in container terms).

## Steps to Reproduce (for bugs)

On an SELinux enforicing system, I find this can be observed most readily in the CNI config file, if you restart a Calico pod (but not reboot the instance, as Kubelet service is often setup to do some relabling that corrects the issue).

```
mv: inter-device move failed: '/calico.conf.tmp' to '/host/etc/cni/net.d/10-calico.conflist'; unable to remove target: Permission denied
Failed to mv files. This may be caused by selinux configuration on the host, or something else.
```

Here, the host SELinux config isn't to blame imo. The first Calico pod runs install-cni as an init container and the written file carries the SELinux context of that container (random MCS pair). When Calico is restarted, the container will have a different pair and be unable to access the file (install-cni tries to write it every time) which causes the init container to fail over and over.

```
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0:c443,c515  646 May  9 22:07 10-calico.conflist 
-rw-------. 1 root root system_u:object_r:container_file_t:s0           2786 May  9 22:07 calico-kubeconfig
```

## Possible Solution

I don't have a "right" behavior per-se. Perhaps update Calico Kubernetes manifest examples to set a consistent SELinux context on the `calico/cni` container across restarts. Similar solutions on different platforms (I only use Kubernetes, don't have more context). Raise a bit of awareness/discussion here about how to handle these kinda of side-effects. Adjust logs to say there could be an SELinux-related problem, without casting it as a host problem.

```
          securityContext:
            seLinuxOptions:
              level: "s0"
```

## Your Environment

* CNI plugin version: v3.13.3, v3.14.0
* Orchestrator version: Kubernetes
* CNI config: v0.3.1
* Operating System and version: Fedora CoreOS
* Link to your project (optional): Typhoon

**Comment by caseydavenport** [comment]
@dghubble thanks for catching this.

It seems like setting a consistent context could work for this, though I'm not versed enough in SELinux just yet to know if there might be other implications of doing that. 

I wonder if, alternatively, we could do something like this:

- cp the temp file to the host, still as a temp/intermediate file
- mv the temp file that is now on the host host to its final resting position on the host.

IIUC, the initial cp will set the SELinux context to that of the host, and then the mv will succeed safely even if the existing file is in use (the original issue we were trying to solve). Does that seem right?

**Comment by dghubble** [comment]
I think that sounds right, though I'm no expert too. `cp` the `/calico.conf.tmp` file to the host mount location and, since the file doesn't exist, it gets the context of the directory, and the final move doesn't change the context. I remember Kubelet scanning for configs alphabetically in `--cni-conf-dir` so maybe that's a concern if Kubelet notices the tmp file or maybe that's outdated info these days.

Something related I looked at. I could not reproduce this issue in flannel's [install-cni](https://github.com/coreos/flannel-cni/blob/master/install-cni.sh#L13) despite it using the same technique, on the same Fedora CoreOS (enforcing) setup. Puzzling. I made some debug pods to exec inside (no mounts, just looking around):

```
apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    name: debug
spec:
  hostNetwork: true
  containers:
    - name: debug
      image: quay.io/calico/cni:v3.14.0
      command:
        - sleep
        - "36000"
```

```
# Pod quay.io/calico/cni:v3.14.0
ls -lZ /calico.conf.tmp 
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0:c170,c666 638 May  7 17:48 /calico.conf.tmp

# Pod 
ls -alZ /flannel.conflist.default
Uses busybox, no -Z flag or awareness of SELinux
```

It seems the Calico cni container is somewhat aware of SELinux (unlike flannel-cni) and `/calico.conf.tmp` exists and has initial SELinux attributes (the specific numbers will differ per pod run).

My theory is that `flannel-cni` is unaware of SELinux so when the file (no context) is moved to the host location it obtains a default context (aside: I'm not sure why the context isn't just "unlabeled", it seems the file written to the host mount gets context of the host directory). In calico-cni, the container starts with a `/calico.conf.tmp` that has an SELinux context, so `mv` preserves that context which is how the CNI config on host ended up with the MCS pair like c170,c666.

**Comment by realgaurav** [comment]
Hey @dghubble, sorry about the delay. I recently tried to reproduce the issue using typhoon:

```
module "tempest" {
  source = "git::https://github.com/poseidon/typhoon//aws/fedora-coreos/kubernetes?ref=v1.19.3"
```

I edited `calico-node` daemonset and removed the securityContext fix added in the repo for this ssue:

```
securityContext:
  seLinuxOptions:
    level: s0
```

After `calico-node` was ready, I tried restarting calico-node pods using rollout restart and also by deleting the pods directly (a few times). Each time all the pods came back up and ready without any issue.
```
kubectl rollout restart ds -n kube-system calico-node
...
kubectl delete pod -n kube-system calico-node-6m9t5 calico-node-qcpcn calico-node-6nljs
```

I am suspecting this could be because of a [recent change](https://github.com/projectcalico/cni-plugin/blob/release-v3.16/pkg/install/install.go) to the installation method. However I want to make sure I didn't miss any steps in the repro. Can you please check here or try reproducing the issue with `calico-node v3.16.3`? Thanks

**Comment by realgaurav** [comment]
@dghubble -- a gentle reminder to check if you got a chance to look at my comment :pray:

**Comment by dghubble** [comment]
Yeah, checking with Calico v3.16.5, the workaround of setting the init container `seLinuxOptions` doesn't seem required anymore for Calico pods to run after deletion/disruption. I'll look into removing it in future.

Thanks!
