### ISSUE TITLE
ppc64le image is wrongly built on dockerhub

### ISSUE THREAD

**Issue by runlevel5** [projectcalico/cni-plugin#875]
The `calico/cni:v3.14.0-0-g418f8a8-ppc64le` does not ship ppc64le binary.

![Screenshot_2020-05-15 calico cni Tags - Docker Hub](https://user-images.githubusercontent.com/135605/82001926-b3479200-969f-11ea-8ec1-51ee9e0a9a01.png)

You could clearly see in the screenshot above, the image OS is amd64, which is wrong.

## Expected Behavior

ppc64le binary

## Current Behavior

amd64 binary thus everytime I try to run on my ppc64le linux, I will get error:

```
{"msg":"exec container process `/usr/bin/bash`: Exec format error","level":"error","time":"2020-05-15T01:19:42.000961642Z"}
```

## Possible Solution

Just change the OS that semaphore target

## Context

This issue impacts version 3.13 or newer.

## Your Environment

* Operating System and version: Fedora 32 PPC64LE

**Comment by lmm** [comment]
Thanks for the reporting this, @runlevel5
