### ISSUE TITLE
initContainer succeeds even though copy of calico binary fails

### ISSUE THREAD

**Issue by sbueringer** [projectcalico/cni-plugin#877]
## Expected Behavior
If the calico binary cannot be copied, I expect the install-cni.sh sript to fail

## Current Behavior
We're running very frequent installations and in 99% of the cases everything works fine. I just had the case that the binary was not copied but install-cni.sh succeeded anyway so no retry was triggered. Output:
```
Wrote Calico CNI binaries to /host/opt/cni/bin
/install-cni.sh: line 96: /host/opt/cni/bin/calico: No such file or directory
CNI plugin version: 
/host/secondary-bin-dir is non-writeable, skipping
```

## Steps to Reproduce (for bugs)
I'm not sure if it's possible to reproduce this.
```bash
for path in /opt/cni/bin/*;
  do
    filename="$(basename "$path")"
    tmp=",$filename,"
    if [ "${SKIP_CNI_BINARIES#*$tmp}" != "$SKIP_CNI_BINARIES" ];
    then
      echo "$filename is in SKIP_CNI_BINARIES, skipping"
      continue
    fi
    if [ "${UPDATE_CNI_BINARIES}" != "true" ] && [ -f $dir/"$filename" ];
    then
      echo "$dir/$filename is already here and UPDATE_CNI_BINARIES isn't true, skipping"
      continue
    fi
    cp "$path" $dir/ || exit_with_error "Failed to copy $path to $dir. This may be caused by selinux configuration on the host, or something else."
  done

  echo "Wrote Calico CNI binaries to $dir"
  echo "CNI plugin version: $($dir/calico -v)"
```

It's unclear to me how the `cp` could succeed but it would be nice if `$($dir/calico -v)` would fail if 
the file cannot be found (`/install-cni.sh: line 96: /host/opt/cni/bin/calico: No such file or directory`). I guess it doesn't fail because it's executed in a subshell). Would it be possible to implement it in a way that the whole script fails if `calico -v` doesn't work?

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): 3.13
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.17
* Operating System and version: Ubuntu

**Comment by jperville** [comment]
Hello @sbueringer I ran into a bug similar to yours where `calico -v` fails but the init container still completes #891 . Your fix at #889 will certainly fix my issue too.
