### ISSUE TITLE
calico-node runs but is broken when the host `/opt` is mounted noexec

### ISSUE THREAD

**Issue by jperville** [projectcalico/cni-plugin#891]
## Expected Behavior

When `/opt` is mounted noexec on a calico-node host, calico should fail to initialize since binaries in `/opt/cni/bin` won't execute.

## Current Behavior

When `/opt` is mounted noexec on a calico-node host, the calico-node containers actually run, but they fail to produce a working network (node is NotReady, kubelet spams "Network plugin returns error: Missing CNI default network", there is no "cali*" interface in `ifconfig` output etc).

## Explanation and Possible Solution

The install-cni init container somehow does not exit non-zero when the calico executable fails to execute, despite use of `set -e` at the top of the shell script. I believe that the reason is that `calico -v` is executed within a `echo` statement, which swallows the non-exit code as explained in #889 and that the proposed fix in #889 also fixes this issue .

## Steps to Reproduce (for bugs)

1. provision a kubernetes cluster with kubespray with `kube_network_plugin=calico` set
2. before running Ansible, on each node of the kubernetes cluster, create a separate `/opt` partition and mount it with noexec flag (eg. add `/dev/mapper/vg-opt      /opt                    xfs     noexec        0 2` to `/etc/fstab`)
3. run Ansible to provision the kubernetes cluster
4. all kubernetes node running on hosts with noexec `/opt` are NotReady because of "Network plugin returns error: Missing CNI default network"
5. the log of the install-cni init container shows the following line : "/install-cni.sh: line 100: /host/opt/cni/bin/calico: Permission denied" but still completes successfully
6. run the following commands to investigate in details :

```
[root@kapitan ~]# kubectl get node
NAME      STATUS     ROLES    AGE   VERSION
kapitan   NotReady   master   98m   v1.18.2

[root@kapitan ~]# kubectl describe node kapitan
Name:               kapitan
Roles:              master
Labels:             applications=true
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=kapitan
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/crio/crio.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 10 Jun 2020 09:57:06 +0200
Taints:             node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  kapitan
  AcquireTime:     <unset>
  RenewTime:       Wed, 10 Jun 2020 11:36:40 +0200
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Wed, 10 Jun 2020 09:58:38 +0200   Wed, 10 Jun 2020 09:58:38 +0200   CalicoIsUp                   Calico is running on this node
  MemoryPressure       False   Wed, 10 Jun 2020 11:36:42 +0200   Wed, 10 Jun 2020 09:57:03 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Wed, 10 Jun 2020 11:36:42 +0200   Wed, 10 Jun 2020 09:57:03 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Wed, 10 Jun 2020 11:36:42 +0200   Wed, 10 Jun 2020 09:57:03 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                False   Wed, 10 Jun 2020 11:36:42 +0200   Wed, 10 Jun 2020 09:57:03 +0200   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network

[root@kapitan ~]# journalctl -f -u kubelet
-- Logs begin at Wed 2020-06-10 09:30:32 CEST. --
Jun 10 11:35:29 kapitan kubelet[7691]: E0610 11:35:29.821023    7691 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: Missing CNI default network

[root@kapitan ~]# 
[root@kapitan ~]# kubectl describe pod calico-node-stjbq  -n kube-system
(snip)
Events:
  Type     Reason     Age                From              Message
  ----     ------     ----               ----              -------
  Warning  Unhealthy  76s (x9 over 91m)  kubelet, kapitan  Liveness probe failed: command timed out
  Warning  Unhealthy  18s (x7 over 93m)  kubelet, kapitan  Readiness probe failed: command timed out

[root@kapitan ~]# kubectl logs -f calico-node-stjbq -c install-cni
Wrote Calico CNI binaries to /host/opt/cni/bin
/install-cni.sh: line 100: /host/opt/cni/bin/calico: Permission denied
CNI plugin version: 
/host/secondary-bin-dir is non-writeable, skipping
Using CNI config template from /host/etc/cni/net.d/calico.conflist.template.
CNI config: {
  "name": "cni0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "nodename": "kapitan",
          "type": "calico",
      "log_level": "info",
      "etcd_endpoints": "https://192.168.220.100:2379",
      "etcd_cert_file": "/etc/calico/certs/cert.crt",
      "etcd_key_file": "/etc/calico/certs/key.pem",
      "etcd_ca_cert_file": "/etc/calico/certs/ca_cert.crt",
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "ipv4_pools": ["10.233.64.0/18"]
      },
      "policy": {
        "type": "k8s"
      },      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
Created CNI config 10-calico.conflist
Done configuring CNI.  Sleep=false
```

## Context

I encountered this issue when upgrading from an earlier kubernetes version, where calico binaries were not stored in my noexec `/opt` but somewhere else on the filesystem.

## Your Environment
* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): `v3.14.0`
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.18.2
* Operating System and version: Centos 7.5

**Comment by caseydavenport** [comment]
https://github.com/projectcalico/cni-plugin/pull/889 was merged the other day and should fix the fact that the install script doesn't fail in Calico v3.15

In order to work on systems that don't allow our default directory to be written to, you will need to adjust the mount to be where the kubelet expects CNI plugins to be installed.
