### ISSUE TITLE
[Regression] calico-node v3.13.3 failed to start PodInitializing

### ISSUE THREAD

**Issue by runlevel5** [projectcalico/cni-plugin#893]
## Expected Behavior
calico-node pods started correctly

## Current Behavior
Get init error :(

## Possible Solution
Reverted to v3.13.2. I can confirm v3.13.3 introduced regression. Seems to only affect ppc64le version.

## Steps to Reproduce (for bugs)
1. `wget https://docs.projectcalico.org/manifests/calico.yaml && sed -i 's/v3\.14\.1/v3\.13\.3/g' /tmp/calico.yaml`
2. `kubectl apply -f calico.yaml`
3. `kubectl -n kube-system get pods` and get `calico-node-r49lz   0/1     Init:Error   3          74s`
4. Inspect logs with `kubectl -n kube-system logs -f calico-node-r49lz` and get `Error from server (BadRequest): container "calico-node" in pod "calico-node-r49lz" is waiting to start: PodInitializing`

## Your Environment
* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v3.13.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.18.2
* CNI config:
* Operating System and version: Ubuntu 18.0.4 bionic powerpc64le
* Link to your project (optional):

**Comment by runlevel5** [comment]
any guidance on how to get more debug info out of them is greatly appreciated

**Comment by caseydavenport** [comment]
@runlevel5 you could try `kubectl describe` on the pod to see what events have occurred. 

There's not much to go on with what is here

**Comment by kayanme** [comment]
Probably that is my more detailed issue [here](https://github.com/projectcalico/cni-plugin/issues/988#issue-757800973)
