### ISSUE TITLE
[CVEs] docker image on clair, view high level CVEs

### ISSUE THREAD

**Issue by aesirteam** [projectcalico/cni-plugin#894]
### CVEs lists:
High level:

- [RHSA-2020:0575](https://access.redhat.com/errata/RHSA-2020:0575)
- [RHSA-2020:0271](https://access.redhat.com/errata/RHSA-2020:0271)
- [RHSA-2020:0273](https://access.redhat.com/errata/RHSA-2020:0273)

Middle level:

- [RHSA-2020:1794](https://access.redhat.com/errata/RHSA-2020:1794)
- [RHSA-2020:1827](https://access.redhat.com/errata/RHSA-2020:1827)
- [RHSA-2020:1864](https://access.redhat.com/errata/RHSA-2020:1864)
- [RHSA-2020:1840](https://access.redhat.com/errata/RHSA-2020:1840)
- [RHSA-2020:1913](https://access.redhat.com/errata/RHSA-2020:1913)
- [RHSA-2020:1810](https://access.redhat.com/errata/RHSA-2020:1810)
- [RHSA-2020:1792 curl](https://access.redhat.com/errata/RHSA-2020:1792)
- [RHSA-2020:1792 libcurl](https://access.redhat.com/errata/RHSA-2020:1792)
- [RHSA-2020:1880](https://access.redhat.com/errata/RHSA-2020:1880)
- [RHSA-2020:1864](https://access.redhat.com/errata/RHSA-2020:1864)
- [RHSA-2020:1998](https://access.redhat.com/errata/RHSA-2020:1998)

![2020-06-18 17-58-53 的屏幕截图](https://user-images.githubusercontent.com/5821532/85006964-6f0f4c00-b18d-11ea-9aab-cb4135a1c730.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): v3.12.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* CNI config:
* Operating System and version:
* Link to your project (optional):

**Comment by aesirteam** [comment]
Ｕse  "RUN microdnf updata" into image, CVEs fixed! 
But create image stage by letter!

**Comment by caseydavenport** [comment]
xref https://github.com/projectcalico/node/issues/523

**Comment by caseydavenport** [comment]
These should be fixed in the latest Calico releases.
