### ISSUE TITLE
IP address leaks possible when allocating multiple addresses fails

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/cni-plugin#908]
Poor error handling between the CNI plugin and libcalico-go can lead to leaked IP addresses when allocating multiple IPs (in particular dual stack).

## Expected Behavior
In dual stack mode, when IPv6 address assignment fails due to exhaustion, no IPv4 address is leaked for that pod.

## Current Behavior
https://github.com/projectcalico/cni-plugin/blob/master/pkg/ipamplugin/ipam_plugin.go#L235-L261 never frees the IPv4 address that AutoAssign() assigned.

## Possible Solution
CNI plugin error handling needs to deal with AutoAssign() partially succeeding, or AutoAssign() mustn't partially succeed.

There may also be ways to cause AutoAssign() to return both an error and some allocated IPs as well, although they might be unhittable without a single call requesting multiple IPs.

## Steps to Reproduce (for bugs)
1. Exhaust the IPv6 pool.
2. Create a dual stack pod.
3. IP address should be leaked.

## Context
I've not actually reproduced this, just a code read, but it seems quite clear.

## Your Environment
Master

**Comment by mgleung** [comment]
This should be fixed with https://github.com/projectcalico/cni-plugin/pull/1010
