### ISSUE TITLE
Query: Can we use calico-ipam to allocate IPs to a SRIOV allocated interface in pod using multus NAD ?

### ISSUE THREAD

**Issue by superfix906** [projectcalico/cni-plugin#926]
Hi, Have a small query. I want to use the calico-ipam in place of a host-local/whereabouts IPAM plugin, such that it allows me to assign IPs from a dedicated IP Pool to a SRIOV allocated device inside the pod, using multus NetworkAttachmentDefinition (NAD). 

Today, multus NAD supports using host-local/whereabouts/etc IPAM plugins to allocate IP's to multiple devices in a pod, just wondering if this is supported in calico as well or if calico only provides IPAM for K8s Cluster Network.

Any help/pointers shall be appreciated. Am already using calico as my main CNI for POD CIDR, so will be great, if we can extend the IPAM functionality to network interfaces in the pods with a separate pool, as well. Thanks in advance !

**Comment by caseydavenport** [comment]
You can certainly try! Interested to know the results, so do report back.

This isn't something we test / normally support though, so you're definitely going off-road here.

**Comment by superfix906** [comment]
@caseydavenport thanks for replying. As per your inputs it doesn't look to fit our use case, as we had tried this.
