### ISSUE TITLE
tag version is not in order

### ISSUE THREAD

**Issue by michellew-vmware** [projectcalico/cni-plugin#935]
## Expected Behavior
We expect the tag is ordered by numeric sequence. 

## Current Behavior
3.15.2 is published on June
3.14.2: latest version

## Your Environment
We try to get latest version automatically. However, we always get 3.15.2 as latest version. But 3.14.2 is the right one we should use.
Could you please publish tag in numeric sequence?

**Comment by mgleung** [comment]
Hi @michellew-vmware. Thanks for bringing this to our attention. We use semantic versioning so while we may release some patch versions of a release after a minor release (in your example, we released `v3.15.1` before `v3.14.2`) those patch versions may not be the latest in that they have the newest features, but they do include some backwards compatible bug fixes for their minor version. If your goal is to find the latest release version (in terms of features) then I would recommend checking our [docs](https://docs.projectcalico.org/release-notes/) for the latest versions. The versions found there should always be ordered with the latest release being at the top of the page.
