### ISSUE TITLE
v3.16 CNI install fails to fill in the etcd TLS parameters

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/cni-plugin#944]
## Expected Behavior

The `etcd_` parameters in the config map should be substituted into the CNI config file.

## Current Behavior

Spotted by *behle* on Calico Users: Hello.  Are there any known issues with deploying Calico 3.16 in secure etcd datastore mode?  We are using the same yaml files we always have (very similar to the defaults provided), but for 3.16 the cni config files on the workers are missing the etcd cert/key/ca file paths:
```
"etcd_key_file": "",
"etcd_cert_file": "",
"etcd_ca_cert_file": "",
```
So it seems like the `__ETCD_KEY_FILE__` entries aren't being substituted properly
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* CNI config:
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
This should fix it: https://github.com/projectcalico/cni-plugin/pull/948
