### ISSUE TITLE
install-cni Init:CrashLoopBackOff on fresh install in v3.16

### ISSUE THREAD

**Issue by joshreic-db** [projectcalico/cni-plugin#957]
When applying the calico manifest and creating new nodes, calico-node pods on those new nodes end up in Init:CrashLoopBackOff. The error occurs in install-cni:

```
universe % k logs calico-node-zpjzg -n kube-system -c install-cni     
time="2020-10-01T04:48:31Z" level=info msg="Running as a Kubernetes pod" source="install.go:140"
time="2020-10-01T04:48:32Z" level=error msg="Failed to install /host/opt/cni/bin/bandwidth" error="open /host/opt/cni/bin/bandwidth: no such file or directory"
```

When I modify the manifest to use the v3.15.3 version of the install-cni container, the problem disappears
```
3709,3710c3707,3708
<           image: calico/cni:v3.15.3
<           command: ["/install-cni.sh"]`
---
>           image: calico/cni:v3.16.1
>           command: ["/opt/cni/bin/install"]
```

The issue does not appear on nodes which already had cni installed by an earlier version of the calico manifest.

## Expected Behavior
Normal installation

## Current Behavior
Init:CrashLoopBackoff

## Possible Solution

Looks like failure is occurring here: https://github.com/projectcalico/cni-plugin/blob/c880e82ab883ff1804498772efe4bc57bb05b95a/pkg/install/install.go#L208-L210. This code appears to be a go port of https://github.com/projectcalico/cni-plugin/blob/release-v3.15/k8s-install/scripts/install-cni.sh#L70-L97. I suspect it may be buggy/insufficiently tested. 

E.g., line 204 https://github.com/projectcalico/cni-plugin/blob/c880e82ab883ff1804498772efe4bc57bb05b95a/pkg/install/install.go#L204 looks like it should be instead be 
```
if fileExists(target) && !c.UpdateCNIBinaries {
``` 
(if file already exists and we **aren't** updating binaries, skip) which would match the corresponding logic in the previous `install-cni.sh` https://github.com/projectcalico/cni-plugin/blob/release-v3.15/k8s-install/scripts/install-cni.sh#L87

## Steps to Reproduce (for bugs)

1. Apply calico manifest
2. Spin up new nodes
3. Watch calico-node pods on new nodes go into Init:CrashLoopBackoff

## Your Environment

* OS: centos 
* arch: amd64.CNI plugin version (e.g. `/opt/cni/bin/calico --version`):
* kubernetes Client Version: v1.16.10, Server Version: v1.16.12
* manifest https://docs.projectcalico.org/manifests/calico-typha.yaml (current version 3.16.1)

**Comment by fasaxc** [comment]
Thanks for the detailed analysis.  I wonder how this gets through our testing.  We test over 250 combinations of k8s installer, version, OS, arch etc.  They all do fresh installs.

How _exactly_ do you install k8s; is this kubeadm, home mad terraform, etc?  We test with various installer, I wonder if all the ones we test pre-install the bandwidth plugin (or something like that).

**Comment by joshreic-db** [comment]
Homegrown terraform. I looked into our ansible and it appears that we are setting up our cni on the images using the following rule.
```
name: yum install cni
  become: yes
  shell: |
    yum -y install containernetworking-plugins
    mkdir -p /opt/cni/bin
    ln -sf /usr/libexec/cni/* /opt/cni/bin
```
I'm guessing perhaps the new code has trouble w/ doing a CopyFileAndPermissions onto a symlink?

**Comment by fasaxc** [comment]
@ipochi Assuming you're on flatcar?  Do you have a symlink for /opt/cni/bin too?

**Comment by ipochi** [comment]
@fasaxc 
```
 readlink /opt/cni/bin/
```

shows nothing.

**Comment by ipochi** [comment]
It was a mistake from my end. I forgot to change a file in the update process.
Resolved.

**Comment by mgleung** [comment]
The issue with the symlinks should be fixed with https://github.com/projectcalico/cni-plugin/pull/966 and the issue with the wrong logic around `UPDATE_CNI_BINARIES` should be fixed with https://github.com/projectcalico/cni-plugin/pull/979
