### ISSUE TITLE
On pod interface flap routes are not repopulated

### ISSUE THREAD

**Issue by VivekThrivikraman-est** [projectcalico/cni-plugin#986]
## Expected Behavior

On pod interface flapping(ifdown followed by ifup) kernel routing table should be repopulated

## Current Behavior

On pod interface flapping(ifdown followed by ifup) kernel routing table entries are empty

## Steps to Reproduce (for bugs)

1.  Check Ip routes inside pod before ifdown:
ip route
{{ default via 169.254.1.1 dev eth0}}
{{ 169.254.1.1 dev eth0 scope link}} 

2. Bring down pod eth0 interface :
 ifconfig eth0 down 

3.Bring up pod eth0 interface:
ifconfig eth0 up

4.Check ip routes inside the pod:
ip route

## Context

Livez probe was configured for the Pod, and flap of pod interface was done. After port flap, pod appeared to be in permanent crashloopbackoff state. CrashLoopBackoff restarted the failing container, though the container was restarted, the Pod was not restarted.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`):v3.9.6
* Orchestrator version (e.g. kubernetes, mesos, rkt):v1.19
* CNI config:
* Operating System and version:
* Link to your project (optional):

**Comment by lmm** [comment]
Hi @VivekThrivikraman-est . v3.9.6 is pretty old, if possible I would highly recommend using a recent version of Calico (we're at v3.17 now!) 🙂 

I know that Felix monitors the host-side of the veth pairs but I'm not sure what happens when the interface on the pod flaps as you're testing. I wonder if @caseydavenport knows

Out of curiosity what is causing the pod interface flapping?

**Comment by VivekThrivikraman-est** [comment]
> Hi @VivekThrivikraman-est . v3.9.6 is pretty old, if possible I would highly recommend using a recent version of Calico (we're at v3.17 now!) 🙂
> 
> I know that Felix monitors the host-side of the veth pairs but I'm not sure what happens when the interface on the pod flaps as you're testing. I wonder if @caseydavenport knows
> 
> Out of curiosity what is causing the pod interface flapping?

Will try with newer version of Calico. This was done as part of system testing and flapping was a manual operation.

**Comment by song-jiang** [comment]
@VivekThrivikraman-est Have you tried new version?

**Comment by caseydavenport** [comment]
@VivekThrivikraman-est I believe this is expected - there is nothing maintaining the routes _within_ each pod. Those are configured by the CNI plugin at pod launch and aren't touched afterwards.

Why are you bringing the interface down to begin with?

**Comment by VivekThrivikraman-est** [comment]
Yes I think the issue can be closed, it doesn't look like there could be a use case where there would be a port flap(unless manually done) unlike with physical interfaces.
